# pylint: disable=too-many-lines
from collections.abc import (
    Callable,
)
from datetime import (
    datetime,
)
from db_model.enums import (
    GitCloningStatus,
)
from db_model.groups.enums import (
    GroupLanguage,
    GroupManaged,
    GroupService,
    GroupStateStatus,
    GroupSubscriptionType,
    GroupTier,
)
from db_model.groups.types import (
    Group,
    GroupFile,
    GroupState,
)
from db_model.organization_access.types import (
    OrganizationAccess,
)
from db_model.organizations.enums import (
    OrganizationStateStatus,
)
from db_model.organizations.types import (
    Organization,
    OrganizationDocuments,
    OrganizationPaymentMethods,
    OrganizationState,
)
from db_model.roots.enums import (
    RootStatus,
    RootType,
)
from db_model.roots.types import (
    GitRoot,
    GitRootCloning,
    GitRootState,
    RootUnreliableIndicators,
)
from db_model.stakeholders.types import (
    NotificationsParameters,
    NotificationsPreferences,
    Stakeholder,
    StakeholderPhone,
    StakeholderSessionToken,
    StakeholderState,
    StakeholderTours,
    StateSessionType,
)
from db_model.types import (
    Policies,
)
from decimal import (
    Decimal,
)
import pytest
from typing import (
    Any,
)

MOCKED_DATA: dict[str, dict[str, Any]] = {
    "mailer.common.Dataloaders.stakeholder": {
        '["nonexistinguser@fluidattacks.com"]': None,
        '["integratesmanager@gmail.com"]': Stakeholder(
            email="integratesmanager@gmail.com",
            enrolled=True,
            first_name="Integrates",
            is_concurrent_session=False,
            is_registered=True,
            last_login_date=datetime.fromisoformat(
                "2020-12-31T16:50:17+00:00"
            ),
            last_name="Manager",
            legal_remember=True,
            phone=StakeholderPhone(
                country_code="CO",
                calling_country_code="57",
                national_number="1234567894",
            ),
            registration_date=datetime.fromisoformat(
                "2018-02-28T16:54:12+00:00"
            ),
            role="admin",
            session_key=None,
            session_token=None,
            state=StakeholderState(
                modified_by="integratesmanager@gmail.com",
                modified_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                notifications_preferences=NotificationsPreferences(
                    available=[],
                    email=[
                        "ACCESS_GRANTED",
                        "AGENT_TOKEN",
                        "EVENT_REPORT",
                        "FILE_UPDATE",
                        "GROUP_INFORMATION",
                        "GROUP_REPORT",
                        "NEW_COMMENT",
                        "NEW_DRAFT",
                        "PORTFOLIO_UPDATE",
                        "REMEDIATE_FINDING",
                        "REMINDER_NOTIFICATION",
                        "ROOT_UPDATE",
                        "SERVICE_UPDATE",
                        "UNSUBSCRIPTION_ALERT",
                        "UPDATED_TREATMENT",
                        "VULNERABILITY_ASSIGNED",
                        "VULNERABILITY_REPORT",
                    ],
                    sms=[],
                    parameters=NotificationsParameters(
                        min_severity=Decimal("3.0")
                    ),
                ),
            ),
            tours=StakeholderTours(
                new_group=False,
                new_root=False,
                new_risk_exposure=False,
                welcome=False,
            ),
        ),
    },
    "mailer.common.get_recipient_first_name": {
        '["nonexisting@nonexisting.com"]': None,
        '["unittest@fluidattacks.com"]': "Miguel",
    },
    "mailer.events.Dataloaders.root": {
        '["unittesting", "4039d098-ffc5-4984-8ed3-eb17bca98e19"]': GitRoot(
            cloning=GitRootCloning(
                modified_date=datetime.fromisoformat(
                    "2020-11-19T13:39:10+00:00"
                ),
                reason="root OK",
                status=GitCloningStatus.OK,
                commit="5b5c92105b5c92105b5c92105b5c92105b5c9210",
                commit_date=datetime.fromisoformat(
                    "2022-02-15T18:45:06.493253+00:00"
                ),
            ),
            created_by="jdoe@fluidattacks.com",
            created_date=datetime.fromisoformat("2020-11-19T13:37:10+00:00"),
            group_name="unittesting",
            id="4039d098-ffc5-4984-8ed3-eb17bca98e19",
            organization_name="okada",
            state=GitRootState(
                branch="master",
                environment="production",
                includes_health_check=True,
                modified_by="jdoe@fluidattacks.com",
                modified_date=datetime.fromisoformat(
                    "2020-11-19T13:37:10+00:00"
                ),
                nickname="universe",
                status=RootStatus.ACTIVE,
                url="https://gitlab.com/fluidattacks/universe",
                credential_id=None,
                gitignore=["bower_components/*", "node_modules/*"],
                other=None,
                reason=None,
                use_vpn=False,
            ),
            type=RootType.GIT,
            unreliable_indicators=RootUnreliableIndicators(
                unreliable_code_languages=[],
                unreliable_last_status_update=datetime.fromisoformat(
                    "2020-11-19T13:37:10+00:00"
                ),
            ),
        )
    },
    "mailer.events.Dataloaders.stakeholder": {
        '["unittesting"]': [
            Stakeholder(
                email="continuoushack2@gmail.com",
                enrolled=True,
                first_name="Continuous2",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T15:45:37+00:00"
                ),
                last_name="Hacking",
                legal_remember=True,
                phone=StakeholderPhone(
                    country_code="CO",
                    calling_country_code="57",
                    national_number="1234567892",
                ),
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="user",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="continuoushack2@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=True,
                    new_root=True,
                    new_risk_exposure=True,
                    welcome=True,
                ),
            ),
            Stakeholder(
                email="continuoushacking@gmail.com",
                enrolled=True,
                first_name="Continuous",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T15:45:37+00:00"
                ),
                last_name="Hacking",
                legal_remember=True,
                phone=StakeholderPhone(
                    country_code="CO",
                    calling_country_code="57",
                    national_number="1234567893",
                ),
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="continuoushacking@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="customer_manager@fluidattacks.com",
                enrolled=True,
                first_name="System",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Owner",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2021-08-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="customer_manager@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2018-08-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="dbetancur@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T16:50:17+00:00"
                ),
                last_name="Manager",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="admin",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="forces.unittesting@fluidattacks.com",
                enrolled=True,
                first_name="",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=None,
                last_name="",
                legal_remember=True,
                phone=None,
                registration_date=None,
                role="user",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integrateshacker@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Hacker",
                legal_remember=False,
                phone=StakeholderPhone(
                    country_code="CO",
                    calling_country_code="57",
                    national_number="1234567895",
                ),
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesmanager@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T16:50:17+00:00"
                ),
                last_name="Manager",
                legal_remember=True,
                phone=StakeholderPhone(
                    country_code="CO",
                    calling_country_code="57",
                    national_number="1234567891",
                ),
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="admin",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="integratesmanager@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=True,
                    new_root=True,
                    new_risk_exposure=True,
                    welcome=True,
                ),
            ),
            Stakeholder(
                email="integratesmanager@gmail.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T16:50:17+00:00"
                ),
                last_name="Manager",
                legal_remember=True,
                phone=StakeholderPhone(
                    country_code="CO",
                    calling_country_code="57",
                    national_number="1234567894",
                ),
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="admin",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="integratesmanager@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesreattacker@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Reattacker",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesresourcer@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Resourcer",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="integratesresourcer@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "EVENT_REPORT",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesreviewer@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Reviewer",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesserviceforces@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Service Forces",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="user",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesuser2@fluidattacks.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Internal Manager",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="user",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesuser2@gmail.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Customer",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="user",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="integratesuser2@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "EVENT_REPORT",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="integratesuser@gmail.com",
                enrolled=True,
                first_name="Integrates",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="User",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="user",
                session_key=None,
                session_token=StakeholderSessionToken(
                    jti="0f98c8d494be2c9eddd973e4a861483988a1d90bb268be48dfc442d0b4cada72",  # noqa: E501 pylint: disable=line-too-long
                    state=StateSessionType.IS_VALID,
                ),
                state=StakeholderState(
                    modified_by="integratesuser@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="unittest2@fluidattacks.com",
                enrolled=True,
                first_name="Group",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Manager",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2018-02-28T16:54:12+00:00"
                ),
                role="hacker",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by="unittest2@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2018-02-28T16:54:12+00:00"
                    ),
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[
                            "ACCESS_GRANTED",
                            "AGENT_TOKEN",
                            "EVENT_REPORT",
                            "FILE_UPDATE",
                            "GROUP_INFORMATION",
                            "GROUP_REPORT",
                            "NEW_COMMENT",
                            "NEW_DRAFT",
                            "PORTFOLIO_UPDATE",
                            "REMEDIATE_FINDING",
                            "REMINDER_NOTIFICATION",
                            "ROOT_UPDATE",
                            "SERVICE_UPDATE",
                            "UNSUBSCRIPTION_ALERT",
                            "UPDATED_TREATMENT",
                            "VULNERABILITY_ASSIGNED",
                            "VULNERABILITY_REPORT",
                        ],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="unittest@fluidattacks.com",
                enrolled=True,
                first_name="Miguel",
                is_concurrent_session=False,
                is_registered=True,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="de Orellana",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2019-02-28T16:54:12+00:00"
                ),
                role="admin",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
            Stakeholder(
                email="vulnmanager@gmail.com",
                enrolled=True,
                first_name="Vooln",
                is_concurrent_session=False,
                is_registered=False,
                last_login_date=datetime.fromisoformat(
                    "2020-12-31T18:40:37+00:00"
                ),
                last_name="Manager",
                legal_remember=True,
                phone=None,
                registration_date=datetime.fromisoformat(
                    "2022-02-16T04:54:55+00:00"
                ),
                role="user",
                session_key=None,
                session_token=None,
                state=StakeholderState(
                    modified_by=None,
                    modified_date=None,
                    notifications_preferences=NotificationsPreferences(
                        available=[],
                        email=[],
                        sms=[],
                        parameters=NotificationsParameters(
                            min_severity=Decimal("3.0")
                        ),
                    ),
                ),
                tours=StakeholderTours(
                    new_group=False,
                    new_root=False,
                    new_risk_exposure=False,
                    welcome=False,
                ),
            ),
        ]
    },
    "mailer.events.get_group_stakeholders_emails": {
        '["unittesting"]': "['continuoushack2@gmail.com', "
        "'continuoushacking@gmail.com', 'customer_manager@fluidattacks.com', "
        "'forces.unittesting@fluidattacks.com', "
        "'integrateshacker@fluidattacks.com', "
        "'integratesmanager@fluidattacks.com', 'integratesmanager@gmail.com', "
        "'integratesreattacker@fluidattacks.com', "
        "'integratesresourcer@fluidattacks.com', "
        "'integratesreviewer@fluidattacks.com', "
        "'integratesserviceforces@fluidattacks.com', "
        "'integratesuser2@fluidattacks.com', 'integratesuser2@gmail.com', "
        "'integratesuser@gmail.com', 'unittest2@fluidattacks.com', "
        "'unittest@fluidattacks.com', 'vulnmanager@gmail.com']"
    },
    "mailer.events.get_organization_name": {'["unittesting"]': "okada"},
    "mailer.events.send_mails_async": {
        '["unittesting", "4039d098-ffc5-4984-8ed3-eb17bca98e19", '
        '"AUTHORIZATION_SPECIAL_ATTACK", "Test", null, "538745942"]': None,
        '["unittesting", "4039d098-ffc5-4984-8ed3-eb17bca98e19", '
        '"AUTHORIZATION_SPECIAL_ATTACK", "Test", "PROBLEM_SOLVED", '
        '"538745942"]': None,
        '["unittesting", "4039d098-ffc5-4984-8ed3-eb17bca98e19", '
        '"AUTHORIZATION_SPECIAL_ATTACK", "Test", "OTHER", "538745942"]': None,
    },
    "mailer.utils.authz.get_group_level_role": {
        '["customer_manager@fluidattacks.com"]': ["", "", "customer_manager"],
    },
    "mailer.utils.authz.get_organization_level_role": {
        '["customer_manager@fluidattacks.com"]': ["customer_manager"],
    },
    "mailer.utils.Dataloaders.group": {
        '["unittesting"]': Group(
            created_by="unknown",
            created_date=datetime.fromisoformat("2018-03-08T00:43:18+00:00"),
            description="Integrates unit test group",
            language=GroupLanguage.EN,
            name="unittesting",
            organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
            state=GroupState(
                has_machine=True,
                has_squad=True,
                managed=GroupManaged.NOT_MANAGED,
                modified_by="unknown",
                modified_date=datetime.fromisoformat(
                    "2018-03-08T00:43:18+00:00"
                ),
                status=GroupStateStatus.ACTIVE,
                tier=GroupTier.MACHINE,
                type=GroupSubscriptionType.CONTINUOUS,
                tags={"test-groups", "test-updates", "test-tag"},
                comments=None,
                justification=None,
                payment_id=None,
                pending_deletion_date=None,
                service=GroupService.WHITE,
            ),
            agent_token=None,
            business_id="14441323",
            business_name="Testing Company and Sons",
            context="Group context test",
            disambiguation="Disambiguation test",
            files=[
                GroupFile(
                    description="Test",
                    file_name="test.zip",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-03-01T20:21:00+00:00"
                    ),
                ),
                GroupFile(
                    description="shell",
                    file_name="shell.exe",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-04-24T19:56:00+00:00"
                    ),
                ),
                GroupFile(
                    description="shell2",
                    file_name="shell2.exe",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-04-24T19:59:00+00:00"
                    ),
                ),
                GroupFile(
                    description="eerweterterter",
                    file_name="asdasd.py",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-08-06T19:28:00+00:00"
                    ),
                ),
            ],
            policies=Policies(
                modified_date=datetime.fromisoformat(
                    "2023-02-15T20:07:57+00:00"
                ),
                modified_by="integratesmanager@gmail.com",
                inactivity_period=None,
                max_acceptance_days=None,
                max_acceptance_severity=None,
                max_number_acceptances=None,
                min_acceptance_severity=None,
                min_breaking_severity=None,
                vulnerability_grace_period=None,
            ),
            sprint_duration=2,
            sprint_start_date=datetime.fromisoformat("2022-05-31T00:00:00"),
        ),
    },
    "mailer.utils.Dataloaders.organization": {
        '["unittesting"]': Organization(
            created_by="unknown@unknown.com",
            created_date=datetime.fromisoformat("2018-02-08T00:43:18+00:00"),
            id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
            name="okada",
            policies=Policies(
                modified_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                modified_by="integratesmanager@gmail.com",
                inactivity_period=90,
                max_acceptance_days=60,
                max_acceptance_severity=Decimal("10.0"),
                max_number_acceptances=2,
                min_acceptance_severity=Decimal("0.0"),
                min_breaking_severity=Decimal("0"),
                vulnerability_grace_period=0,
            ),
            state=OrganizationState(
                status=OrganizationStateStatus.ACTIVE,
                modified_by="unknown",
                modified_date=datetime.fromisoformat(
                    "2018-02-08T00:43:18+00:00"
                ),
                pending_deletion_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
            ),
            country="Colombia",
            payment_methods=[
                OrganizationPaymentMethods(
                    id="38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                    business_name="Fluid",
                    email="test@fluidattacks.com",
                    country="Colombia",
                    state="Antioquia",
                    city="Medellín",
                    documents=OrganizationDocuments(rut=None, tax_id=None),
                ),
                OrganizationPaymentMethods(
                    id="4722b0b7-cfeb-4898-8308-185dfc2523bc",
                    business_name="Testing Company and Sons",
                    email="test@fluidattacks.com",
                    country="Colombia",
                    state="Antioquia",
                    city="Medellín",
                    documents=OrganizationDocuments(rut=None, tax_id=None),
                ),
            ],
            billing_customer=None,
            vulnerabilities_url=None,
        )
    },
    "mailer.utils.Dataloaders.organization_groups": {
        '["ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3"]': [
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates continuous group",
                language=GroupLanguage.EN,
                name="continuoustesting",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.SQUAD,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"another-tag", "test-tag"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=[
                    GroupFile(
                        description="shell2",
                        file_name="shell2.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:59:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="asdasd",
                        file_name="asdasd.py",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-08-06T19:28:00+00:00"
                        ),
                    ),
                ],
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2019-01-20T22:00:00+00:00"
                ),
                description="oneshot testing",
                language=GroupLanguage.EN,
                name="oneshottest",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-01-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.ONESHOT,
                    type=GroupSubscriptionType.ONESHOT,
                    tags={
                        "another-tag",
                        "test-groups",
                        "test-updates",
                        "test-tag",
                    },
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.BLACK,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2021-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=None,
                    max_acceptance_days=90,
                    max_acceptance_severity=Decimal("3.9"),
                    max_number_acceptances=3,
                    min_acceptance_severity=Decimal("0"),
                    min_breaking_severity=Decimal("3.9"),
                    vulnerability_grace_period=10,
                ),
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-05-08T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2018-03-08T00:43:18+00:00"
                ),
                description="Integrates unit test group",
                language=GroupLanguage.EN,
                name="unittesting",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2018-03-08T00:43:18+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.MACHINE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-groups", "test-updates", "test-tag"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context="Group context test",
                disambiguation="Disambiguation test",
                files=[
                    GroupFile(
                        description="Test",
                        file_name="test.zip",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-03-01T20:21:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="shell",
                        file_name="shell.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:56:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="shell2",
                        file_name="shell2.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:59:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="eerweterterter",
                        file_name="asdasd.py",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-08-06T19:28:00+00:00"
                        ),
                    ),
                ],
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2023-02-15T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=None,
                    max_acceptance_days=None,
                    max_acceptance_severity=None,
                    max_number_acceptances=None,
                    min_acceptance_severity=None,
                    min_breaking_severity=None,
                    vulnerability_grace_period=None,
                ),
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-05-31T00:00:00"
                ),
            ),
        ]
    },
    "mailer.utils.Dataloaders.stakeholder_organizations_access": {
        '["customer_manager@fluidattacks.com"]': [
            OrganizationAccess(
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                email="customer_manager@fluidattacks.com",
                expiration_time=None,
                has_access=None,
                invitation=None,
                role="customer_manager",
            )
        ]
    },
    "mailer.utils.get_org_groups": {
        '["customer_manager@fluidattacks.com"]': [
            [
                Group(
                    created_by="unknown",
                    created_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    description="Integrates continuous group",
                    language=GroupLanguage.EN,
                    name="continuoustesting",
                    organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                    state=GroupState(
                        has_machine=True,
                        has_squad=True,
                        managed=GroupManaged.NOT_MANAGED,
                        modified_by="unknown",
                        modified_date=datetime.fromisoformat(
                            "2020-05-20T22:00:00+00:00"
                        ),
                        status=GroupStateStatus.ACTIVE,
                        tier=GroupTier.SQUAD,
                        type=GroupSubscriptionType.CONTINUOUS,
                        tags={"another-tag", "test-tag"},
                        comments=None,
                        justification=None,
                        payment_id=None,
                        pending_deletion_date=None,
                        service=GroupService.WHITE,
                    ),
                    agent_token=None,
                    business_id="14441323",
                    business_name="Testing Company and Sons",
                    context=None,
                    disambiguation=None,
                    files=[
                        GroupFile(
                            description="shell2",
                            file_name="shell2.exe",
                            modified_by="unittest@fluidattacks.com",
                            modified_date=datetime.fromisoformat(
                                "2019-04-24T19:59:00+00:00"
                            ),
                        ),
                        GroupFile(
                            description="asdasd",
                            file_name="asdasd.py",
                            modified_by="unittest@fluidattacks.com",
                            modified_date=datetime.fromisoformat(
                                "2019-08-06T19:28:00+00:00"
                            ),
                        ),
                    ],
                    policies=None,
                    sprint_duration=2,
                    sprint_start_date=datetime.fromisoformat(
                        "2022-06-06T00:00:00"
                    ),
                ),
                Group(
                    created_by="unknown",
                    created_date=datetime.fromisoformat(
                        "2019-01-20T22:00:00+00:00"
                    ),
                    description="oneshot testing",
                    language=GroupLanguage.EN,
                    name="oneshottest",
                    organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                    state=GroupState(
                        has_machine=True,
                        has_squad=False,
                        managed=GroupManaged.NOT_MANAGED,
                        modified_by="unknown",
                        modified_date=datetime.fromisoformat(
                            "2019-01-20T22:00:00+00:00"
                        ),
                        status=GroupStateStatus.ACTIVE,
                        tier=GroupTier.ONESHOT,
                        type=GroupSubscriptionType.ONESHOT,
                        tags={
                            "another-tag",
                            "test-groups",
                            "test-updates",
                            "test-tag",
                        },
                        comments=None,
                        justification=None,
                        payment_id=None,
                        pending_deletion_date=None,
                        service=GroupService.BLACK,
                    ),
                    agent_token=None,
                    business_id="14441323",
                    business_name="Testing Company and Sons",
                    context=None,
                    disambiguation=None,
                    files=None,
                    policies=Policies(
                        modified_date=datetime.fromisoformat(
                            "2021-11-22T20:07:57+00:00"
                        ),
                        modified_by="integratesmanager@gmail.com",
                        inactivity_period=None,
                        max_acceptance_days=90,
                        max_acceptance_severity=Decimal("3.9"),
                        max_number_acceptances=3,
                        min_acceptance_severity=Decimal("0"),
                        min_breaking_severity=Decimal("3.9"),
                        vulnerability_grace_period=10,
                    ),
                    sprint_duration=2,
                    sprint_start_date=datetime.fromisoformat(
                        "2022-05-08T00:00:00"
                    ),
                ),
                Group(
                    created_by="unknown",
                    created_date=datetime.fromisoformat(
                        "2018-03-08T00:43:18+00:00"
                    ),
                    description="Integrates unit test group",
                    language=GroupLanguage.EN,
                    name="unittesting",
                    organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                    state=GroupState(
                        has_machine=True,
                        has_squad=True,
                        managed=GroupManaged.NOT_MANAGED,
                        modified_by="unknown",
                        modified_date=datetime.fromisoformat(
                            "2018-03-08T00:43:18+00:00"
                        ),
                        status=GroupStateStatus.ACTIVE,
                        tier=GroupTier.MACHINE,
                        type=GroupSubscriptionType.CONTINUOUS,
                        tags={"test-groups", "test-updates", "test-tag"},
                        comments=None,
                        justification=None,
                        payment_id=None,
                        pending_deletion_date=None,
                        service=GroupService.WHITE,
                    ),
                    agent_token=None,
                    business_id="14441323",
                    business_name="Testing Company and Sons",
                    context="Group context test",
                    disambiguation="Disambiguation test",
                    files=[
                        GroupFile(
                            description="Test",
                            file_name="test.zip",
                            modified_by="unittest@fluidattacks.com",
                            modified_date=datetime.fromisoformat(
                                "2019-03-01T20:21:00+00:00"
                            ),
                        ),
                        GroupFile(
                            description="shell",
                            file_name="shell.exe",
                            modified_by="unittest@fluidattacks.com",
                            modified_date=datetime.fromisoformat(
                                "2019-04-24T19:56:00+00:00"
                            ),
                        ),
                        GroupFile(
                            description="shell2",
                            file_name="shell2.exe",
                            modified_by="unittest@fluidattacks.com",
                            modified_date=datetime.fromisoformat(
                                "2019-04-24T19:59:00+00:00"
                            ),
                        ),
                        GroupFile(
                            description="eerweterterter",
                            file_name="asdasd.py",
                            modified_by="unittest@fluidattacks.com",
                            modified_date=datetime.fromisoformat(
                                "2019-08-06T19:28:00+00:00"
                            ),
                        ),
                    ],
                    policies=Policies(
                        modified_date=datetime.fromisoformat(
                            "2023-02-15T20:07:57+00:00"
                        ),
                        modified_by="integratesmanager@gmail.com",
                        inactivity_period=None,
                        max_acceptance_days=None,
                        max_acceptance_severity=None,
                        max_number_acceptances=None,
                        min_acceptance_severity=None,
                        min_breaking_severity=None,
                        vulnerability_grace_period=None,
                    ),
                    sprint_duration=2,
                    sprint_start_date=datetime.fromisoformat(
                        "2022-05-31T00:00:00"
                    ),
                ),
            ]
        ]
    },
    "mailer.utils.get_stakeholder_roles": {
        '["customer_manager@fluidattacks.com"]': {
            "group": {"customer_manager"},
            "org": {"customer_manager"},
        }
    },
    "mailer.utils.get_stakeholders_email_by_preferences": {
        '["unittesting", "user_unsubscribed"]': [
            "continuoushack2@gmail.com",
            "continuoushacking@gmail.com",
            "customer_manager@fluidattacks.com",
            "integratesuser@gmail.com",
            "unittest2@fluidattacks.com",
        ]
    },
}


@pytest.fixture
def mock_data_for_module(
    *,
    resolve_mock_data: Callable,
) -> Any:
    def _mock_data_for_module(
        mock_path: str, mock_args: list[Any], module_at_test: str
    ) -> Callable[[str, list[Any], str], Any]:
        return resolve_mock_data(
            mock_data=MOCKED_DATA,
            mock_path=mock_path,
            mock_args=mock_args,
            module_at_test=module_at_test,
        )

    return _mock_data_for_module
