boto3: 1.26.131
bugsnag: 3.9.0
category-encoders: 2.2.2
click: 7.1.2
cryptography: 40.0.1
Cython: 0.29.33
GitPython: 3.1.29
gql: 3.0.0a6
imbalanced-learn: 0.10.1
joblib: 1.2.0
jsonschema: 4.18.3
mixpanel: 4.5.0
more-itertools: 8.5.0
mypy-extensions: 0.4.3
numpy: 1.23.2
oldest-supported-numpy: 2022.11.19
pandas: 1.5.3
prettytable: 1.0.1
protobuf: 3.20.0
PyDriller: 1.15.2
python-gitlab: 3.15.0
pytz: "2020.1"
pyyaml: "6.0"
requests: 2.25.0
sagemaker: 2.163.0
scikit-learn: 1.2.1
tqdm: 4.62.2
xgboost: 1.6.2
