# pylint: disable=too-many-lines
from collections.abc import (
    Callable,
)
from datetime import (
    datetime,
)
from db_model.groups.enums import (
    GroupLanguage,
    GroupManaged,
    GroupService,
    GroupStateStatus,
    GroupSubscriptionType,
    GroupTier,
)
from db_model.groups.types import (
    Group,
    GroupFile,
    GroupState,
)
from db_model.organizations.enums import (
    OrganizationStateStatus,
)
from db_model.organizations.types import (
    Organization,
    OrganizationDocuments,
    OrganizationPaymentMethods,
    OrganizationState,
)
from db_model.types import (
    Policies,
)
from decimal import (
    Decimal,
)
import pytest
from typing import (
    Any,
)

MOCKED_DATA: dict[str, dict[str, Any]] = {
    "organizations.domain.Dataloaders.group": {
        '["madeupgroup"]': None,
        '["unittesting"]': Group(
            created_by="unknown",
            created_date=datetime.fromisoformat("2018-03-08T00:43:18+00:00"),
            description="Integrates unit test group",
            language=GroupLanguage.EN,
            name="unittesting",
            organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
            state=GroupState(
                has_machine=True,
                has_squad=True,
                managed=GroupManaged.NOT_MANAGED,
                modified_by="unknown",
                modified_date=datetime.fromisoformat(
                    "2018-03-08T00:43:18+00:00"
                ),
                status=GroupStateStatus.ACTIVE,
                tier=GroupTier.MACHINE,
                type=GroupSubscriptionType.CONTINUOUS,
                tags={"test-tag", "test-groups", "test-updates"},
                comments=None,
                justification=None,
                payment_id=None,
                pending_deletion_date=None,
                service=GroupService.WHITE,
            ),
            agent_token=None,
            business_id="14441323",
            business_name="Testing Company and Sons",
            context="Group context test",
            disambiguation="Disambiguation test",
            files=[
                GroupFile(
                    description="Test",
                    file_name="test.zip",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-03-01T20:21:00+00:00"
                    ),
                ),
                GroupFile(
                    description="shell",
                    file_name="shell.exe",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-04-24T19:56:00+00:00"
                    ),
                ),
                GroupFile(
                    description="shell2",
                    file_name="shell2.exe",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-04-24T19:59:00+00:00"
                    ),
                ),
                GroupFile(
                    description="eerweterterter",
                    file_name="asdasd.py",
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-08-06T19:28:00+00:00"
                    ),
                ),
            ],
            policies=Policies(
                modified_date=datetime.fromisoformat(
                    "2023-02-15T20:07:57+00:00"
                ),
                modified_by="integratesmanager@gmail.com",
                inactivity_period=None,
                max_acceptance_days=None,
                max_acceptance_severity=None,
                max_number_acceptances=None,
                min_acceptance_severity=None,
                min_breaking_severity=None,
                vulnerability_grace_period=None,
            ),
            sprint_duration=2,
            sprint_start_date=datetime.fromisoformat("2022-05-31T00:00:00"),
        ),
    },
    "organizations.domain.Dataloaders.organization_groups": {
        '["ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3"]': [
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates continuous group",
                language=GroupLanguage.EN,
                name="continuoustesting",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.SQUAD,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-tag", "another-tag"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=[
                    GroupFile(
                        description="shell2",
                        file_name="shell2.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:59:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="asdasd",
                        file_name="asdasd.py",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-08-06T19:28:00+00:00"
                        ),
                    ),
                ],
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2019-01-20T22:00:00+00:00"
                ),
                description="oneshot testing",
                language=GroupLanguage.EN,
                name="oneshottest",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-01-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.ONESHOT,
                    type=GroupSubscriptionType.ONESHOT,
                    tags={
                        "test-tag",
                        "test-groups",
                        "another-tag",
                        "test-updates",
                    },
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.BLACK,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2021-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=None,
                    max_acceptance_days=90,
                    max_acceptance_severity=Decimal("3.9"),
                    max_number_acceptances=3,
                    min_acceptance_severity=Decimal("0"),
                    min_breaking_severity=Decimal("3.9"),
                    vulnerability_grace_period=10,
                ),
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2023-03-06T22:00:00+00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2018-03-08T00:43:18+00:00"
                ),
                description="Integrates unit test group",
                language=GroupLanguage.EN,
                name="unittesting",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2018-03-08T00:43:18+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.MACHINE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-tag", "test-groups", "test-updates"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context="Group context test",
                disambiguation="Disambiguation test",
                files=[
                    GroupFile(
                        description="Test",
                        file_name="test.zip",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-03-01T20:21:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="shell",
                        file_name="shell.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:56:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="shell2",
                        file_name="shell2.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:59:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="eerweterterter",
                        file_name="asdasd.py",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-08-06T19:28:00+00:00"
                        ),
                    ),
                ],
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2023-02-15T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=None,
                    max_acceptance_days=None,
                    max_acceptance_severity=None,
                    max_number_acceptances=None,
                    min_acceptance_severity=None,
                    min_breaking_severity=None,
                    vulnerability_grace_period=None,
                ),
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-05-31T00:00:00"
                ),
            ),
        ]
    },
    "organizations.domain.get_all_active_groups": {
        "[]": [
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates continuous group",
                language=GroupLanguage.EN,
                name="continuoustesting",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.SQUAD,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-tag", "another-tag"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=[
                    GroupFile(
                        description="shell2",
                        file_name="shell2.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:59:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="asdasd",
                        file_name="asdasd.py",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-08-06T19:28:00+00:00"
                        ),
                    ),
                ],
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2019-01-20T22:00:00+00:00"
                ),
                description="oneshot testing",
                language=GroupLanguage.EN,
                name="oneshottest",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-01-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.ONESHOT,
                    type=GroupSubscriptionType.ONESHOT,
                    tags={
                        "test-tag",
                        "test-groups",
                        "another-tag",
                        "test-updates",
                    },
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.BLACK,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2021-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=None,
                    max_acceptance_days=90,
                    max_acceptance_severity=Decimal("3.9"),
                    max_number_acceptances=3,
                    min_acceptance_severity=Decimal("0"),
                    min_breaking_severity=Decimal("3.9"),
                    vulnerability_grace_period=10,
                ),
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2023-03-06T22:00:00+00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2018-03-08T00:43:18+00:00"
                ),
                description="Integrates unit test group",
                language=GroupLanguage.EN,
                name="unittesting",
                organization_id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2018-03-08T00:43:18+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.MACHINE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-tag", "test-groups", "test-updates"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context="Group context test",
                disambiguation="Disambiguation test",
                files=[
                    GroupFile(
                        description="Test",
                        file_name="test.zip",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-03-01T20:21:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="shell",
                        file_name="shell.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:56:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="shell2",
                        file_name="shell2.exe",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-24T19:59:00+00:00"
                        ),
                    ),
                    GroupFile(
                        description="eerweterterter",
                        file_name="asdasd.py",
                        modified_by="unittest@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2019-08-06T19:28:00+00:00"
                        ),
                    ),
                ],
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2023-02-15T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=None,
                    max_acceptance_days=None,
                    max_acceptance_severity=None,
                    max_number_acceptances=None,
                    min_acceptance_severity=None,
                    min_breaking_severity=None,
                    vulnerability_grace_period=None,
                ),
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-05-31T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="deleteimamura",
                organization_id="ORG#7376c5fe-4634-4053-9718-e14ecbda1e6b",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.MACHINE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags=None,
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="barranquilla",
                organization_id="ORG#956e9107-fd8d-49bc-b550-5609a7a1f6ac",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.SQUAD,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-newgroups"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="monteria",
                organization_id="ORG#956e9107-fd8d-49bc-b550-5609a7a1f6ac",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.FREE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-newgroups"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="asgard",
                organization_id="ORG#c6cecc0e-bb92-4079-8b6d-c4e815c10bb1",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.OTHER,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-nogroups"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="deletegroup",
                organization_id="ORG#c6cecc0e-bb92-4079-8b6d-c4e815c10bb1",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.OTHER,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags=None,
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=datetime.fromisoformat(
                        "2020-12-22T19:36:29+00:00"
                    ),
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="gotham",
                organization_id="ORG#c6cecc0e-bb92-4079-8b6d-c4e815c10bb1",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.ONESHOT,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-nogroups"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="metropolis",
                organization_id="ORG#c6cecc0e-bb92-4079-8b6d-c4e815c10bb1",
                state=GroupState(
                    has_machine=False,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.MACHINE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"test-nogroups"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="setpendingdeletion",
                organization_id="ORG#c6cecc0e-bb92-4079-8b6d-c4e815c10bb1",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.ONESHOT,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags=None,
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="kurome",
                organization_id="ORG#f2e2777d-a168-4bea-93cd-d79142b294d2",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.OTHER,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags=None,
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="sheele",
                organization_id="ORG#f2e2777d-a168-4bea-93cd-d79142b294d2",
                state=GroupState(
                    has_machine=False,
                    has_squad=False,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.OTHER,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags=None,
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
            Group(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2020-05-20T22:00:00+00:00"
                ),
                description="Integrates group",
                language=GroupLanguage.EN,
                name="lubbock",
                organization_id="ORG#fe80d2d4-ccb7-46d1-8489-67c6360581de",
                state=GroupState(
                    has_machine=True,
                    has_squad=True,
                    managed=GroupManaged.NOT_MANAGED,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    status=GroupStateStatus.ACTIVE,
                    tier=GroupTier.FREE,
                    type=GroupSubscriptionType.CONTINUOUS,
                    tags={"another-tag"},
                    comments=None,
                    justification=None,
                    payment_id=None,
                    pending_deletion_date=None,
                    service=GroupService.WHITE,
                ),
                agent_token=None,
                business_id="14441323",
                business_name="Testing Company and Sons",
                context=None,
                disambiguation=None,
                files=None,
                policies=None,
                sprint_duration=2,
                sprint_start_date=datetime.fromisoformat(
                    "2022-06-06T00:00:00"
                ),
            ),
        ]
    },
    "organizations.domain.get_group_names": {
        "[]": [
            [],
            ["oneshottest", "continuoustesting", "unittesting"],
            ["deleteimamura"],
            ["barranquilla", "monteria"],
            [],
            [
                "metropolis",
                "deletegroup",
                "gotham",
                "asgard",
                "setpendingdeletion",
            ],
            [],
            [],
            ["kurome", "sheele"],
            ["lubbock"],
            [],
        ]
    },
    "organizations.domain.orgs_model.iterate_organizations": {
        "[]": [
            Organization(
                created_by="unknown",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#33c08ebd-2068-47e7-9673-e1aa03dc9448",
                name="kiba",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=90,
                    max_acceptance_days=None,
                    max_acceptance_severity=Decimal("10.0"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0.0"),
                    vulnerability_grace_period=None,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2018-02-08T00:43:18+00:00"
                ),
                id="ORG#38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                name="okada",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=90,
                    max_acceptance_days=60,
                    max_acceptance_severity=Decimal("10.0"),
                    max_number_acceptances=2,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0"),
                    vulnerability_grace_period=0,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2018-02-08T00:43:18+00:00"
                    ),
                    pending_deletion_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                ),
                country="Colombia",
                payment_methods=[
                    OrganizationPaymentMethods(
                        id="38eb8f25-7945-4173-ab6e-0af4ad8b7ef3",
                        business_name="Fluid",
                        email="test@fluidattacks.com",
                        country="Colombia",
                        state="Antioquia",
                        city="Medellín",
                        documents=OrganizationDocuments(rut=None, tax_id=None),
                    ),
                    OrganizationPaymentMethods(
                        id="4722b0b7-cfeb-4898-8308-185dfc2523bc",
                        business_name="Testing Company and Sons",
                        email="test@fluidattacks.com",
                        country="Colombia",
                        state="Antioquia",
                        city="Medellín",
                        documents=OrganizationDocuments(rut=None, tax_id=None),
                    ),
                ],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#7376c5fe-4634-4053-9718-e14ecbda1e6b",
                name="imamura",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=None,
                    max_acceptance_days=30,
                    max_acceptance_severity=Decimal("8.5"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("1"),
                    min_breaking_severity=Decimal("0"),
                    vulnerability_grace_period=0,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#956e9107-fd8d-49bc-b550-5609a7a1f6ac",
                name="kamiya",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=90,
                    max_acceptance_days=30,
                    max_acceptance_severity=Decimal("8.5"),
                    max_number_acceptances=3,
                    min_acceptance_severity=Decimal("1"),
                    min_breaking_severity=Decimal("0"),
                    vulnerability_grace_period=0,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#c2ee2d15-04ab-4f39-9795-fbe30cdeee86",
                name="bulat",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=90,
                    max_acceptance_days=None,
                    max_acceptance_severity=Decimal("6.9"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("3.4"),
                    min_breaking_severity=Decimal("0.0"),
                    vulnerability_grace_period=None,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#c6cecc0e-bb92-4079-8b6d-c4e815c10bb1",
                name="makimachi",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=90,
                    max_acceptance_days=90,
                    max_acceptance_severity=Decimal("7"),
                    max_number_acceptances=4,
                    min_acceptance_severity=Decimal("3"),
                    min_breaking_severity=Decimal("0"),
                    vulnerability_grace_period=0,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#d32674a9-9838-4337-b222-68c88bf54647",
                name="makoto",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=90,
                    max_acceptance_days=None,
                    max_acceptance_severity=Decimal("10.0"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0.0"),
                    vulnerability_grace_period=None,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="integratesmanager@gmail.com",
                created_date=datetime.fromisoformat(
                    "2019-11-30T15:00:00+00:00"
                ),
                id="ORG#ed6f051c-2572-420f-bc11-476c4e71b4ee",
                name="ikari",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=90,
                    max_acceptance_days=None,
                    max_acceptance_severity=Decimal("10.0"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0.0"),
                    vulnerability_grace_period=None,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.DELETED,
                    modified_by="integratesmanager@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2019-11-30T15:00:00+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#f2e2777d-a168-4bea-93cd-d79142b294d2",
                name="hajime",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="integratesmanager@gmail.com",
                    inactivity_period=90,
                    max_acceptance_days=60,
                    max_acceptance_severity=Decimal("7"),
                    max_number_acceptances=1,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0"),
                    vulnerability_grace_period=0,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#fe80d2d4-ccb7-46d1-8489-67c6360581de",
                name="tatsumi",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=90,
                    max_acceptance_days=None,
                    max_acceptance_severity=Decimal("10.0"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0.0"),
                    vulnerability_grace_period=None,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
            Organization(
                created_by="unknown@unknown.com",
                created_date=datetime.fromisoformat(
                    "2019-11-22T20:07:57+00:00"
                ),
                id="ORG#ffddc7a3-7f05-4fc7-b65d-7defffa883c2",
                name="himura",
                policies=Policies(
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    modified_by="unknown",
                    inactivity_period=90,
                    max_acceptance_days=None,
                    max_acceptance_severity=Decimal("10.0"),
                    max_number_acceptances=None,
                    min_acceptance_severity=Decimal("0.0"),
                    min_breaking_severity=Decimal("0.0"),
                    vulnerability_grace_period=None,
                ),
                state=OrganizationState(
                    status=OrganizationStateStatus.ACTIVE,
                    modified_by="unknown",
                    modified_date=datetime.fromisoformat(
                        "2019-11-22T20:07:57+00:00"
                    ),
                    pending_deletion_date=None,
                ),
                country="Colombia",
                payment_methods=[],
                billing_customer=None,
                vulnerabilities_url=None,
            ),
        ]
    },
}


@pytest.fixture
def mock_data_for_module(
    *,
    resolve_mock_data: Callable,
) -> Any:
    def _mock_data_for_module(
        mock_path: str, mock_args: list[Any], module_at_test: str
    ) -> Callable[[str, list[Any], str], Any]:
        return resolve_mock_data(
            mock_data=MOCKED_DATA,
            mock_path=mock_path,
            mock_args=mock_args,
            module_at_test=module_at_test,
        )

    return _mock_data_for_module
