---
codecov:
  notify:
    require_ci_to_pass: false
coverage:
  ignore:
    - coverage_results.txt
  status:
    project:
      default:
        # The build fails if total project coverage drops by more than 6%
        # target: auto
        # threshold: 0%
        target: 95%
    changes: false
    patch: false
flags:
  integrates:
    paths: [integrates/]
  skims:
    paths: [skims/]
