from lib.root import (
    f001,
    f004,
    f007,
    f008,
    f009,
    f011,
    f012,
    f015,
    f016,
    f017,
    f021,
    f022,
    f024,
    f031,
    f034,
    f035,
    f042,
    f044,
    f052,
    f056,
    f059,
    f060,
    f063,
    f066,
    f070,
    f073,
    f083,
    f085,
    f089,
    f091,
    f096,
    f097,
    f098,
    f099,
    f100,
    f107,
    f109,
    f112,
    f127,
    f128,
    f130,
    f134,
    f135,
    f143,
    f148,
    f152,
    f153,
    f157,
    f160,
    f164,
    f165,
    f169,
    f177,
    f183,
    f188,
    f203,
    f211,
    f234,
    f236,
    f237,
    f239,
    f246,
    f250,
    f256,
    f257,
    f258,
    f259,
    f267,
    f280,
    f281,
    f297,
    f300,
    f309,
    f313,
    f320,
    f325,
    f332,
    f333,
    f335,
    f338,
    f343,
    f344,
    f350,
    f353,
    f354,
    f358,
    f363,
    f366,
    f368,
    f371,
    f372,
    f379,
    f380,
    f381,
    f393,
    f394,
    f396,
    f400,
    f401,
    f402,
    f406,
    f407,
    f408,
    f412,
    f413,
    f414,
    f416,
    f423,
    f426,
)
from model.core import (
    FindingEnum,
)
from model.graph import (
    GraphShardMetadataLanguage,
    QueryNodes,
)

QUERIES: dict[
    GraphShardMetadataLanguage,
    dict[str, tuple[tuple[FindingEnum, QueryNodes], ...]],
] = {
    GraphShardMetadataLanguage.CSHARP: {
        "Attribute": (
            (FindingEnum.F134, f134.c_sharp_insecure_cors_origin_attribute),
        ),
        "MemberAccess": (
            (FindingEnum.F001, f001.c_sharp_sql_user_params),
            (FindingEnum.F008, f008.c_sharp_unsafe_status_write),
            (FindingEnum.F016, f016.c_sharp_weak_protocol),
            (FindingEnum.F016, f016.c_sharp_service_point_manager_disabled),
            (FindingEnum.F017, f017.c_sharp_verify_decoder),
            (FindingEnum.F017, f017.c_sharp_jwt_signed_member_access),
            (FindingEnum.F035, f035.c_sharp_weak_credential_policy),
            (FindingEnum.F035, f035.c_sharp_no_password),
            (FindingEnum.F052, f052.c_sharp_disabled_strong_crypto),
            (FindingEnum.F052, f052.c_sharp_insecure_cipher_member_access),
            (FindingEnum.F052, f052.c_sharp_rsa_secure_mode),
            (FindingEnum.F052, f052.c_sharp_insecure_hash_member_access),
            (FindingEnum.F060, f060.c_sharp_insecure_certificate_validation),
            (FindingEnum.F063, f063.c_sharp_open_redirect),
            (FindingEnum.F066, f066.c_sharp_has_console_functions),
            (FindingEnum.F091, f091.c_sharp_insecure_logging),
            (FindingEnum.F096, f096.c_sharp_type_name_handling),
            (FindingEnum.F134, f134.c_sharp_insecure_cors),
            (FindingEnum.F211, f211.c_sharp_vuln_regular_expression),
            (FindingEnum.F211, f211.c_sharp_regex_injection),
            (FindingEnum.F320, f320.c_sharp_ldap_connections_authenticated),
            (FindingEnum.F358, f358.c_sharp_cert_validation_disabled),
        ),
        "MethodDeclaration": (
            (FindingEnum.F366, f366.c_sharp_conflicting_annotations),
        ),
        "MethodInvocation": (
            (FindingEnum.F001, f001.c_sharp_sql_injection_execution),
            (FindingEnum.F004, f004.c_sharp_remote_command_execution),
            (FindingEnum.F008, f008.c_sharp_unsafe_addheader_write),
            (FindingEnum.F011, f011.c_sharp_schema_by_url),
            (FindingEnum.F015, f015.c_sharp_insecure_authentication),
            (FindingEnum.F016, f016.c_sharp_insecure_shared_access_protocol),
            (FindingEnum.F021, f021.c_sharp_path_injection),
            (FindingEnum.F021, f021.c_sharp_xpath_injection_evaluate),
            (
                FindingEnum.F052,
                f052.c_sharp_obsolete_key_derivation_method_invocation,
            ),
            (FindingEnum.F063, f063.c_sharp_unsafe_path_traversal),
            (FindingEnum.F098, f098.c_sharp_path_injection),
            (FindingEnum.F100, f100.c_sharp_insec_create),
            (FindingEnum.F107, f107.c_sharp_ldap_injection),
            (FindingEnum.F169, f169.c_sharp_plain_text_keys),
            (FindingEnum.F134, f134.c_sharp_insecure_cors_origin_method),
            (FindingEnum.F153, f153.c_sharp_accepts_any_mime_type),
            (FindingEnum.F160, f160.c_sharp_file_create_temp_file),
            (FindingEnum.F239, f239.c_sharp_info_leak_errors),
            (FindingEnum.F413, f413.c_sharp_insecure_assembly_load),
            (FindingEnum.F416, f416.c_sharp_xaml_injection),
        ),
        "ObjectCreation": (
            (FindingEnum.F001, f001.c_sharp_sql_injection_object),
            (FindingEnum.F011, f011.c_sharp_xsl_transform_object),
            (FindingEnum.F016, f016.c_sharp_httpclient_no_revocation_list),
            (FindingEnum.F017, f017.c_sharp_jwt_signed_object_creation),
            (FindingEnum.F042, f042.c_sharp_insecurely_generated_cookies),
            (FindingEnum.F052, f052.c_sharp_insecure_keys),
            (FindingEnum.F052, f052.c_sharp_insecure_cipher_object_creation),
            (FindingEnum.F052, f052.c_sharp_insecure_hash_object_creation),
            (FindingEnum.F052, f052.c_sharp_managed_secure_mode),
            (
                FindingEnum.F052,
                f052.c_sharp_obsolete_key_derivation_object_creation,
            ),
            (FindingEnum.F096, f096.c_sharp_check_xml_serializer),
            (FindingEnum.F096, f096.c_sharp_insecure_deserialization),
            (FindingEnum.F096, f096.c_sharp_js_deserialization),
            (FindingEnum.F148, f148.c_sharp_insecure_channel),
            (FindingEnum.F414, f414.c_sharp_disabled_http_header_check),
            (FindingEnum.F320, f320.c_sharp_ldap_connections_directory),
            (FindingEnum.F338, f338.c_sharp_check_hashes_salt),
        ),
    },
    GraphShardMetadataLanguage.DART: {
        "MethodInvocation": (
            (FindingEnum.F091, f091.dart_insecure_logging),
            (FindingEnum.F338, f338.dart_salting_is_harcoded),
        ),
        "SymbolLookup": ((FindingEnum.F237, f237.dart_has_print_statements),),
    },
    GraphShardMetadataLanguage.GO: {
        "MethodInvocation": (
            (FindingEnum.F052, f052.go_insecure_cipher),
            (FindingEnum.F127, f127.go_insecure_query_float),
            (FindingEnum.F153, f153.go_accepts_any_mime_type),
            (FindingEnum.F338, f338.go_salting_is_harcoded),
        ),
        "MemberAccess": ((FindingEnum.F052, f052.go_insecure_hash),),
    },
    GraphShardMetadataLanguage.HCL: {
        "Object": (
            (
                FindingEnum.F015,
                f015.tfm_azure_linux_vm_insecure_authentication,
            ),
            (
                FindingEnum.F015,
                f015.tfm_azure_virtual_machine_insecure_authentication,
            ),
            (FindingEnum.F016, f016.tfm_aws_elb_without_sslpolicy),
            (
                FindingEnum.F016,
                f016.tfm_aws_serves_content_over_insecure_protocols,
            ),
            (FindingEnum.F016, f016.tfm_azure_api_insecure_protocols),
            (
                FindingEnum.F016,
                f016.tfm_azure_serves_content_over_insecure_protocols,
            ),
            (FindingEnum.F024, f024.tfm_aws_allows_anyone_to_admin_ports),
            (FindingEnum.F024, f024.tfm_aws_ec2_allows_all_outbound_traffic),
            (FindingEnum.F024, f024.tfm_aws_ec2_cfn_unrestricted_ip_protocols),
            (FindingEnum.F024, f024.tfm_aws_ec2_unrestricted_cidrs),
            (FindingEnum.F024, f024.tfm_ec2_has_open_all_ports_to_the_public),
            (
                FindingEnum.F024,
                f024.tfm_ec2_has_security_groups_ip_ranges_in_rfc1918,
            ),
            (FindingEnum.F024, f024.tfm_ec2_has_unrestricted_dns_access),
            (FindingEnum.F024, f024.tfm_ec2_has_unrestricted_ftp_access),
            (FindingEnum.F024, f024.tfm_ec2_has_unrestricted_ports),
            (FindingEnum.F024, f024.tfm_ec2_instances_without_profile),
            (FindingEnum.F031, f031.tfm_admin_policy_attached),
            (FindingEnum.F031, f031.tfm_bucket_policy_allows_public_access),
            (FindingEnum.F031, f031.tfm_iam_excessive_privileges),
            (FindingEnum.F031, f031.tfm_iam_excessive_role_policy),
            (FindingEnum.F031, f031.tfm_iam_has_full_access_to_ssm),
            (FindingEnum.F031, f031.tfm_iam_user_missing_role_based_security),
            (FindingEnum.F031, f031.tfm_negative_statement),
            (FindingEnum.F044, f044.tfm_has_danger_https_methods_enabled),
            (FindingEnum.F044, f044.tfm_api_all_http_methods_enabled),
            (FindingEnum.F070, f070.tfm_elb2_uses_insecure_security_policy),
            (FindingEnum.F073, f073.tfm_rds_publicly_accessible),
            (
                FindingEnum.F099,
                f099.tfm_bucket_server_side_encryption_disabled,
            ),
            (FindingEnum.F109, f109.tfm_rds_not_inside_subnet),
            (FindingEnum.F134, f134.tfm_wildcard_in_allowed_origins),
            (FindingEnum.F157, f157.tfm_aws_acl_broad_network_access),
            (FindingEnum.F157, f157.tfm_azure_kv_danger_bypass),
            (FindingEnum.F157, f157.tfm_azure_kv_default_network_access),
            (FindingEnum.F157, f157.tfm_azure_sa_default_network_access),
            (
                FindingEnum.F157,
                f157.tfm_azure_unrestricted_access_network_segments,
            ),
            (FindingEnum.F165, f165.tfm_iam_allow_not_principal_trust_policy),
            (FindingEnum.F165, f165.tfm_iam_allow_not_actions_trust_policy),
            (FindingEnum.F165, f165.tfm_iam_allow_not_action_perms_policies),
            (FindingEnum.F165, f165.tfm_iam_allow_not_resource_perms_policies),
            (FindingEnum.F165, f165.tfm_iam_is_policy_applying_to_users),
            (FindingEnum.F177, f177.tfm_ec2_use_default_security_group),
            (FindingEnum.F203, f203.tfm_public_buckets),
            (FindingEnum.F246, f246.tfm_rds_has_unencrypted_storage),
            (FindingEnum.F250, f250.tfm_ebs_unencrypted_by_default),
            (FindingEnum.F250, f250.tfm_ebs_unencrypted_volumes),
            (FindingEnum.F250, f250.tfm_ec2_unencrypted_ebs_block),
            (FindingEnum.F256, f256.tfm_rds_has_not_automated_backups),
            (FindingEnum.F256, f256.tfm_rds_no_deletion_protection),
            (FindingEnum.F257, f257.tfm_ec2_has_not_termination_protection),
            (FindingEnum.F258, f258.tfm_elb2_has_not_deletion_protection),
            (FindingEnum.F259, f259.tfm_dynamo_has_not_deletion_protection),
            (FindingEnum.F259, f259.tfm_db_no_point_in_time_recovery),
            (FindingEnum.F281, f281.tfm_bucket_policy_has_secure_transport),
            (FindingEnum.F300, f300.tfm_azure_app_authentication_off),
            (FindingEnum.F300, f300.tfm_azure_as_client_certificates_enabled),
            (FindingEnum.F325, f325.tfm_iam_has_wildcard_on_policy),
            (FindingEnum.F325, f325.tfm_iam_has_wildcard_on_trust_policy),
            (FindingEnum.F325, f325.tfm_iam_permissive_policy),
            (FindingEnum.F325, f325.tfm_kms_master_keys_exposed_to_everyone),
            (FindingEnum.F332, f332.tfm_secgroup_uses_insecure_protocol),
            (FindingEnum.F333, f333.tfm_ec2_associate_public_ip_address),
            (FindingEnum.F333, f333.tfm_ec2_has_not_an_iam_instance_profile),
            (FindingEnum.F333, f333.tfm_ec2_has_terminate_shutdown_behavior),
            (FindingEnum.F335, f335.tfm_s3_bucket_versioning_disabled),
            (FindingEnum.F363, f363.tfm_insecure_generate_secret_string),
            (FindingEnum.F372, f372.tfm_azure_kv_only_accessible_over_https),
            (FindingEnum.F372, f372.tfm_azure_sa_insecure_transfer),
            (FindingEnum.F372, f372.tfm_elb2_uses_insecure_http_protocol),
            (FindingEnum.F372, f372.tfm_serves_content_over_http),
            (FindingEnum.F381, f381.tfm_check_required_version),
            (FindingEnum.F394, f394.tfm_trail_log_files_not_validated),
            (
                FindingEnum.F396,
                f396.tfm_kms_key_is_key_rotation_absent_or_disabled,
            ),
            (FindingEnum.F400, f400.tfm_distribution_has_logging_disabled),
            (FindingEnum.F400, f400.tfm_ec2_monitoring_disabled),
            (FindingEnum.F400, f400.tfm_load_balancers_logging_disabled),
            (FindingEnum.F400, f400.tfm_trails_not_multiregion),
            (FindingEnum.F401, f401.tfm_azure_kv_secret_no_expiration_date),
            (FindingEnum.F402, f402.tfm_azure_app_service_logging_disabled),
            (FindingEnum.F402, f402.tfm_azure_sql_server_audit_log_retention),
            (FindingEnum.F402, f402.tfm_azure_storage_logging_disabled),
            (FindingEnum.F406, f406.tfm_aws_efs_unencrypted),
            (FindingEnum.F407, f407.tfm_aws_ebs_volumes_unencrypted),
            (FindingEnum.F408, f408.tfm_api_gateway_access_logging_disabled),
            (FindingEnum.F412, f412.tfm_azure_key_vault_not_recoverable),
        ),
    },
    GraphShardMetadataLanguage.JAVA: {
        "Annotation": ((FindingEnum.F012, f012.java_jpa_like),),
        "CatchClause": ((FindingEnum.F234, f234.java_info_leak_stacktrace),),
        "MethodDeclaration": (
            (FindingEnum.F134, f134.java_insecure_cors_origin_modifier),
        ),
        "MethodInvocation": (
            (FindingEnum.F004, f004.java_remote_command_1),
            (FindingEnum.F004, f004.java_remote_command_2),
            (FindingEnum.F007, f007.java_csrf_protections_disabled),
            (FindingEnum.F008, f008.java_unsafe_xss_content),
            (FindingEnum.F015, f015.java_basic_authentication),
            (FindingEnum.F015, f015.java_insecure_authentication),
            (FindingEnum.F021, f021.java_unsafe_xpath_injection),
            (FindingEnum.F034, f034.java_weak_random),
            (FindingEnum.F052, f052.java_insecure_cipher),
            (FindingEnum.F052, f052.java_insecure_hash),
            (FindingEnum.F052, f052.java_insecure_cipher_ssl),
            (FindingEnum.F052, f052.java_insecure_cipher_jmqi),
            (FindingEnum.F052, f052.java_insecure_connection),
            (FindingEnum.F052, f052.java_insecure_hash_argument),
            (FindingEnum.F059, f059.java_sensitive_log_info),
            (FindingEnum.F063, f063.java_zip_slip_injection),
            (FindingEnum.F083, f083.java_insecure_parser),
            (FindingEnum.F089, f089.java_trust_boundary_violation),
            (FindingEnum.F091, f091.java_insecure_logging),
            (FindingEnum.F107, f107.java_ldap_injection),
            (FindingEnum.F112, f112.java_sql_injection),
            (FindingEnum.F128, f128.java_cookie_http_only),
            (FindingEnum.F130, f130.java_cookie_set_secure),
            (FindingEnum.F134, f134.java_insecure_cors_origin),
            (FindingEnum.F153, f153.java_accepts_any_mime_type_chain),
            (FindingEnum.F153, f153.java_http_accepts_any_mime_type),
            (FindingEnum.F160, f160.java_file_create_temp_file),
            (FindingEnum.F211, f211.java_vuln_regular_expression),
            (FindingEnum.F237, f237.java_has_print_statements),
            (FindingEnum.F350, f350.java_use_insecure_trust_manager),
            (FindingEnum.F368, f368.java_host_key_checking),
            (FindingEnum.F423, f423.java_uses_exit_method),
        ),
        "ObjectCreation": (
            (FindingEnum.F052, f052.java_insecure_pass),
            (FindingEnum.F052, f052.java_insecure_key_ec),
            (FindingEnum.F052, f052.java_insecure_key_rsa),
            (FindingEnum.F052, f052.java_insecure_key_secret),
            (FindingEnum.F063, f063.java_unsafe_path_traversal),
            (FindingEnum.F153, f153.java_http_accepts_any_mime_type_obj),
            (FindingEnum.F338, f338.java_salting_is_hardcoded),
            (FindingEnum.F354, f354.java_insecure_file_upload_size),
        ),
    },
    GraphShardMetadataLanguage.JAVASCRIPT: {
        "Assignment": ((FindingEnum.F344, f344.js_local_storage_sens_data),),
        "Debugger": ((FindingEnum.F183, f183.js_debugging_enabled),),
        "ElementAccess": (
            (FindingEnum.F153, f153.js_accepts_any_mime_default),
        ),
        "Import": ((FindingEnum.F379, f379.js_import_is_never_used),),
        "JsxElement": ((FindingEnum.F371, f371.js_dangerously_set_innerhtml),),
        "MemberAccess": (
            (FindingEnum.F309, f309.js_insecure_jwt_token),
            (FindingEnum.F338, f338.js_salting_is_harcoded),
            (FindingEnum.F353, f353.js_decode_insecure_jwt_token),
            (FindingEnum.F371, f371.js_bypass_security_trust_url),
            (FindingEnum.F371, f371.js_uses_innerhtml),
        ),
        "MethodInvocation": (
            (FindingEnum.F004, f004.js_remote_command_execution),
            (FindingEnum.F008, f008.js_unsafe_xss_content),
            (FindingEnum.F009, f009.javascript_crypto_js_credentials),
            (FindingEnum.F021, f021.js_dynamic_xpath),
            (FindingEnum.F083, f083.js_xml_parser),
            (FindingEnum.F085, f085.js_client_storage),
            (FindingEnum.F091, f091.js_insecure_logging),
            (FindingEnum.F097, f097.js_has_reverse_tabnabbing),
            (FindingEnum.F042, f042.js_insecurely_generated_cookies),
            (FindingEnum.F052, f052.javascript_insecure_create_cipher),
            (FindingEnum.F052, f052.javascript_insecure_ec_keypair),
            (FindingEnum.F052, f052.javascript_insecure_ecdh_key),
            (FindingEnum.F052, f052.javascript_insecure_encrypt),
            (FindingEnum.F052, f052.javascript_insecure_hash),
            (FindingEnum.F052, f052.javascript_insecure_hash_library),
            (FindingEnum.F052, f052.javascript_insecure_rsa_keypair),
            (FindingEnum.F052, f052.javascript_jwt_insec_sign_algo_async),
            (FindingEnum.F052, f052.javascript_jwt_insec_sign_algorithm),
            (FindingEnum.F060, f060.js_unsafe_origin),
            (FindingEnum.F063, f063.js_insecure_path_traversal),
            (FindingEnum.F063, f063.js_zip_slip_injection),
            (FindingEnum.F066, f066.javascript_uses_console_log),
            (FindingEnum.F112, f112.js_sql_injection),
            (FindingEnum.F128, f128.js_insecure_cookies),
            (FindingEnum.F143, f143.js_uses_eval),
            (FindingEnum.F153, f153.js_accepts_any_mime_method),
            (FindingEnum.F188, f188.js_lack_of_validation_dom_window),
            (FindingEnum.F034, f034.javascript_weak_random),
            (FindingEnum.F211, f211.js_regex_injection),
            (FindingEnum.F280, f280.js_non_secure_construction),
            (FindingEnum.F297, f297.js_sql_injection),
            (FindingEnum.F344, f344.js_local_storage_sensitive_data),
        ),
        "ObjectCreation": (
            (FindingEnum.F135, f135.js_insecure_http_headers),
            (FindingEnum.F143, f143.js_uses_eval),
            (FindingEnum.F152, f152.js_insecure_header_xframe_options),
            (FindingEnum.F343, f343.js_insecure_compression),
        ),
    },
    GraphShardMetadataLanguage.JSON: {
        "Object": (
            (FindingEnum.F016, f016.cfn_elb_without_sslpolicy),
            (
                FindingEnum.F016,
                f016.cfn_serves_content_over_insecure_protocols,
            ),
            (FindingEnum.F024, f024.cfn_allows_anyone_to_admin_ports),
            (FindingEnum.F024, f024.cfn_ec2_has_open_all_ports_to_the_public),
            (
                FindingEnum.F024,
                f024.cfn_ec2_has_security_groups_ip_ranges_in_rfc1918,
            ),
            (FindingEnum.F024, f024.cfn_ec2_has_unrestricted_dns_access),
            (FindingEnum.F024, f024.cfn_ec2_has_unrestricted_ftp_access),
            (FindingEnum.F024, f024.cfn_groups_without_egress),
            (FindingEnum.F024, f024.cfn_instances_without_profile),
            (FindingEnum.F024, f024.cfn_unrestricted_cidrs),
            (FindingEnum.F024, f024.cfn_unrestricted_ip_protocols),
            (FindingEnum.F024, f024.cfn_ec2_has_unrestricted_ports),
            (FindingEnum.F031, f031.cfn_bucket_policy_allows_public_access),
            (FindingEnum.F031, f031.cfn_admin_policy_attached),
            (FindingEnum.F031, f031.cfn_iam_excessive_role_policy),
            (FindingEnum.F031, f031.cfn_iam_has_full_access_to_ssm),
            (FindingEnum.F031, f031.cfn_iam_user_missing_role_based_security),
            (FindingEnum.F031, f031.cfn_negative_statement),
            (FindingEnum.F044, f044.cfn_has_danger_https_methods_enabled),
            (FindingEnum.F044, f044.cfn_api_all_http_methods_enabled),
            (FindingEnum.F070, f070.cfn_elb2_uses_insecure_security_policy),
            (FindingEnum.F073, f073.cfn_rds_is_publicly_accessible),
            (
                FindingEnum.F099,
                f099.cfn_bucket_server_side_encryption_disabled,
            ),
            (FindingEnum.F109, f109.cfn_rds_is_not_inside_a_db_subnet_group),
            (FindingEnum.F165, f165.cfn_iam_allow_not_action_perms_policies),
            (FindingEnum.F165, f165.cfn_iam_allow_not_actions_trust_policy),
            (FindingEnum.F165, f165.cfn_iam_allow_not_principal_trust_policy),
            (FindingEnum.F165, f165.cfn_iam_allow_not_resource_perms_policies),
            (FindingEnum.F165, f165.cfn_iam_is_policy_applying_to_users),
            (FindingEnum.F177, f177.cfn_ec2_use_default_security_group),
            (FindingEnum.F203, f203.cfn_public_buckets),
            (FindingEnum.F246, f246.cfn_rds_has_unencrypted_storage),
            (FindingEnum.F250, f250.cfn_ec2_has_unencrypted_volumes),
            (FindingEnum.F250, f250.cfn_ec2_unencrypted_ebs_block),
            (FindingEnum.F246, f246.cfn_rds_has_unencrypted_storage),
            (FindingEnum.F250, f250.cfn_ec2_has_unencrypted_volumes),
            (FindingEnum.F250, f250.cfn_ec2_unencrypted_ebs_block),
            (FindingEnum.F256, f256.cfn_rds_has_not_automated_backups),
            (FindingEnum.F256, f256.cfn_rds_has_not_termination_protection),
            (FindingEnum.F257, f257.cfn_ec2_has_not_termination_protection),
            (FindingEnum.F258, f258.cfn_elb2_has_not_deletion_protection),
            (FindingEnum.F259, f259.cfn_dynamo_has_not_deletion_protection),
            (FindingEnum.F259, f259.cfn_has_not_point_in_time_recovery),
            (FindingEnum.F267, f267.k8s_allow_privilege_escalation_enabled),
            (FindingEnum.F267, f267.k8s_check_add_capability),
            (FindingEnum.F267, f267.k8s_check_drop_capability),
            (FindingEnum.F267, f267.k8s_check_if_capability_exists),
            (FindingEnum.F267, f267.k8s_check_if_sys_admin_exists),
            (FindingEnum.F267, f267.k8s_check_privileged_used),
            (FindingEnum.F267, f267.k8s_check_run_as_user),
            (FindingEnum.F267, f267.k8s_check_seccomp_profile),
            (FindingEnum.F267, f267.k8s_container_without_securitycontext),
            (FindingEnum.F267, f267.k8s_check_host_pid),
            (FindingEnum.F267, f267.k8s_root_container),
            (FindingEnum.F267, f267.k8s_root_filesystem_read_only),
            (FindingEnum.F281, f281.cfn_bucket_policy_has_secure_transport),
            (FindingEnum.F313, f313.cfn_insecure_certificate),
            (FindingEnum.F325, f325.cfn_iam_has_wildcard_action_policy),
            (FindingEnum.F325, f325.cfn_iam_has_wildcard_action_trust_policy),
            (FindingEnum.F325, f325.cfn_iam_has_wildcard_resource_policy),
            (
                FindingEnum.F325,
                f325.cfn_iam_has_wildcard_resource_trust_policy,
            ),
            (FindingEnum.F325, f325.cfn_iam_permissive_policy),
            (FindingEnum.F325, f325.cfn_kms_master_keys_exposed_to_everyone),
            (FindingEnum.F325, f325.json_principal_wildcard),
            (FindingEnum.F332, f332.cfn_secgroup_uses_insecure_protocol),
            (FindingEnum.F332, f332.k8s_insecure_port),
            (FindingEnum.F333, f333.cfn_ec2_associate_public_ip_address),
            (FindingEnum.F333, f333.cfn_ec2_has_not_an_iam_instance_profile),
            (FindingEnum.F333, f333.cfn_ec2_has_terminate_shutdown_behavior),
            (FindingEnum.F335, f335.cfn_s3_bucket_versioning_disabled),
            (FindingEnum.F363, f363.cfn_insecure_generate_secret_string),
            (FindingEnum.F372, f372.cfn_serves_content_over_http),
            (FindingEnum.F372, f372.cfn_elb2_uses_insecure_http_protocol),
            (FindingEnum.F394, f394.cfn_log_files_not_validated),
            (
                FindingEnum.F396,
                f396.cfn_kms_key_is_key_rotation_absent_or_disabled,
            ),
            (FindingEnum.F400, f400.cfn_bucket_has_logging_conf_disabled),
            (FindingEnum.F400, f400.cfn_cf_distribution_has_logging_disabled),
            (FindingEnum.F400, f400.cfn_ec2_monitoring_disabled),
            (FindingEnum.F400, f400.cfn_elb2_has_access_logs_s3_disabled),
            (FindingEnum.F400, f400.cfn_elb_has_access_logging_disabled),
            (FindingEnum.F400, f400.cfn_trails_not_multiregion),
            (FindingEnum.F406, f406.cfn_aws_efs_unencrypted),
            (FindingEnum.F407, f407.cfn_aws_ebs_volumes_unencrypted),
            (FindingEnum.F408, f408.cfn_api_gateway_access_logging_disabled),
            (FindingEnum.F426, f426.k8s_image_has_digest),
        ),
        "Pair": (
            (FindingEnum.F009, f009.json_sensitive_info),
            (FindingEnum.F009, f009.json_sensitive_info_in_dotnet),
            (FindingEnum.F009, f009.json_sensitive_key),
            (FindingEnum.F022, f022.cfn_server_port_insecure_channel),
            (FindingEnum.F056, f056.json_anon_connection_config),
            (FindingEnum.F060, f060.json_allowed_hosts),
            (FindingEnum.F060, f060.json_disable_host_check),
            (FindingEnum.F134, f134.cfn_cors_true),
            (FindingEnum.F134, f134.cfn_wildcard_in_allowed_origins),
            (FindingEnum.F164, f164.json_ssl_port_missing),
            (FindingEnum.F236, f236.tsconfig_sourcemap_enabled),
            (FindingEnum.F313, f313.cfn_insecure_certificate),
            (FindingEnum.F332, f332.cfn_server_disabled_ssl),
            (FindingEnum.F332, f332.k8s_insecure_http_channel),
            (FindingEnum.F372, f372.json_https_flag_missing),
        ),
    },
    GraphShardMetadataLanguage.KOTLIN: {
        "MemberAccess": (
            (FindingEnum.F004, f004.kt_remote_command_exec),
            (FindingEnum.F083, f083.kt_insecure_parser),
            (FindingEnum.F107, f107.kt_anonymous_ldap),
            (FindingEnum.F052, f052.kotlin_insecure_certification),
            (FindingEnum.F052, f052.kt_insecure_key_pair_generator),
            (FindingEnum.F052, f052.kt_insecure_key_generator),
        ),
        "MethodInvocation": (
            (FindingEnum.F016, f016.kt_default_http_client_deprecated),
            (FindingEnum.F052, f052.kotlin_insecure_hash),
            (FindingEnum.F052, f052.kotlin_insecure_hash_instance),
            (FindingEnum.F052, f052.kotlin_insecure_cipher),
            (FindingEnum.F052, f052.kotlin_insecure_cipher_ssl),
            (FindingEnum.F052, f052.kotlin_insecure_cipher_http),
            (FindingEnum.F052, f052.kotlin_insecure_key_rsa),
            (FindingEnum.F052, f052.kt_insecure_parameter_spec),
            (FindingEnum.F052, f052.kt_insecure_encription_key),
            (FindingEnum.F052, f052.kotlin_insecure_key_ec),
            (FindingEnum.F052, f052.kotlin_insecure_init_vector),
            (FindingEnum.F052, f052.kotlin_insecure_hostname_ver),
            (FindingEnum.F128, f128.kt_cookie_http_only),
            (FindingEnum.F130, f130.kt_cookie_set_secure),
            (FindingEnum.F153, f153.kt_accepts_any_mime_type),
            (FindingEnum.F034, f034.kotlin_weak_random),
            (FindingEnum.F211, f211.kt_vuln_regular_expression),
            (FindingEnum.F338, f338.kt_salting_is_harcoded),
            (FindingEnum.F332, f332.kt_unencrypted_channel),
        ),
    },
    GraphShardMetadataLanguage.PYTHON: {
        "Class": (
            (FindingEnum.F011, f011.conan_conanfile_py),
            (FindingEnum.F393, f393.conan_conanfile_py_dev),
        ),
        "ElementAccess": ((FindingEnum.F280, f280.python_xml_parser),),
        "MemberAccess": (
            (FindingEnum.F107, f107.python_ldap_injection),
            (FindingEnum.F160, f160.python_unsafe_temp_file),
            (FindingEnum.F211, f211.python_regex_dos),
            (FindingEnum.F280, f280.python_xml_parser),
            (FindingEnum.F313, f313.python_unsafe_certificate_validation),
            (FindingEnum.F313, f313.python_unsafe_ssl_context_certificate),
            (FindingEnum.F320, f320.python_unsafe_ldap_connection),
        ),
        "MethodInvocation": (
            (FindingEnum.F004, f004.python_remote_command_execution),
            (FindingEnum.F015, f015.python_danger_basic_auth),
            (FindingEnum.F083, f083.python_xml_parser),
            (FindingEnum.F096, f096.python_deserialization_injection),
            (FindingEnum.F052, f052.python_insecure_cipher),
            (FindingEnum.F052, f052.python_insec_hash_library),
            (FindingEnum.F060, f060.python_unsafe_ssl_hostname),
            (FindingEnum.F063, f063.python_io_path_traversal),
            (FindingEnum.F128, f128.python_http_only_cookie),
            (FindingEnum.F130, f130.python_secure_cookie),
            (FindingEnum.F153, f153.python_danger_accept_header),
            (FindingEnum.F237, f237.python_has_print_statements),
        ),
    },
    GraphShardMetadataLanguage.SWIFT: {
        "MethodInvocation": (
            (FindingEnum.F052, f052.swift_insecure_cipher),
            (FindingEnum.F052, f052.swift_insecure_crypto),
        ),
        "SymbolLookup": ((FindingEnum.F052, f052.swift_insecure_cipher),),
        "MemberAccess": ((FindingEnum.F052, f052.swift_insecure_cryptalgo),),
    },
    GraphShardMetadataLanguage.TYPESCRIPT: {
        "Assignment": ((FindingEnum.F344, f344.ts_local_storage_sens_data),),
        "Debugger": ((FindingEnum.F183, f183.ts_debugging_enabled),),
        "ElementAccess": (
            (FindingEnum.F153, f153.ts_accepts_any_mime_default),
        ),
        "Import": ((FindingEnum.F379, f379.js_import_is_never_used),),
        "JsxElement": ((FindingEnum.F371, f371.ts_dangerously_set_innerhtml),),
        "MemberAccess": (
            (FindingEnum.F309, f309.ts_insecure_jwt_token),
            (FindingEnum.F338, f338.ts_salting_is_harcoded),
            (FindingEnum.F353, f353.ts_decode_insecure_jwt_token),
            (FindingEnum.F371, f371.ts_bypass_security_trust_url),
            (FindingEnum.F371, f371.ts_uses_innerhtml),
        ),
        "MethodInvocation": (
            (FindingEnum.F004, f004.ts_remote_command_execution),
            (FindingEnum.F008, f008.ts_unsafe_xss_content),
            (FindingEnum.F009, f009.typescript_crypto_ts_credentials),
            (FindingEnum.F021, f021.ts_dynamic_xpath),
            (FindingEnum.F083, f083.ts_xml_parser),
            (FindingEnum.F085, f085.ts_client_storage),
            (FindingEnum.F091, f091.ts_insecure_logging),
            (FindingEnum.F097, f097.ts_has_reverse_tabnabbing),
            (FindingEnum.F042, f042.ts_insecurely_generated_cookies),
            (FindingEnum.F052, f052.typescript_insecure_ec_keypair),
            (FindingEnum.F052, f052.typescript_insecure_create_cipher),
            (FindingEnum.F052, f052.typescript_insecure_ecdh_key),
            (FindingEnum.F052, f052.typescript_insecure_encrypt),
            (FindingEnum.F052, f052.typescript_insecure_hash),
            (FindingEnum.F052, f052.typescript_insecure_hash_library),
            (FindingEnum.F052, f052.typescript_insecure_rsa_keypair),
            (FindingEnum.F052, f052.typescript_jwt_insec_sign_algo_async),
            (FindingEnum.F052, f052.typescript_jwt_insec_sign_algorithm),
            (FindingEnum.F060, f060.ts_unsafe_origin),
            (FindingEnum.F063, f063.ts_insecure_path_traversal),
            (FindingEnum.F066, f066.ts_uses_console_log),
            (FindingEnum.F063, f063.ts_zip_slip_injection),
            (FindingEnum.F112, f112.ts_sql_injection),
            (FindingEnum.F128, f128.ts_insecure_cookies),
            (FindingEnum.F143, f143.ts_uses_eval),
            (FindingEnum.F153, f153.js_accepts_any_mime_method),
            (FindingEnum.F188, f188.ts_lack_of_validation_dom_window),
            (FindingEnum.F034, f034.typescript_weak_random),
            (FindingEnum.F211, f211.ts_regex_injection),
            (FindingEnum.F280, f280.ts_non_secure_construction),
            (FindingEnum.F297, f297.ts_sql_injection),
            (FindingEnum.F344, f344.ts_local_storage_sensitive_data),
        ),
        "ObjectCreation": (
            (FindingEnum.F135, f135.ts_insecure_http_headers),
            (FindingEnum.F143, f143.ts_uses_eval),
            (FindingEnum.F152, f152.ts_insecure_header_xframe_options),
            (FindingEnum.F343, f343.ts_insecure_compression),
        ),
    },
    GraphShardMetadataLanguage.YAML: {
        "Object": (
            (FindingEnum.F009, f009.docker_compose_env_secrets),
            (FindingEnum.F016, f016.cfn_elb_without_sslpolicy),
            (
                FindingEnum.F016,
                f016.cfn_serves_content_over_insecure_protocols,
            ),
            (FindingEnum.F024, f024.cfn_allows_anyone_to_admin_ports),
            (FindingEnum.F024, f024.cfn_ec2_has_open_all_ports_to_the_public),
            (
                FindingEnum.F024,
                f024.cfn_ec2_has_security_groups_ip_ranges_in_rfc1918,
            ),
            (FindingEnum.F024, f024.cfn_ec2_has_unrestricted_dns_access),
            (FindingEnum.F024, f024.cfn_ec2_has_unrestricted_ftp_access),
            (FindingEnum.F024, f024.cfn_groups_without_egress),
            (FindingEnum.F024, f024.cfn_instances_without_profile),
            (FindingEnum.F024, f024.cfn_unrestricted_cidrs),
            (FindingEnum.F024, f024.cfn_unrestricted_ip_protocols),
            (FindingEnum.F024, f024.cfn_ec2_has_unrestricted_ports),
            (FindingEnum.F031, f031.cfn_bucket_policy_allows_public_access),
            (FindingEnum.F031, f031.cfn_admin_policy_attached),
            (FindingEnum.F031, f031.cfn_iam_excessive_role_policy),
            (FindingEnum.F031, f031.cfn_iam_has_full_access_to_ssm),
            (FindingEnum.F031, f031.cfn_iam_user_missing_role_based_security),
            (FindingEnum.F031, f031.cfn_negative_statement),
            (FindingEnum.F044, f044.cfn_has_danger_https_methods_enabled),
            (FindingEnum.F044, f044.cfn_api_all_http_methods_enabled),
            (FindingEnum.F070, f070.cfn_elb2_uses_insecure_security_policy),
            (FindingEnum.F073, f073.cfn_rds_is_publicly_accessible),
            (
                FindingEnum.F099,
                f099.cfn_bucket_server_side_encryption_disabled,
            ),
            (FindingEnum.F109, f109.cfn_rds_is_not_inside_a_db_subnet_group),
            (FindingEnum.F165, f165.cfn_iam_allow_not_action_perms_policies),
            (FindingEnum.F165, f165.cfn_iam_allow_not_actions_trust_policy),
            (FindingEnum.F165, f165.cfn_iam_allow_not_principal_trust_policy),
            (FindingEnum.F165, f165.cfn_iam_allow_not_resource_perms_policies),
            (FindingEnum.F165, f165.cfn_iam_is_policy_applying_to_users),
            (FindingEnum.F177, f177.cfn_ec2_use_default_security_group),
            (FindingEnum.F203, f203.cfn_public_buckets),
            (FindingEnum.F246, f246.cfn_rds_has_unencrypted_storage),
            (FindingEnum.F250, f250.cfn_ec2_has_unencrypted_volumes),
            (FindingEnum.F250, f250.cfn_ec2_unencrypted_ebs_block),
            (FindingEnum.F246, f246.cfn_rds_has_unencrypted_storage),
            (FindingEnum.F250, f250.cfn_ec2_has_unencrypted_volumes),
            (FindingEnum.F250, f250.cfn_ec2_unencrypted_ebs_block),
            (FindingEnum.F256, f256.cfn_rds_has_not_automated_backups),
            (FindingEnum.F256, f256.cfn_rds_has_not_termination_protection),
            (FindingEnum.F257, f257.cfn_ec2_has_not_termination_protection),
            (FindingEnum.F258, f258.cfn_elb2_has_not_deletion_protection),
            (FindingEnum.F259, f259.cfn_dynamo_has_not_deletion_protection),
            (FindingEnum.F259, f259.cfn_has_not_point_in_time_recovery),
            (FindingEnum.F267, f267.k8s_allow_privilege_escalation_enabled),
            (FindingEnum.F267, f267.k8s_check_add_capability),
            (FindingEnum.F267, f267.k8s_check_drop_capability),
            (FindingEnum.F267, f267.k8s_check_if_capability_exists),
            (FindingEnum.F267, f267.k8s_check_if_sys_admin_exists),
            (FindingEnum.F267, f267.k8s_check_privileged_used),
            (FindingEnum.F267, f267.k8s_check_run_as_user),
            (FindingEnum.F267, f267.k8s_check_seccomp_profile),
            (FindingEnum.F267, f267.k8s_container_without_securitycontext),
            (FindingEnum.F267, f267.k8s_check_host_pid),
            (FindingEnum.F267, f267.k8s_root_container),
            (FindingEnum.F267, f267.k8s_root_filesystem_read_only),
            (FindingEnum.F281, f281.cfn_bucket_policy_has_secure_transport),
            (FindingEnum.F325, f325.cfn_iam_has_wildcard_action_policy),
            (FindingEnum.F325, f325.cfn_iam_has_wildcard_action_trust_policy),
            (FindingEnum.F325, f325.cfn_iam_has_wildcard_resource_policy),
            (
                FindingEnum.F325,
                f325.cfn_iam_has_wildcard_resource_trust_policy,
            ),
            (FindingEnum.F325, f325.cfn_iam_permissive_policy),
            (FindingEnum.F325, f325.cfn_kms_master_keys_exposed_to_everyone),
            (FindingEnum.F332, f332.cfn_secgroup_uses_insecure_protocol),
            (FindingEnum.F332, f332.k8s_insecure_port),
            (FindingEnum.F333, f333.cfn_ec2_associate_public_ip_address),
            (FindingEnum.F333, f333.cfn_ec2_has_not_an_iam_instance_profile),
            (FindingEnum.F333, f333.cfn_ec2_has_terminate_shutdown_behavior),
            (FindingEnum.F335, f335.cfn_s3_bucket_versioning_disabled),
            (FindingEnum.F363, f363.cfn_insecure_generate_secret_string),
            (FindingEnum.F372, f372.cfn_elb2_uses_insecure_http_protocol),
            (FindingEnum.F372, f372.cfn_serves_content_over_http),
            (FindingEnum.F394, f394.cfn_log_files_not_validated),
            (
                FindingEnum.F396,
                f396.cfn_kms_key_is_key_rotation_absent_or_disabled,
            ),
            (FindingEnum.F400, f400.cfn_bucket_has_logging_conf_disabled),
            (FindingEnum.F400, f400.cfn_cf_distribution_has_logging_disabled),
            (FindingEnum.F400, f400.cfn_ec2_monitoring_disabled),
            (FindingEnum.F400, f400.cfn_elb2_has_access_logs_s3_disabled),
            (FindingEnum.F400, f400.cfn_elb_has_access_logging_disabled),
            (FindingEnum.F400, f400.cfn_trails_not_multiregion),
            (FindingEnum.F406, f406.cfn_aws_efs_unencrypted),
            (FindingEnum.F407, f407.cfn_aws_ebs_volumes_unencrypted),
            (FindingEnum.F408, f408.cfn_api_gateway_access_logging_disabled),
            (FindingEnum.F426, f426.k8s_image_has_digest),
        ),
        "Pair": (
            (FindingEnum.F022, f022.cfn_server_port_insecure_channel),
            (FindingEnum.F134, f134.cfn_cors_true),
            (FindingEnum.F134, f134.cfn_wildcard_in_allowed_origins),
            (FindingEnum.F313, f313.cfn_insecure_certificate),
            (FindingEnum.F332, f332.cfn_server_disabled_ssl),
            (FindingEnum.F332, f332.k8s_insecure_http_channel),
            (FindingEnum.F380, f380.docker_compose_image_has_digest),
        ),
    },
}
