:page-background-image: {{finding_summary_background}}

{% for finding in findings %}
==== {{finding.title + "\n"}}
|===
|{{severity_title}}|{{cardinality_title}}|{{state_title}}
{{"|"+finding.severity_score|string+"|"+finding.open_vulnerabilities|string+"|"+finding.state}}
|===
===== {{description_title}}
{{finding.description + "\n"}}
===== {{threat_title}}
{{finding.threat + "\n"}}

===== {{attack_vector_title}}
{{finding.attack_vector_description + "\n"}}

===== {{solution_title}}
{{finding.recommendation + "\n"}}
===== {{requisite_title}}
    {% for req in finding.requirements.split("\n") %}
        - {{req + "\n"}}
    {% endfor %}
==== {{where_title}}
{% if finding.grouped_ports_vulnerabilities or finding.grouped_lines_vulnerabilities or finding.grouped_inputs_vulnerabilities %}
===== {{ports}}
|===
|{{'Host'}}|{{port}}
{% for port in finding.grouped_ports_vulnerabilities %}
{{'|'+port.where+'|'+port.specific}}
{% endfor %}
|===
===== {{lines}}
|===
|{{path}}|{{line}}|{{commit_hash}}
{% for line in finding.grouped_lines_vulnerabilities %}
{{'|'+line.where+'|'+line.specific+'|'+line.commit_hash}}
{% endfor %}
|===
===== {{inputs}}
|===
|{{'URL'}}|{{field}}
{% for input in finding.grouped_inputs_vulnerabilities %}
{{'|'+input.where+'|'+input.specific}}
{% endfor %}
|===
{% else %}
    {{finding.where.lstrip() + '\n'}}
{% endif %}
==== {{evidence_title}}
{% for evidence in finding.evidence_set %}
{{evidence['explanation'] + "\n"}}
{{evidence['name']+"\n"}}
<<<
{% endfor %}
<<<
{%- endfor %}
