aioboto3: 9.6.0
aiodataloader: 0.3.0
aioextensions: 20.11.1621472
aiofiles: 0.6.0
aiohttp: 3.7.4
androguard: 3.3.5
asn1crypto: 1.4.0
beautifulsoup4: 4.9.3
cfn-flip: 1.2.3
click: 8.1.3
confuse: 2.0.1
cvss: "2.6"
dnspython: 2.2.1
expiringdict: 1.2.2
frozendict: 2.0.2
future: 0.18.2
gemfileparser: 0.8.0
GitPython: 3.1.29
jmespath: 0.10.0
json-parser: 1.2.0
json-source-map: 1.0.3
lark-parser: 0.7.8 # pending to upgrade
lxml: 4.9.2
metaloaders: 20.9.2566091
more-itertools: 9.0.0
mypy-extensions: 0.4.3
networkx: 2.5.1
ntplib: 0.4.0
oyaml: "1.0"
pathspec: 0.8.1
PyYAML: "6.0"
pyarn: 0.1.2
pygments: 2.9.0
pygraphviz: "1.10"
pyleri: 1.4.1
pyparsing: 2.4.7
python-dateutil: 2.8.1
python-hcl2: 1.0.0 # pending to upgrade
python-jose: 3.2.0
pytz: "2021.3"
reactivex: 4.0.4
platformdirs: 2.5.4
wrapt-timeout-decorator: 1.3.12.2
requirements-parser: 0.5.0
requests: 2.25.1
sarif-om: 1.0.4
semantic-version: 2.10.0
semver: 2.13.0
simplejson: 3.17.0
soupsieve: 2.2.1
sympy: "1.12"
tlslite-ng: 0.8.0a41
tree-sitter: 0.20.1
unidiff: 0.6.0
viewstate: 0.4.3
virtualenv: 20.15.0
watchtower: 2.0.1
wcmatch: "8.4"
pickleshare: 0.7.5
