announcekit_user: ENC[AES256_GCM,data:im7E55k1MetacwqcJQp07Rvd6zlC3NP8XGsSYw==,iv:SCaVjL0Fv9mRGHLKlFeWNWIG8pjDE/Bqv7Gs+py+x3k=,tag:w2svXch3iF9LUMmdo8Hcpg==,type:str]
announcekit_passwd: ENC[AES256_GCM,data:eDhC9zF0iqwT4IodjO0HOBnbGDiZlJcVOQ==,iv:OqtCA36Xcivadl8JIGsyKbaVJ5vOMed2CPQAglXb9YI=,tag:cAA0aGqVmcktdpjm+ux/kQ==,type:str]
announcekit_proj: ENC[AES256_GCM,data:Toe7gc4=,iv:/kI9LMkmNnALIHVI9HVKVzzsgrKJMjjG3FwLKhK7x6Q=,tag:We4CSJY3YAkLp4zUNovt3w==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:205810638802:alias/dev
          created_at: "2022-02-21T19:49:50Z"
          enc: AQICAHhXTEro6XxD1aUcNM+ov9OG4EgBp9RTxhGglF2qwWCpLAEs7zb7a/ANfY/9yBFqbhCTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMa1QegCunbNvv3zp2AgEQgDvNSVTNStAnixTr9MO02wLbUVrbfN3HZ8GeA0Z8Q/yaEExKcg6JUa4A+M46ifb3fE/OoGCObL0/roEtUA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-06T13:35:20Z"
    mac: ENC[AES256_GCM,data:JuwKZuvozVUHbitRKb9QwU/x376lIpK6rmjXKYUGawYcjgaftKt3mAxTn8HVrWSqrKHQaXZVxIXfC1cwrXzu8PtSz+yFdBEbwvUNdjOPK26oU1BFZrQMEF2pgmax4oIwwyV5ejwgEPNJi3SqsjFTC0fOvKA3TcKRpv/EgcIrA/U=,iv:WwfaFxxUhAZU9akpCoQzHnXZrP/f+NeztcfYMToZE8o=,tag:35pPD3srgDpKGEe9QBus/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
