import React from "react";

import { StyledContainer } from "./styledComponents";
import type { IContainerProps } from "./types";

const Container: React.FC<IContainerProps> = ({
  align,
  bgColor,
  bgGradient,
  borderBottomColor,
  borderTopColor,
  borderColor,
  borderHoverColor,
  br,
  center,
  children,
  classname,
  direction,
  display,
  displayMd,
  displaySm,
  height,
  hovercolor,
  hoverShadow,
  id,
  justify,
  justifyMd,
  justifySm,
  leftBar,
  maxWidth,
  mb,
  mh,
  minHeight,
  minWidth,
  minWidthMd,
  minWidthSm,
  ml,
  mr,
  mt,
  mtMd,
  mtSm,
  mv,
  onClick,
  pb,
  ph,
  phMd,
  phSm,
  pl,
  position,
  pr,
  pt,
  pv,
  pvMd,
  pvSm,
  shadow,
  shadowBottom,
  textHoverColor,
  topBar,
  width,
  widthMd,
  widthSm,
  wrap,
}): JSX.Element => {
  return (
    <StyledContainer
      align={align}
      bgColor={bgColor}
      bgGradient={bgGradient}
      borderBottomColor={borderBottomColor}
      borderColor={borderColor}
      borderHoverColor={borderHoverColor}
      borderTopColor={borderTopColor}
      br={br}
      center={center}
      classname={classname}
      direction={direction}
      display={display}
      displayMd={displayMd}
      displaySm={displaySm}
      height={height}
      hoverShadow={hoverShadow}
      hovercolor={hovercolor}
      id={id}
      justify={justify}
      justifyMd={justifyMd}
      justifySm={justifySm}
      leftBar={leftBar}
      maxWidth={maxWidth}
      mb={mb}
      mh={mh}
      minHeight={minHeight}
      minWidth={minWidth}
      minWidthMd={minWidthMd}
      minWidthSm={minWidthSm}
      ml={ml}
      mr={mr}
      mt={mt}
      mtMd={mtMd}
      mtSm={mtSm}
      mv={mv}
      onClick={onClick}
      pb={pb}
      ph={ph}
      phMd={phMd}
      phSm={phSm}
      pl={pl}
      position={position}
      pr={pr}
      pt={pt}
      pv={pv}
      pvMd={pvMd}
      pvSm={pvSm}
      shadow={shadow}
      shadowBottom={shadowBottom}
      textHoverColor={textHoverColor}
      topBar={topBar}
      width={width}
      widthMd={widthMd}
      widthSm={widthSm}
      wrap={wrap}
    >
      {children}
    </StyledContainer>
  );
};

export { Container };
