# pylint: disable=import-error,too-many-lines
from back.test import (
    db,
)
from datetime import (
    datetime,
)
from db_model.enums import (
    GitCloningStatus,
    Source,
)
from db_model.findings.enums import (
    FindingStateStatus,
    FindingStatus,
    FindingVerificationStatus,
)
from db_model.findings.types import (
    CVSS31Severity,
    Finding,
    FindingEvidence,
    FindingEvidences,
    FindingState,
    FindingUnreliableIndicatorsToUpdate,
    FindingVerification,
)
from db_model.groups.enums import (
    GroupLanguage,
    GroupManaged,
    GroupService,
    GroupStateStatus,
    GroupSubscriptionType,
    GroupTier,
)
from db_model.groups.types import (
    Group,
    GroupState,
)
from db_model.organization_finding_policies.enums import (
    PolicyStateStatus,
)
from db_model.organization_finding_policies.types import (
    OrgFindingPolicy,
    OrgFindingPolicyState,
)
from db_model.roots.enums import (
    RootStatus,
    RootType,
)
from db_model.roots.types import (
    GitRoot,
    GitRootCloning,
    GitRootState,
    IPRoot,
    IPRootState,
    RootEnvironmentUrl,
)
from db_model.toe_inputs.types import (
    ToeInput,
    ToeInputState,
)
from db_model.toe_lines.types import (
    ToeLines,
    ToeLinesState,
)
from db_model.toe_ports.types import (
    ToePort,
    ToePortState,
)
from db_model.types import (
    SeverityScore,
)
from db_model.vulnerabilities.enums import (
    VulnerabilityStateStatus,
    VulnerabilityTechnique,
    VulnerabilityTreatmentStatus,
    VulnerabilityType,
    VulnerabilityVerificationStatus,
    VulnerabilityZeroRiskStatus,
)
from db_model.vulnerabilities.types import (
    Vulnerability,
    VulnerabilityState,
    VulnerabilityTreatment,
    VulnerabilityUnreliableIndicators,
    VulnerabilityVerification,
    VulnerabilityZeroRisk,
)
from decimal import (
    Decimal,
)
import pytest
import pytest_asyncio
from typing import (
    Any,
)


@pytest.mark.resolver_test_group("upload_file")
@pytest_asyncio.fixture(autouse=True, scope="session")
async def populate(generic_data: dict[str, Any]) -> bool:
    data: dict[str, Any] = {
        "findings": [
            {
                "finding": Finding(
                    id="918fbc15-2121-4c2a-83a8-dfa8748bcb2e",
                    group_name="group123",
                    severity_score=SeverityScore(),
                    state=FindingState(
                        modified_by="test@fluidattacks.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:11+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.CREATED,
                    ),
                    title="001. SQL injection",
                    hacker_email="test@fluidattacks.com",
                ),
                "historic_state": [],
                "historic_verification": [],
            },
            {
                "finding": Finding(
                    id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    state=FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:11+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.CREATED,
                    ),
                    title="001. SQL injection - C Sharp SQL API",
                    recommendation="Updated recommendation",
                    description="I just have updated the description",
                    hacker_email="test1@gmail.com",
                    severity=CVSS31Severity(
                        attack_complexity=Decimal("0.77"),
                        attack_vector=Decimal("0.62"),
                        availability_impact=Decimal("0.00"),
                        availability_requirement=Decimal("0.0"),
                        confidentiality_impact=Decimal("0.56"),
                        confidentiality_requirement=Decimal("0.0"),
                        exploitability=Decimal("1.0"),
                        integrity_impact=Decimal("0.00"),
                        integrity_requirement=Decimal("0.0"),
                        modified_attack_complexity=Decimal("0.0"),
                        modified_attack_vector=Decimal("0.0"),
                        modified_availability_impact=Decimal("0.0"),
                        modified_confidentiality_impact=Decimal("0.0"),
                        modified_integrity_impact=Decimal("0.0"),
                        modified_privileges_required=Decimal("0.0"),
                        modified_user_interaction=Decimal("0.0"),
                        modified_severity_scope=Decimal("0.0"),
                        privileges_required=Decimal("0.62"),
                        remediation_level=Decimal("1.00"),
                        report_confidence=Decimal("1.00"),
                        severity_scope=Decimal("0.0"),
                        user_interaction=Decimal("0.85"),
                    ),
                    severity_score=SeverityScore(
                        base_score=Decimal("5.7"),
                        temporal_score=Decimal("5.7"),
                        cvss_v3="CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                        cvssf=Decimal("10.556"),
                    ),
                    requirements=(
                        "REQ.0132. Passwords (phrase type) "
                        "must be at least 3 words long."
                    ),
                    threat="Updated threat",
                    attack_vector_description=(
                        "This is an updated attack vector"
                    ),
                    evidences=FindingEvidences(
                        evidence1=FindingEvidence(
                            description="evidence1",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-evidence1"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                        records=FindingEvidence(
                            description="records",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-records"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2111-11-19T13:37:10+00:00"
                            ),
                        ),
                    ),
                ),
                "historic_state": [
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:12+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.SUBMITTED,
                    ),
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:13+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.REJECTED,
                    ),
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:14+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.SUBMITTED,
                    ),
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:45:15+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.APPROVED,
                    ),
                ],
                "historic_verification": [
                    FindingVerification(
                        comment_id="42343434",
                        modified_by="requester@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:11+00:00"
                        ),
                        status=FindingVerificationStatus.REQUESTED,
                        vulnerability_ids={
                            "be09edb7-cd5c-47ed-bee4-97c645acdce8",
                            "be09edb7-cd5c-47ed-bee4-97c645acdce9",
                            "be09edb7-cd5c-47ed-bee4-97c645acdcea",
                        },
                    ),
                    FindingVerification(
                        comment_id="54545454",
                        modified_by="reattacker@fluidattack.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:12+00:00"
                        ),
                        status=FindingVerificationStatus.VERIFIED,
                        vulnerability_ids={
                            "be09edb7-cd5c-47ed-bee4-97c645acdcea",
                        },
                    ),
                ],
                "unreliable_indicators": FindingUnreliableIndicatorsToUpdate(
                    unreliable_closed_vulnerabilities=1,
                    unreliable_open_vulnerabilities=2,
                    unreliable_newest_vulnerability_report_date=(
                        datetime.fromisoformat("2018-04-08T00:43:11+00:00")
                    ),
                    unreliable_oldest_open_vulnerability_report_date=(
                        datetime.fromisoformat("2018-04-08T00:43:11+00:00")
                    ),
                    unreliable_oldest_vulnerability_report_date=(
                        datetime.fromisoformat("2018-04-08T00:43:11+00:00")
                    ),
                    unreliable_status=FindingStatus.VULNERABLE,
                    unreliable_where=(
                        "192.168.1.44, 192.168.1.45, 192.168.1.46"
                    ),
                ),
            },
            {
                "finding": Finding(
                    id="333d9984-17b0-434a-a8e0-a464c74f0212",
                    group_name="group1234",
                    state=FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:11+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.CREATED,
                    ),
                    title="002. Asymmetric denial of service",
                    recommendation="Updated recommendation",
                    description="Another description",
                    hacker_email="test1@gmail.com",
                    severity=CVSS31Severity(
                        attack_complexity=Decimal("0.44"),
                        attack_vector=Decimal("0.2"),
                        availability_impact=Decimal("0.22"),
                        availability_requirement=Decimal("1.5"),
                        confidentiality_impact=Decimal("0.22"),
                        confidentiality_requirement=Decimal("0.5"),
                        exploitability=Decimal("0.94"),
                        integrity_impact=Decimal("0.22"),
                        integrity_requirement=Decimal("1"),
                        modified_availability_impact=Decimal("0.22"),
                        modified_user_interaction=Decimal("0.62"),
                        modified_integrity_impact=Decimal("0"),
                        modified_attack_complexity=Decimal("0.44"),
                        modified_severity_scope=Decimal("0"),
                        modified_privileges_required=Decimal("0.27"),
                        modified_attack_vector=Decimal("0.85"),
                        modified_confidentiality_impact=Decimal("0.22"),
                        privileges_required=Decimal("0.62"),
                        severity_scope=Decimal("1.0"),
                        remediation_level=Decimal("0.95"),
                        report_confidence=Decimal("1"),
                        user_interaction=Decimal("0.85"),
                    ),
                    severity_score=SeverityScore(
                        base_score=Decimal("4.5"),
                        temporal_score=Decimal("4.1"),
                        cvss_v3="CVSS:3.1/AV:P/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:L/"
                        "E:P/RL:O/CR:L/AR:H/MAV:N/MAC:H/MPR:H/MUI:R/MS:U/MC:L/"
                        "MA:L",
                        cvssf=Decimal("1.149"),
                    ),
                    requirements=(
                        "REQ.0132. Passwords (phrase type) "
                        "must be at least 3 words long."
                    ),
                    threat="Updated threat",
                    attack_vector_description="This is an attack vector",
                    evidences=FindingEvidences(
                        evidence1=FindingEvidence(
                            description="evidence1",
                            url=(
                                "group1234-333d9984-17b0-434a-"
                                "a8e0-a464c74f0212-evidence1"
                            ),
                            is_draft=False,
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                    ),
                ),
                "historic_state": [
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:14+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.SUBMITTED,
                    ),
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:45:15+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.APPROVED,
                    ),
                ],
                "historic_verification": [],
                "unreliable_indicator": FindingUnreliableIndicatorsToUpdate(
                    unreliable_closed_vulnerabilities=0,
                    unreliable_open_vulnerabilities=1,
                    unreliable_newest_vulnerability_report_date=(
                        datetime.fromisoformat("2020-12-26T05:45:00+00:00")
                    ),
                    unreliable_oldest_open_vulnerability_report_date=(
                        datetime.fromisoformat("2020-02-24T05:45:00+00:00")
                    ),
                    unreliable_oldest_vulnerability_report_date=(
                        datetime.fromisoformat("2018-04-01T05:45:00+00:00")
                    ),
                    unreliable_status=FindingStatus.VULNERABLE,
                    unreliable_where=(
                        "https://test.test/GetList?=1234&"
                        "amp;page=1&amp;start=56789"
                    ),
                ),
            },
            {
                "finding": Finding(
                    id="475041531",
                    group_name="group1",
                    rejected_vulnerabilities=0,
                    submitted_vulnerabilities=0,
                    evidences=FindingEvidences(
                        evidence1=FindingEvidence(
                            description="evidence1",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-evidence1"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                        evidence2=FindingEvidence(
                            description="evidence2",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-evidence2"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                        evidence3=FindingEvidence(
                            description="evidence3",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-evidence3"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                        evidence4=FindingEvidence(
                            description="evidence4",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-evidence4"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                        evidence5=FindingEvidence(
                            description="evidence5",
                            url=(
                                "group1-3c475384-834c-47b0-"
                                "ac71-a41a022e401c-evidence5"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                        exploitation=FindingEvidence(
                            description="exploitation",
                            url=(
                                "group1-3c475384-834c-47b0-ac71"
                                "-a41a022e401c-exploitation"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2010-11-19T13:37:10+00:00"
                            ),
                        ),
                        animation=FindingEvidence(
                            description="animation",
                            url=(
                                "group1-3c475384-834c-47b0-ac71-"
                                "a41a022e401c-animation"
                            ),
                            modified_date=datetime.fromisoformat(
                                "2020-11-19T13:37:10+00:00"
                            ),
                        ),
                    ),
                    state=FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:11+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.CREATED,
                    ),
                    title="001. SQL injection - C Sharp SQL API",
                    recommendation="Updated recommendation",
                    description="I just have updated the description",
                    hacker_email="test1@gmail.com",
                    severity=CVSS31Severity(
                        attack_complexity=Decimal("0.77"),
                        attack_vector=Decimal("0.2"),
                        availability_impact=Decimal("0.22"),
                        availability_requirement=Decimal("1.5"),
                        confidentiality_impact=Decimal("0.22"),
                        confidentiality_requirement=Decimal("0.5"),
                        exploitability=Decimal("0.94"),
                        integrity_impact=Decimal("0.22"),
                        integrity_requirement=Decimal("1"),
                        modified_availability_impact=Decimal("0.22"),
                        modified_user_interaction=Decimal("0.62"),
                        modified_integrity_impact=Decimal("0"),
                        modified_attack_complexity=Decimal("0.44"),
                        modified_severity_scope=Decimal("0"),
                        modified_privileges_required=Decimal("0.27"),
                        modified_attack_vector=Decimal("0.85"),
                        modified_confidentiality_impact=Decimal("0.22"),
                        privileges_required=Decimal("0.62"),
                        severity_scope=Decimal("1.0"),
                        remediation_level=Decimal("0.95"),
                        report_confidence=Decimal("1"),
                        user_interaction=Decimal("0.85"),
                    ),
                    severity_score=SeverityScore(
                        base_score=Decimal("4.9"),
                        temporal_score=Decimal("4.4"),
                        cvss_v3="CVSS:3.1/AV:P/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:L"
                        "/E:P/RL:O/CR:L/AR:H/MAV:N/MAC:H/MPR:H/MUI:R/MS:U/MC:L"
                        "/MA:L",
                        cvssf=Decimal("1.741"),
                    ),
                    requirements=(
                        "REQ.0132. Passwords (phrase type) "
                        "must be at least 3 words long."
                    ),
                    threat="Updated threat",
                    attack_vector_description=(
                        "This is an updated attack vector"
                    ),
                ),
                "historic_state": [
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:12+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.SUBMITTED,
                    ),
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:13+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.REJECTED,
                    ),
                    FindingState(
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2017-04-08T00:45:14+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.SUBMITTED,
                    ),
                    FindingState(
                        modified_by=generic_data["global_vars"]["admin_email"],
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:45:15+00:00"
                        ),
                        source=Source.ASM,
                        status=FindingStateStatus.APPROVED,
                    ),
                ],
                "historic_verification": [
                    FindingVerification(
                        comment_id="42343434",
                        modified_by="test1@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-01-01T00:45:12+00:00"
                        ),
                        status=FindingVerificationStatus.REQUESTED,
                        vulnerability_ids={
                            "be09edb7-cd5c-47ed-bee4-97c645acdce8",
                            "uuid2",
                        },
                    )
                ],
                "unreliable_indicators": FindingUnreliableIndicatorsToUpdate(
                    unreliable_closed_vulnerabilities=0,
                    unreliable_open_vulnerabilities=1,
                    unreliable_newest_vulnerability_report_date=(
                        datetime.fromisoformat("2020-12-26T05:45:00+00:00")
                    ),
                    unreliable_oldest_open_vulnerability_report_date=(
                        datetime.fromisoformat("2020-02-24T05:45:00+00:00")
                    ),
                    unreliable_oldest_vulnerability_report_date=(
                        datetime.fromisoformat("2018-04-01T05:45:00+00:00")
                    ),
                    unreliable_status=FindingStatus.DRAFT,
                ),
            },
        ],
        "roots": [
            {
                "root": GitRoot(
                    cloning=GitRootCloning(
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        reason="root creation",
                        status=GitCloningStatus("UNKNOWN"),
                    ),
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                    organization_name="orgtest",
                    state=GitRootState(
                        branch="master",
                        environment="production",
                        gitignore=["bower_components/*", "node_modules/*"],
                        includes_health_check=True,
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                        url="https://gitlab.com/fluidattacks/universe",
                    ),
                    type=RootType.GIT,
                ),
                "historic_state": [],
                "git_environment_urls": [
                    RootEnvironmentUrl(
                        url="https://test.com",
                        id="78dd64d3198473115a7f5263d27bed15f9f2fc07",
                    )
                ],
            },
            {
                "root": GitRoot(
                    cloning=GitRootCloning(
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        reason="root creation",
                        status=GitCloningStatus("UNKNOWN"),
                    ),
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="e782e588-060d-4ae7-8930-3c11d2ba4395",
                    organization_name="orgtest",
                    state=GitRootState(
                        branch="master",
                        environment="production",
                        gitignore=["node_modules/*"],
                        includes_health_check=True,
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe123",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                        url="https://gitlab.com/fluidattacks/universe",
                    ),
                    type=RootType.GIT,
                ),
                "historic_state": [],
                "git_environment_urls": [
                    RootEnvironmentUrl(
                        url="https://testtest.com",
                        id="683d198c-f88d-4a92-a02d-7377ad2dca45",
                    ),
                ],
            },
            {
                "root": GitRoot(
                    cloning=GitRootCloning(
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        reason="root creation",
                        status=GitCloningStatus("UNKNOWN"),
                    ),
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1234",
                    id="ad63c994-cd29-4b31-a21f-60306e2a3e56",
                    organization_name="orgtest",
                    state=GitRootState(
                        branch="main",
                        environment="production",
                        gitignore=[],
                        includes_health_check=True,
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe1234",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                        url="https://gitlab.com/testgroup/testproject",
                    ),
                    type=RootType.GIT,
                ),
                "historic_state": [],
                "git_environment_urls": [
                    RootEnvironmentUrl(
                        url=(
                            "https://test.test/GetList"
                            "?=1234&page=1&start=56789"
                        ),
                        id="95552a1e-e968-46ac-994f-c08b66925f22",
                    ),
                ],
            },
            {
                "root": GitRoot(
                    cloning=GitRootCloning(
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        reason="root creation",
                        commit="0d511e3b72e06f45fffa2ca2b5ef82a23ccfe021",
                        status=GitCloningStatus("UNKNOWN"),
                    ),
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="d3abda84-72fc-4725-95d1-c674d0e2c13f",
                    organization_name="orgtest",
                    state=GitRootState(
                        branch="main",
                        environment="production",
                        gitignore=[],
                        includes_health_check=True,
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe99",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                        url="https://gitlab.com/fluidattacks/universetest",
                    ),
                    type=RootType.GIT,
                ),
                "historic_state": [],
                "git_environment_urls": [
                    RootEnvironmentUrl(
                        url="https://test.com/test",
                        id="79dd64d3198473115a7f5263d27bed15f9f2fc07",
                    )
                ],
            },
            {
                "root": IPRoot(
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="40190504-eeab-4640-af14-2af5673041e6",
                    organization_name="orgtest",
                    state=IPRootState(
                        address="192.168.1.44",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe44",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                    ),
                    type=RootType.IP,
                ),
                "historic_state": [],
            },
            {
                "root": IPRoot(
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="bb90e4a1-9e24-4d1b-af48-24fb5f09dc71",
                    organization_name="orgtest",
                    state=IPRootState(
                        address="192.168.1.45",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe45",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                    ),
                    type=RootType.IP,
                ),
                "historic_state": [],
            },
            {
                "root": IPRoot(
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="44325233-5f35-46f2-a7c1-86653d0d16e7",
                    organization_name="orgtest",
                    state=IPRootState(
                        address="192.168.1.45",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2021-11-19T13:37:10+00:00"
                        ),
                        nickname="universe95",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                    ),
                    type=RootType.IP,
                ),
                "historic_state": [],
            },
            {
                "root": IPRoot(
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="f54c209e-45e8-4960-9aa5-bb9c34987e09",
                    organization_name="orgtest",
                    state=IPRootState(
                        address="192.168.1.46",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe46",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                    ),
                    type=RootType.IP,
                ),
                "historic_state": [],
            },
            {
                "root": IPRoot(
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="715f2498-bb07-41a4-99bd-61bd008fa903",
                    organization_name="orgtest",
                    state=IPRootState(
                        address="192.168.1.47",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe47",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                    ),
                    type=RootType.IP,
                ),
                "historic_state": [],
            },
            {
                "root": IPRoot(
                    created_by="admin@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-11-19T13:37:10+00:00"
                    ),
                    group_name="group1",
                    id="30c85c00-d2ab-43f4-b75e-7ae27928c8a4",
                    organization_name="orgtest",
                    state=IPRootState(
                        address="192.168.1.57",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-11-19T13:37:10+00:00"
                        ),
                        nickname="universe57",
                        other=None,
                        reason=None,
                        status=RootStatus.ACTIVE,
                    ),
                    type=RootType.IP,
                ),
                "historic_state": [],
            },
        ],
        "toe_inputs": (
            ToeInput(
                component="https://example.com",
                entry_point="phone",
                group_name="group1",
                state=ToeInputState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=False,
                    modified_by="hacker@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2022-02-02T06:00:00+00:00"
                    ),
                    seen_at=None,
                    seen_first_time_by="",
                    unreliable_root_id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                ),
            ),
            ToeInput(
                component="https://test.test/GetList?=1234&page=1&start=56789",
                entry_point="input:list:url",
                group_name="group1234",
                state=ToeInputState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=False,
                    modified_by="hacker@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2022-02-02T06:00:00+00:00"
                    ),
                    seen_at=None,
                    seen_first_time_by="",
                    unreliable_root_id="ad63c994-cd29-4b31-a21f-60306e2a3e56",
                ),
            ),
            ToeInput(
                component="https://test.test/GetList?=1234&page=1&start=56789",
                entry_point="input:list:user",
                group_name="group1234",
                state=ToeInputState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=False,
                    modified_by="hacker@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2022-02-02T06:00:00+00:00"
                    ),
                    seen_at=None,
                    seen_first_time_by="",
                    unreliable_root_id="ad63c994-cd29-4b31-a21f-60306e2a3e56",
                ),
            ),
            ToeInput(
                component="https://example.com",
                entry_point="pphone (en)",
                group_name="group1",
                state=ToeInputState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=False,
                    modified_by="hacker@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2022-02-02T06:00:00+00:00"
                    ),
                    seen_at=None,
                    seen_first_time_by="",
                    unreliable_root_id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                ),
            ),
            ToeInput(
                component="https://example.com",
                entry_point="contact (en) [CVE-0000-1111]",
                group_name="group1",
                state=ToeInputState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=False,
                    modified_by="hacker@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2022-02-02T06:00:00+00:00"
                    ),
                    seen_at=None,
                    seen_first_time_by="",
                    unreliable_root_id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                ),
            ),
            ToeInput(
                component="https://test_new_closed.com",
                entry_point="phone",
                group_name="group1",
                state=ToeInputState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="",
                    be_present=True,
                    be_present_until=None,
                    has_vulnerabilities=False,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    modified_by="hacker@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2022-02-02T06:00:00+00:00"
                    ),
                    seen_at=None,
                    seen_first_time_by="",
                    unreliable_root_id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                ),
            ),
        ),
        "toe_lines": (
            ToeLines(
                filename="path/to/file1.ext",
                group_name="group1",
                root_id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                state=ToeLinesState(
                    attacked_at=None,
                    attacked_by="test@test.com",
                    attacked_lines=23,
                    be_present=True,
                    be_present_until=None,
                    comments="",
                    first_attack_at=None,
                    modified_by="test@test.com",
                    modified_date=datetime.fromisoformat(
                        "2020-11-16T15:41:04+00:00"
                    ),
                    has_vulnerabilities=False,
                    last_author="customer1@gmail.com",
                    last_commit="f9e4beba70c4f34d6117c3b0c23ebe6b2bff66c1",
                    last_commit_date=datetime.fromisoformat(
                        "2020-11-16T15:41:04+00:00"
                    ),
                    loc=4324,
                    seen_at=datetime.fromisoformat(
                        "2020-01-01T15:41:04+00:00"
                    ),
                    sorts_risk_level=0,
                ),
            ),
            ToeLines(
                filename="path/to/file22.ext",
                group_name="group1",
                root_id="d3abda84-72fc-4725-95d1-c674d0e2c13f",
                state=ToeLinesState(
                    attacked_at=None,
                    attacked_by="test@test.com",
                    attacked_lines=77,
                    be_present=True,
                    be_present_until=None,
                    comments="",
                    first_attack_at=None,
                    modified_by="test@test.com",
                    modified_date=datetime.fromisoformat(
                        "2020-11-16T15:41:04+00:00"
                    ),
                    has_vulnerabilities=False,
                    last_author="customer1@gmail.com",
                    last_commit="0d511e3b72e06f45fffa2ca2b5ef82a23ccfe021",
                    last_commit_date=datetime.fromisoformat(
                        "2020-11-16T15:41:04+00:00"
                    ),
                    loc=99,
                    seen_at=datetime.fromisoformat(
                        "2020-01-01T15:41:04+00:00"
                    ),
                    sorts_risk_level=0,
                ),
            ),
            ToeLines(
                filename="test/1",
                group_name="group1",
                root_id="63298a73-9dff-46cf-b42d-9b2f01a56690",
                state=ToeLinesState(
                    attacked_at=datetime.fromisoformat(
                        "2021-02-20T05:00:00+00:00"
                    ),
                    attacked_by="test2@test.com",
                    attacked_lines=4,
                    be_present=True,
                    be_present_until=None,
                    comments="comment 2",
                    first_attack_at=datetime.fromisoformat(
                        "2020-02-19T15:41:04+00:00"
                    ),
                    modified_by="test2@test.com",
                    modified_date=datetime.fromisoformat(
                        "2020-11-15T15:41:04+00:00"
                    ),
                    has_vulnerabilities=False,
                    last_author="customer2@gmail.com",
                    last_commit="f9e4beba70c4f34d6117c3b0c23ebe6b2bff66c2",
                    last_commit_date=datetime.fromisoformat(
                        "2020-11-15T15:41:04+00:00"
                    ),
                    loc=180,
                    seen_at=datetime.fromisoformat(
                        "2020-02-01T15:41:04+00:00"
                    ),
                    sorts_risk_level=-1,
                ),
            ),
        ),
        "toe_ports": (
            ToePort(
                address="192.168.1.44",
                port="4444",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="40190504-eeab-4640-af14-2af5673041e6",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.45",
                port="4545",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="bb90e4a1-9e24-4d1b-af48-24fb5f09dc71",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.46",
                port="4646",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="f54c209e-45e8-4960-9aa5-bb9c34987e09",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.45",
                port="4545",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="44325233-5f35-46f2-a7c1-86653d0d16e7",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.47",
                port="4747",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="715f2498-bb07-41a4-99bd-61bd008fa903",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.57",
                port="8001",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="30c85c00-d2ab-43f4-b75e-7ae27928c8a4",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.57",
                port="8002",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="30c85c00-d2ab-43f4-b75e-7ae27928c8a4",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.57",
                port="8081",
                group_name="group1",
                seen_at=datetime.fromisoformat("2001-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="30c85c00-d2ab-43f4-b75e-7ae27928c8a4",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.45",
                port="4848",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="44325233-5f35-46f2-a7c1-86653d0d16e7",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
            ToePort(
                address="192.168.1.45",
                port="4848",
                group_name="group1",
                seen_at=datetime.fromisoformat("2000-01-01T05:00:00+00:00"),
                seen_first_time_by="test1@test.com",
                root_id="bb90e4a1-9e24-4d1b-af48-24fb5f09dc71",
                state=ToePortState(
                    attacked_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    attacked_by="admin@gmail.com",
                    be_present=True,
                    be_present_until=None,
                    first_attack_at=datetime.fromisoformat(
                        "2020-01-02T05:00:00+00:00"
                    ),
                    has_vulnerabilities=True,
                    modified_date=datetime.fromisoformat(
                        "2000-01-01T05:00:00+00:00"
                    ),
                    modified_by="admin@gmail.com",
                ),
            ),
        ),
        "vulnerabilities": [
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2018-04-08T00:43:11+00:00"
                    ),
                    finding_id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="be09edb7-cd5c-47ed-bee4-97c645acdce8",
                    root_id="40190504-eeab-4640-af14-2af5673041e6",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:43:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="4444",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where="192.168.1.44",
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:43:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.PORTS,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_last_reattack_requester=(
                            "requester@gmail.com"
                        ),
                        unreliable_last_requested_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:11+00:00")
                        ),
                        unreliable_source=Source.ASM,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2018-04-08T00:43:11+00:00"
                        ),
                    ),
                    technique=VulnerabilityTechnique.MPT,
                    verification=VulnerabilityVerification(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:11+00:00"
                        ),
                        status=VulnerabilityVerificationStatus.REQUESTED,
                    ),
                ),
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2018-04-08T00:44:11+00:00"
                    ),
                    finding_id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="be09edb7-cd5c-47ed-bee4-97c645acdce9",
                    root_id="bb90e4a1-9e24-4d1b-af48-24fb5f09dc71",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="4545",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where="192.168.1.45",
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.PORTS,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_last_reattack_requester=(
                            "requester@gmail.com"
                        ),
                        unreliable_last_requested_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:11+00:00")
                        ),
                        unreliable_source=Source.ASM,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                    ),
                    technique=VulnerabilityTechnique.MPT,
                    verification=VulnerabilityVerification(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:11+00:00"
                        ),
                        status=VulnerabilityVerificationStatus.REQUESTED,
                    ),
                ),
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-04-08T00:44:11+00:00"
                    ),
                    finding_id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="be7cee90-d045-4b09-a1e0-287082340ebf",
                    root_id="bb90e4a1-9e24-4d1b-af48-24fb5f09dc71",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="4848",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where="192.168.1.45",
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.PORTS,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_efficacy=Decimal("0"),
                        unreliable_last_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:12+00:00")
                        ),
                        unreliable_last_reattack_requester=(
                            "requester@gmail.com"
                        ),
                        unreliable_last_requested_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:11+00:00")
                        ),
                        unreliable_source=Source.ASM,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                    ),
                    technique=VulnerabilityTechnique.MPT,
                    verification=VulnerabilityVerification(
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T01:45:12+00:00"
                        ),
                        status=VulnerabilityVerificationStatus.VERIFIED,
                    ),
                ),
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-04-08T00:44:11+00:00"
                    ),
                    finding_id="333d9984-17b0-434a-a8e0-a464c74f0212",
                    group_name="group1234",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="7948a0d8-a4a4-43e2-97ad-63593c385bdf",
                    root_id="ad63c994-cd29-4b31-a21f-60306e2a3e56",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="input:list:url",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where=(
                            "https://test.test/GetList?="
                            "1234&amp;page=1&amp;start=56789"
                        ),
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.INPUTS,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_source=Source.ASM,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                    ),
                    technique=VulnerabilityTechnique.MPT,
                ),
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2018-04-08T00:45:11+00:00"
                    ),
                    finding_id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="be09edb7-cd5c-47ed-bee4-97c645acdcea",
                    root_id="f54c209e-45e8-4960-9aa5-bb9c34987e09",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:45:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="4646",
                        status=VulnerabilityStateStatus.SAFE,
                        where="192.168.1.46",
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:45:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.PORTS,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_efficacy=Decimal("0"),
                        unreliable_last_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:12+00:00")
                        ),
                        unreliable_last_reattack_requester=(
                            "requester@gmail.com"
                        ),
                        unreliable_last_requested_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:11+00:00")
                        ),
                        unreliable_source=Source.ASM,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2018-04-08T00:45:11+00:00"
                        ),
                    ),
                    technique=VulnerabilityTechnique.MPT,
                    verification=VulnerabilityVerification(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:12+00:00"
                        ),
                        status=VulnerabilityVerificationStatus.VERIFIED,
                    ),
                ),
                "historic_state": [
                    VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:45:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="4646",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where="192.168.1.46",
                    ),
                    VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:12+00:00"
                        ),
                        specific="4646",
                        source=Source.ASM,
                        status=VulnerabilityStateStatus.SAFE,
                        where="192.168.1.46",
                    ),
                ],
                "historic_verification": [
                    VulnerabilityVerification(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:11+00:00"
                        ),
                        status=VulnerabilityVerificationStatus.REQUESTED,
                    ),
                    VulnerabilityVerification(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T01:45:12+00:00"
                        ),
                        status=VulnerabilityVerificationStatus.VERIFIED,
                    ),
                ],
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2020-04-08T00:44:11+00:00"
                    ),
                    finding_id="333d9984-17b0-434a-a8e0-a464c74f0212",
                    group_name="group1234",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="3d27dd6d-382c-4e93-bfd3-80b2e47863b6",
                    root_id="ad63c994-cd29-4b31-a21f-60306e2a3e56",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        source=Source.ASM,
                        specific="input:list:user",
                        status=VulnerabilityStateStatus.REJECTED,
                        where=(
                            "https://test.test/GetList?="
                            "1234&amp;page=1&amp;start=56789"
                        ),
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.INPUTS,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_source=Source.ASM,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                    ),
                    technique=VulnerabilityTechnique.MPT,
                ),
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2018-04-08T00:44:11+00:00"
                    ),
                    finding_id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="be09edb7-cd5c-47ed-bee4-97c645acdceb",
                    root_id="715f2498-bb07-41a4-99bd-61bd008fa903",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                        source=Source.MACHINE,
                        specific="4747",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where="192.168.1.47",
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.PORTS,
                    technique=VulnerabilityTechnique.DAST,
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_last_reattack_requester=(
                            "requester@gmail.com"
                        ),
                        unreliable_last_requested_reattack_date=(
                            datetime.fromisoformat("2018-04-08T01:45:11+00:00")
                        ),
                        unreliable_source=Source.MACHINE,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                    ),
                ),
            },
            {
                "vulnerability": Vulnerability(
                    created_by="hacker@gmail.com",
                    created_date=datetime.fromisoformat(
                        "2019-04-08T00:44:11+00:00"
                    ),
                    finding_id="3c475384-834c-47b0-ac71-a41a022e401c",
                    group_name="group1",
                    organization_name="orgtest",
                    hacker_email="hacker@gmail.com",
                    id="05cecba1-aa78-44c8-b040-8dca05bca556",
                    root_id="30c85c00-d2ab-43f4-b75e-7ae27928c8a4",
                    state=VulnerabilityState(
                        modified_by="hacker@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2019-04-08T00:44:11+00:00"
                        ),
                        source=Source.MACHINE,
                        specific="8081",
                        status=VulnerabilityStateStatus.VULNERABLE,
                        where="192.168.1.57",
                    ),
                    treatment=VulnerabilityTreatment(
                        modified_date=datetime.fromisoformat(
                            "2019-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityTreatmentStatus.UNTREATED,
                    ),
                    type=VulnerabilityType.PORTS,
                    technique=VulnerabilityTechnique.DAST,
                    zero_risk=VulnerabilityZeroRisk(
                        comment_id="54545454",
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-04-08T00:44:11+00:00"
                        ),
                        status=VulnerabilityZeroRiskStatus.CONFIRMED,
                    ),
                    unreliable_indicators=VulnerabilityUnreliableIndicators(
                        unreliable_source=Source.MACHINE,
                        unreliable_treatment_changes=0,
                        unreliable_report_date=datetime.fromisoformat(
                            "2018-04-08T00:44:11+00:00"
                        ),
                    ),
                ),
            },
        ],
        "organization_finding_policies": (
            OrgFindingPolicy(
                organization_name="orgtest",
                id="92551721-c8da-4452-b9a0-00b2a784f8e4",
                name="001. SQL injection - C Sharp SQL API",
                tags=set(),
                state=OrgFindingPolicyState(
                    modified_by="user_manager@gmail.com",
                    modified_date=datetime.fromisoformat(
                        "2021-01-19T11:11:10+00:00"
                    ),
                    status=PolicyStateStatus.SUBMITTED,
                ),
            ),
        ),
    }
    generic_data["db_data"]["policies"].extend(
        [
            {
                "level": "group",
                "subject": generic_data["global_vars"]["admin_email"],
                "object": "group123",
                "role": "admin",
            },
            {
                "level": "group",
                "subject": generic_data["global_vars"]["admin_email"],
                "object": "group1234",
                "role": "admin",
            },
        ]
    )
    generic_data["db_data"]["groups"].extend(
        [
            {
                "group": Group(
                    created_by="unknown",
                    created_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    description="-",
                    language=GroupLanguage.EN,
                    name="group123",
                    state=GroupState(
                        has_machine=False,
                        has_squad=False,
                        managed=GroupManaged["MANAGED"],
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-05-20T22:00:00+00:00"
                        ),
                        service=GroupService.WHITE,
                        status=GroupStateStatus.ACTIVE,
                        tier=GroupTier.FREE,
                        type=GroupSubscriptionType.CONTINUOUS,
                    ),
                    organization_id="40f6da5f-4f66-4bf0-825b-a2d9748ad6db",
                    sprint_start_date=datetime.fromisoformat(
                        "2022-06-06T00:00:00+00:00"
                    ),
                ),
            },
            {
                "group": Group(
                    created_by="unknown",
                    created_date=datetime.fromisoformat(
                        "2020-05-20T22:00:00+00:00"
                    ),
                    description="-",
                    language=GroupLanguage.EN,
                    name="group1234",
                    state=GroupState(
                        has_machine=True,
                        has_squad=True,
                        managed=GroupManaged["MANAGED"],
                        modified_by="admin@gmail.com",
                        modified_date=datetime.fromisoformat(
                            "2020-05-20T22:00:00+00:00"
                        ),
                        service=GroupService.WHITE,
                        status=GroupStateStatus.ACTIVE,
                        tier=GroupTier.FREE,
                        type=GroupSubscriptionType.CONTINUOUS,
                    ),
                    organization_id="40f6da5f-4f66-4bf0-825b-a2d9748ad6db",
                    sprint_start_date=datetime.fromisoformat(
                        "2022-06-06T00:00:00+00:00"
                    ),
                ),
            },
        ]
    )

    return await db.populate({**generic_data["db_data"], **data})
