---
aiohttp: 3.8.4
aiofiles: 23.1.0
aioextensions: 20.11.1621472
alive-progress: 1.6.1
bugsnag: 3.7.1
asyncclick: 8.1.3.4
anyio: 3.7.0
GitPython: 3.1.29
more-itertools: 8.10.0
mypy-extensions: 0.4.3
pathspec: 0.8.1
