apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: integrates-${CI_COMMIT_REF_NAME}
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: integrates-${CI_COMMIT_REF_NAME}
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
