apiVersion: v1
kind: Secret
metadata:
  name: integrates-${CI_COMMIT_REF_NAME}
  namespace: dev
type: Opaque
data:
  CACHIX_AUTH_TOKEN: ${B64_CACHIX_AUTH_TOKEN}
  CI_COMMIT_REF_NAME: ${B64_CI_COMMIT_REF_NAME}
  CI_COMMIT_SHA: ${B64_CI_COMMIT_SHA}
  GITLAB_USER_EMAIL: ${B64_GITLAB_USER_EMAIL}
