from context import (
    FI_MIXPANEL_API_SECRET,
    FI_MIXPANEL_API_TOKEN,
    FI_MIXPANEL_PROJECT_ID,
)

MIXPANEL_API_SECRET = FI_MIXPANEL_API_SECRET
MIXPANEL_API_TOKEN = FI_MIXPANEL_API_TOKEN
MIXPANEL_PROJECT_ID = FI_MIXPANEL_PROJECT_ID
