let securityHeaders = {
  "Content-Security-Policy":
    "script-src " +
    "'self' " +
    "'unsafe-inline' " +
    "fluidattacks.matomo.cloud " +
    "*.app-us1.com " +
    "*.cloudflareinsights.com " +
    "*.cookiebot.com " +
    "*.google-analytics.com " +
    "*.googletagmanager.com " +
    "*.hotjar.com " +
    "*.typekit.net " +
    "*.youtube.com " +
    "*.zoho.com " +
    "*.zohocdn.com " +
    "*.zohopublic.com " +
    "*.zohostatic.com " +
    "trackcmp.net " +
    "ajax.cloudflare.com " +
    "cdnjs.cloudflare.com/ajax/libs/highlight.js/ " +
    "connect.facebook.net/en_US/fbevents.js " +
    "connect.facebook.net/signals/config/ " +
    "googleads.g.doubleclick.net/pagead/viewthroughconversion/ " +
    "snap.licdn.com " +
    "static1.clutch.co/api/widget.js " +
    "widget.clutch.co/static/js/widget.js " +
    "www.googleadservices.com/pagead/ " +
    "https://cdn.logrocket.io " +
    "https://cdn.lr-ingest.io " +
    "https://cdn.lr-in.com " +
    "https://cdn.lr-in-prod.com " +
    "https://cdn.lr-ingest.com " +
    "https://*.smartlook.com " +
    "https://*.smartlook.cloud; " +
    "frame-ancestors " +
    "'self'; " +
    "object-src " +
    "'none'; " +
    "upgrade-insecure-requests;" +
    "worker-src " +
    "'self' " +
    "blob:;",
  "Strict-Transport-Security": "max-age=31536000",
  "X-Xss-Protection": "0",
  "X-Content-Type-Options": "nosniff",
  "X-Permitted-Cross-Domain-Policies": "none",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy":
    "geolocation=(self), " +
    "midi=(self), " +
    "push=(self), " +
    "sync-xhr=(self), " +
    "microphone=(self), " +
    "camera=(self), " +
    "magnetometer=(self), " +
    "gyroscope=(self), " +
    "speaker=(self), " +
    "vibrate=(self), " +
    "fullscreen=(self), " +
    "payment=(self)",
};

let sanitiseHeaders = {};

let removeHeaders = ["Public-Key-Pins"];

const homeURL = "https://fluidattacks.com/";
const redirectMap = new Map([
  ["/products/defends/apache/desactivar-http-trace/", homeURL],
  ["/products/defends/java/prevenir-sqli/", homeURL],
  ["/products/defends/aspnet/verificar-tamano-extension/", homeURL],
  ["/products/defends/python/ofuscar-codigo-fuente/", homeURL],
  ["/products/rules/list/", homeURL],
  ["/products/defends/java/usar-hmac256/", homeURL],
  ["/products/defends/ios/remover-servicios-inseguros/", homeURL],
  ["/products/defends/java/detener-hilos/", homeURL],
  ["/products/rules/", homeURL],
  ["/products/defends/html/deshabilitar-cache-app-web/", homeURL],
  ["/products/defends/csharp/evitar-direct-transversal/", homeURL],
  ["/products/defends/java/prevenir-xss-esapi/", homeURL],
  ["/products/defends/java/registrar-bitacora/", homeURL],
  ["/products/integrates/", homeURL],
  ["/products/defends/sql-server/cambiar-puerto-default/", homeURL],
  ["/security/", homeURL],
  ["/style/", homeURL],
  ["/products/defends/java/controlar-tamano-archivo/", homeURL],
  ["/products/defends/java/definir-rol-seguridad-tomcat/", homeURL],
  ["/products/defends/java/evitar-codigo-duplicado/", homeURL],
  ["/products/defends/java/manejar-sesion-jsp/", homeURL],
  ["/about-us/certifications/devsecops/", homeURL],
  ["/products/rules/list/029/", homeURL],
  ["/products/defends/linux/limitar-sesiones-concurrente/", homeURL],
  ["/products/defends/java/prevenir-csrf-taglibs/", homeURL],
  ["/products/defends/aspnet/firmar-datos-rsa-sha256/", homeURL],
  ["/products/defends/java/evitar-inyeccion-ldap/", homeURL],
  ["/products/defends/oracle/cambiar-puerto-default/", homeURL],
  ["/products/asserts/", homeURL],
  ["/products/defends/wordpress/evitar-fuerza-bruta/", homeURL],
  ["/products/defends/java/codificar-base64/", homeURL],
  ["/products/defends/cobol/generar-numeros-aleatorios/", homeURL],
  ["/products/rules/findings/", homeURL],
  ["/products/defends/javascript/ofuscar-codigo/", homeURL],
  ["/products/defends/cobol/validar-datos-variables/", homeURL],
  ["/products/defends/java/configurar-tiempo-sesion/", homeURL],
  ["/products/defends/php/cifrar-contrasenas-salt/", homeURL],
  ["/products/defends/csharp/quitar-metadatos-imgs/", homeURL],
  ["/format/", homeURL],
  ["/products/defends/java/prevenir-hpp/", homeURL],
  ["/products/defends/csharp/aplicar-seguridad-codigo/", homeURL],
  ["/products/defends/java/prevenir-ataque-csrf/", homeURL],
  ["/products/defends/web/establecer-cabecera-seguridad/", homeURL],
  ["/products/defends/java/prevenir-ataque-xss/", homeURL],
  ["/resources/doc/asserts/", homeURL],
  ["/products/rules/list/337/", homeURL],
  ["/products/defends/java/generar-id-aleatorio/", homeURL],
  ["/products/defends/java/filtrar-entrada-datos-regex/", homeURL],
  ["/products/defends/websphere/evitar-atq-repeticion/", homeURL],
  ["/products/defends/csharp/filtrar-entradas-regex/", homeURL],
  ["/products/defends/java/evitar-inyeccion-xpath/", homeURL],
  ["/products/defends/java/desactivar-xxe/", homeURL],
  ["/products/defends/aspnet/evitar-sesion-concurrente/", homeURL],
  ["/products/defends/objective-c/definir-opc-seguras/", homeURL],
  ["/products/defends/aspnet/validar-email/", homeURL],
  ["/products/rules/list/181/", homeURL],
  ["/techniques/ptaas/", homeURL],
  ["/products/skims/", homeURL],
  ["/products/defends/java/generar-salt-seguro/", homeURL],
  ["/products/defends/programacion/manejar-bitacoras/", homeURL],
  ["/products/defends/java/firmar-archivo-jar/", homeURL],
  ["/products/defends/java/controlar-acceso-servlet/", homeURL],
  ["/products/rules/list/177/", homeURL],
  ["/products/defends/java/definir-charset-content-type/", homeURL],
  ["/products/defends/java/concatenar-cadena-caracter/", homeURL],
  ["/products/rules/list/173/", homeURL],
  ["/products/defends/java/prevenir-xss-apache-commons/", homeURL],
  ["/products/defends/csharp/esquema-autorizacion/", homeURL],
  ["/products/defends/java/desactivar-indexof-tomcat/", homeURL],
  ["/products/rules/list/224/", homeURL],
  ["/products/defends/java/configurar-gestor-seguridad/", homeURL],
  ["/products/defends/java/cifrar-simetricamente/", homeURL],
  ["/products/forces/install/", homeURL],
  ["/products/defends/windows-server/cambiar-usuarios/", homeURL],
  ["/products/defends/scala/obtener-rutas-canon/", homeURL],
  ["/products/rules/list/264/", homeURL],
  ["/products/defends/csharp/usar-cifrado-simetrico/", homeURL],
  ["/products/defends/java/validar-archivos-richfaces/", homeURL],
  ["/products/defends/weblogic/evitar-atq-repeticion/", homeURL],
  ["/blog/index2.html", homeURL],
  ["/products/defends/yii/prevenir-sqli/", homeURL],
  ["/products/devsecops/install/", homeURL],
  ["/web/contact-us/", homeURL],
  ["/products/defends/java/establecer-control-acceso-url/", homeURL],
  ["/products/defends/java/habilitar-httponly/", homeURL],
  ["/products/rules/list/336/", homeURL],
  ["/products/rules/findings/048/", homeURL],
  ["/products/rules/findings/043/", homeURL],
  ["/products/defends/java/obtener-rutas-canon/", homeURL],
  ["/products/rules/list/126/", homeURL],
  ["/products/defends/", homeURL],
  ["/products/defends/java/ofuscar-aplicacion/", homeURL],
  ["/products/defends/apache/habilitar-headers-seguridad/", homeURL],
  ["/products/defends/php/filtrar-entradas-regex/", homeURL],
  ["/resources/doc/asserts/qstart/", homeURL],
  ["/products/defends/pl-sql/evitar-sqli/", homeURL],
  ["/products/defends/java/cifrar-flujo-datos/", homeURL],
  ["/products/defends/java/cifrar-usando-aes/", homeURL],
  ["/products/rules/list/341/", homeURL],
  ["/products/rules/list/342/", homeURL],
  ["/products/defends/aspnet/cifrar-contrasenas-con-salt/", homeURL],
  ["/products/rules/list/349/", homeURL],
  ["/products/defends/aspnet/generar-identificador-unico/", homeURL],
  ["/products/", homeURL],
  ["/products/defends/aspnet/definir-autenticacion-web/", homeURL],
  ["/products/rules/list/327/", homeURL],
  ["/products/defends/aspnet/prevenir-ataque-xss/", homeURL],
  ["/products/rules/list/062/", homeURL],
  ["/products/defends/rpg/usar-condicionales/", homeURL],
  ["/blog/tags/osce/index2.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.http/", homeURL],
  ["/products/defends/weblogic/cambiar-dir-admin/", homeURL],
  ["/products/defends/java/autenticar-app-opensaml/", homeURL],
  ["/products/rules/list/320/", homeURL],
  ["/about-us/partners/arroyo-consulting/", homeURL],
  ["/products/defends/rpg/evitar-sqli/", homeURL],
  ["/products/defends/java/utilizar-concurrencia-ejb/", homeURL],
  ["/products/rules/list/155/", homeURL],
  ["/products/rules/list/156/", homeURL],
  ["/products/defends/javascript/implementar-condicional/", homeURL],
  ["/products/rules/list/116/", homeURL],
  ["/products/defends/cobol/manejar-errores-aritmeticos/", homeURL],
  ["/products/defends/java/listar-criptografico/", homeURL],
  ["/products/defends/aspnet/proteger-cadenas-conexion/", homeURL],
  ["/products/rules/list/172/", homeURL],
  ["/products/rules/list/041/", homeURL],
  ["/products/rules/list/134/", homeURL],
  ["/products/rules/list/357/", homeURL],
  ["/products/defends/java/usar-privilegio/", homeURL],
  ["/products/defends/apache/configurar-soporte-https/", homeURL],
  ["/products/defends/aspnet/establecer-autenticacion/", homeURL],
  ["/products/forces/", homeURL],
  ["/products/rules/findings/022/", homeURL],
  ["/products/rules/list/145/", homeURL],
  ["/products/rules/list/321/", homeURL],
  ["/products/defends/java/generar-sha2/", homeURL],
  ["/products/rules/findings/060/", homeURL],
  ["/products/rules/list/238/", homeURL],
  ["/products/rules/list/324/", homeURL],
  ["/products/rules/list/326/", homeURL],
  ["/products/defends/java/usar-ejb-time-service/", homeURL],
  ["/products/defends/java/personalizar-error/", homeURL],
  ["/products/rules/list/075/", homeURL],
  ["/products/defends/cobol/registrar-excepciones-ile/", homeURL],
  ["/products/rules/list/332/", homeURL],
  ["/about-us/partners/", homeURL],
  ["/products/defends/aspnet/cifrar-contrasenas-una-via/", homeURL],
  ["/products/rules/findings/044/", homeURL],
  ["/products/rules/list/340/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.fsx/", homeURL],
  ["/products/rules/list/039/", homeURL],
  ["/products/defends/cobol/usar-condicionales/", homeURL],
  ["/products/rules/list/346/", homeURL],
  ["/products/rules/list/347/", homeURL],
  ["/faq/list/", homeURL],
  ["/products/rules/list/348/", homeURL],
  ["/products/defends/aspnet/comprender-programacion/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.iam/",
    homeURL,
  ],
  ["/products/defends/apache/restringir-banner/", homeURL],
  ["/products/rules/list/046/", homeURL],
  ["/products/rules/list/135/", homeURL],
  ["/products/rules/findings/076/", homeURL],
  ["/products/rules/list/355/", homeURL],
  ["/products/defends/cobol/cifrar-codigo-fuente/", homeURL],
  ["/products/rules/list/329/", homeURL],
  ["/products/defends/rpg/inicializar-variables/", homeURL],
  ["/products/rules/findings/028/", homeURL],
  ["/products/defends/aspnet/evitar-divulgacion-banner/", homeURL],
  ["/products/defends/aspnet/evitar-codigo-duplicado/", homeURL],
  ["/products/rules/list/142/", homeURL],
  ["/products/rules/list/363/", homeURL],
  ["/products/defends/hacking/evitar-ataque-dos/", homeURL],
  ["/products/rules/findings/064/", homeURL],
  ["/products/defends/aspnet/prevenir-ataque-csrf/", homeURL],
  ["/products/defends/aspnet/deshabilitar-depuracion/", homeURL],
  ["/products/defends/java/autenticar-servidor-cliente/", homeURL],
  ["/products/rules/list/237/", homeURL],
  ["/products/rules/list/325/", homeURL],
  ["/products/defends/consultoria/conocer-reg-sgsi/", homeURL],
  ["/products/rules/list/072/", homeURL],
  ["/products/rules/findings/102/", homeURL],
  ["/products/rules/list/161/", homeURL],
  ["/products/defends/csharp/proteger-aplicacion-xss/", homeURL],
  ["/products/rules/list/078/", homeURL],
  ["/products/rules/list/079/", homeURL],
  ["/products/defends/java/liberar-recursos/", homeURL],
  ["/products/rules/list/023/", homeURL],
  ["/products/rules/list/025/", homeURL],
  ["/products/rules/list/028/", homeURL],
  ["/products/rules/list/333/", homeURL],
  ["/products/defends/html/validar-formulario/", homeURL],
  ["/products/rules/list/334/", homeURL],
  ["/products/rules/findings/093/", homeURL],
  ["/resources/doc/skims/lib_path/common.html", homeURL],
  ["/about-us/security/", homeURL],
  ["/products/rules/list/338/", homeURL],
  ["/blog/authors/felipe-ruiz/index2.html", homeURL],
  ["/products/rules/list/088/", homeURL],
  ["/techniques/sast/", homeURL],
  ["/products/rules/list/176/", homeURL],
  ["/products/defends/aspnet/limitar-tiempo-sesion/", homeURL],
  ["/products/rules/findings/086/", homeURL],
  ["/products/rules/list/302/", homeURL],
  ["/products/rules/list/319/", homeURL],
  ["/products/rules/list/out-of-scope/", homeURL],
  ["/products/defends/java/definir-control-clases/", homeURL],
  ["/products/rules/list/051/", homeURL],
  ["/products/defends/tal/usar-condicionales/", homeURL],
  ["/products/rules/list/186/", homeURL],
  ["/products/defends/web/manejar-sesion-usuario/", homeURL],
  ["/products/rules/list/262/", homeURL],
  ["/products/rules/list/178/", homeURL],
  ["/products/rules/list/265/", homeURL],
  ["/products/rules/list/132/", homeURL],
  ["/products/rules/list/351/", homeURL],
  ["/products/rules/list/353/", homeURL],
  ["/products/rules/list/137/", homeURL],
  ["/products/rules/list/356/", homeURL],
  ["/products/rules/list/358/", homeURL],
  ["/products/defends/aix/restringir-rootdir-proceso/", homeURL],
  ["/products/rules/list/226/", homeURL],
  ["/products/rules/list/227/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.cloudtrail/", homeURL],
  ["/products/defends/java/remover-metadatos/", homeURL],
  ["/products/rules/list/328/", homeURL],
  ["/products/defends/aix/limitar-tiempo-sesion/", homeURL],
  ["/blog/authors/felipe-ruiz/index3.html", homeURL],
  ["/solutions/code-audit/", homeURL],
  ["/products/defends/csharp/validar-propietario-correo/", homeURL],
  ["/products/defends/aspnet/establecer-content-type/", homeURL],
  ["/products/rules/list/060/", homeURL],
  ["/products/rules/findings/114/", homeURL],
  ["/products/rules/findings/027/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.java/", homeURL],
  ["/products/rules/findings/110/", homeURL],
  ["/products/rules/list/150/", homeURL],
  ["/products/rules/findings/026/", homeURL],
  ["/products/rules/list/151/", homeURL],
  ["/products/defends/aspnet/ejecutar-min-privilegio/", homeURL],
  ["/products/rules/findings/024/", homeURL],
  ["/products/defends/java/validar-redirecciones/", homeURL],
  ["/products/rules/list/361/", homeURL],
  ["/products/defends/java/configurar-servlets/", homeURL],
  ["/products/rules/list/362/", homeURL],
  ["/products/rules/list/144/", homeURL],
  ["/products/rules/findings/068/", homeURL],
  ["/products/rules/findings/065/", homeURL],
  ["/products/defends/cifrado/solicitar-certificados-web/", homeURL],
  ["/products/rules/list/146/", homeURL],
  ["/products/defends/glassfish/configurar-bitacoras/", homeURL],
  ["/findings/077/", homeURL],
  ["/products/defends/rpg/liberar-recursos/", homeURL],
  ["/products/rules/list/149/", homeURL],
  ["/resources/doc/skims/integrates/index.html", homeURL],
  ["/products/defends/cobol/comprobar-contrasena-frase/", homeURL],
  ["/products/rules/list/236/", homeURL],
  ["/products/rules/list/322/", homeURL],
  ["/products/defends/java/establecer-politica-gui/", homeURL],
  ["/products/defends/cobol/prevenir-xss/", homeURL],
  ["/blog/index3.html", homeURL],
  ["/products/defends/php/manejar-excepciones/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.fsx/",
    homeURL,
  ],
  ["/products/defends/aspnet/registrar-eventos-bitacoras/", homeURL],
  ["/products/rules/findings/103/", homeURL],
  ["/products/defends/aspnet/evitar-codigo-muerto/", homeURL],
  ["/products/rules/findings/100/", homeURL],
  ["/products/defends/finacle/prevenir-sqli/", homeURL],
  ["/products/rules/findings/011/", homeURL],
  ["/products/rules/list/031/", homeURL],
  ["/about-us/partners/ediligence/", homeURL],
  ["/blog/index5.html", homeURL],
  ["/products/rules/list/157/", homeURL],
  ["/products/defends/java/importar-certificado-digital/", homeURL],
  ["/products/rules/list/242/", homeURL],
  ["/products/rules/findings/054/", homeURL],
  ["/products/rules/list/158/", homeURL],
  ["/about-us/partners/greensqa/", homeURL],
  ["/products/rules/list/159/", homeURL],
  ["/products/defends/java/validar-jcaptcha/", homeURL],
  ["/products/rules/list/330/", homeURL],
  ["/products/rules/list/027/", homeURL],
  ["/products/rules/findings/052/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.html/", homeURL],
  ["/products/rules/list/114/", homeURL],
  ["/blog/index12.html", homeURL],
  ["/products/defends/java/evitar-codigo-muerto/", homeURL],
  ["/products/rules/list/115/", homeURL],
  ["/products/rules/list/118/", homeURL],
  ["/products/rules/list/119/", homeURL],
  ["/products/defends/cobol/establecer-sent-seguras/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.ssh/", homeURL],
  ["/products/defends/aspnet/prevenir-pagina-cache/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.services/",
    homeURL,
  ],
  ["/products/rules/findings/007/", homeURL],
  ["/products/rules/list/083/", homeURL],
  ["/products/rules/list/084/", homeURL],
  ["/products/rules/list/171/", homeURL],
  ["/findings/045/", homeURL],
  ["/products/rules/list/040/", homeURL],
  ["/resources/doc/skims/aws/iam/index.html", homeURL],
  ["/products/defends/cobol/enmascarar-texto/", homeURL],
  ["/products/rules/list/261/", homeURL],
  ["/products/rules/list/043/", homeURL],
  ["/resources/doc/skims/state/index.html", homeURL],
  ["/products/defends/aspnet/configurar-credenciales/", homeURL],
  ["/rules/185/", homeURL],
  ["/products/rules/list/033/", homeURL],
  ["/products/defends/java/personalizar-eventos/", homeURL],
  ["/products/defends/aspnet/establecer-pagina-error/", homeURL],
  ["/techniques/sca/", homeURL],
  ["/products/rules/list/169/", homeURL],
  ["/products/rules/list/122/", homeURL],
  ["/products/rules/list/037/", homeURL],
  ["/rules/236/", homeURL],
  ["/products/defends/java/analizar-bytecode/", homeURL],
  ["/products/rules/list/344/", homeURL],
  ["/products/rules/list/259/", homeURL],
  ["/products/defends/cobol/compilar-programa-estricta/", homeURL],
  ["/products/defends/glassfish/deshabilitar-depuracion/", homeURL],
  ["/products/rules/list/127/", homeURL],
  ["/products/defends/cobol/generar-llaves/", homeURL],
  ["/web/defends/sql-server/cambiar-puerto-default/", homeURL],
  ["/blog/categories/machine-learning/index2.html", homeURL],
  ["/products/defends/suse/eliminar-metadatos/", homeURL],
  ["/products/defends/csharp/liberar-recursos/", homeURL],
  ["/products/defends/windows/brindar-acceso-recursos/", homeURL],
  ["/products/rules/list/091/", homeURL],
  ["/defends/aspnet/realizar-peticiones-https/src/secure-request.cs", homeURL],
  ["/products/rules/list/093/", homeURL],
  ["/blog/index4.html", homeURL],
  ["/products/defends/aspnet/validar-redirecciones/", homeURL],
  ["/products/defends/aspnet/cifrar-credenciales/", homeURL],
  ["/products/rules/list/050/", homeURL],
  ["/products/rules/list/183/", homeURL],
  ["/products/defends/java/crear-contenedores-no-sync/", homeURL],
  ["/products/rules/list/185/", homeURL],
  ["/products/defends/aspnet/prevenir-sqli/", homeURL],
  ["/products/rules/findings/035/", homeURL],
  ["/products/rules/list/045/", homeURL],
  ["/products/rules/findings/034/", homeURL],
  ["/products/defends/java/comprobar-identidad-servlets/", homeURL],
  ["/products/rules/list/131/", homeURL],
  ["/products/rules/findings/031/", homeURL],
  ["/products/rules/findings/079/", homeURL],
  ["/products/rules/list/350/", homeURL],
  ["/products/defends/windows/deshabilitar-puertos/", homeURL],
  ["/findings/060/", homeURL],
  ["/products/rules/list/266/", homeURL],
  ["/products/rules/list/001/", homeURL],
  ["/products/rules/findings/030/", homeURL],
  ["/prine/", homeURL],
  ["/blog/secdevops-campeones-seguridad/", homeURL],
  ["/products/rules/list/223/", homeURL],
  ["/products/defends/programacion/crear-bitacoras-cond/", homeURL],
  ["/products/rules/list/310/", homeURL],
  ["/products/rules/findings/072/", homeURL],
  ["/products/rules/list/359/", homeURL],
  ["/about/security/", homeURL],
  ["/services/continuous-hacking/healthcheck/", homeURL],
  ["/web/security/", homeURL],
  ["/products/defends/java/firmar-objeto/src/cli.java", homeURL],
  ["/blog/index7.html", homeURL],
  ["/about-us/partners/rsec/", homeURL],
  ["/products/rules/list/109/", homeURL],
  ["/products/defends/csharp/prevenir-sqli/", homeURL],
  ["/resources/doc/asserts/fluidasserts.utils.generic/", homeURL],
  ["/asserts/fluidasserts.cloud.aws.ecs/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.cloudwatch/", homeURL],
  ["/findings/026/", homeURL],
  ["/resources/doc/skims/utils/image.html", homeURL],
  ["/about-us/certifications/comptiasecurity/", homeURL],
  ["/asserts/fluidasserts.format.file/", homeURL],
  ["/resources/doc/skims/lib_path/f085.html", homeURL],
  ["/web/defends/html/deshabilitar-cache-app-web/", homeURL],
  ["/findings/029/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation/", homeURL],
  ["/products/defends/scala/limitar-vida-variable/", homeURL],
  ["/findings/113/", homeURL],
  ["/products/defends/aspnet/definir-criptografia/", homeURL],
  ["/products/defends/cobol/liberar-recursos/", homeURL],
  ["/products/rules/findings/118/", homeURL],
  ["/resources/doc/skims/lib_path/f060.html", homeURL],
  ["/products/defends/java/generar-aleatorio-seguro/", homeURL],
  ["/blog/authors/rafael-ballestas/index2.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.csharp/", homeURL],
  ["/products/rules/findings/119/", homeURL],
  ["/products/defends/csharp/ejecutar-minimo-privilegio/", homeURL],
  ["/products/defends/java/registrar-formateado/", homeURL],
  ["/blog/tags/security/index6.html", homeURL],
  ["/products/rules/findings/116/", homeURL],
  ["/products/rules/findings/029/", homeURL],
  ["/products/rules/list/191/", homeURL],
  ["/about-us/partners/cgsi/", homeURL],
  ["/resources/doc/skims/utils/hardware.html", homeURL],
  ["/products/rules/findings/115/", homeURL],
  ["/products/rules/list/061/", homeURL],
  ["/products/rules/list/194/", homeURL],
  ["/resources/doc/skims/utils/function.html", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.azure.network_security_groups/",
    homeURL,
  ],
  [
    "/resources/doc/asserts/fluidasserts.cloud.azure.storage_accounts/",
    homeURL,
  ],
  ["/resources/doc/asserts/fluidasserts.cloud.kubernetes.pods/", homeURL],
  ["/resources/doc/skims/parse_hcl2/structure.html", homeURL],
  ["/products/rules/list/280/", homeURL],
  ["/products/defends/aspnet/proteger-viewstate/", homeURL],
  ["/products/defends/aspnet/establecer-opciones-seguras/", homeURL],
  ["/products/rules/findings/113/", homeURL],
  ["/products/rules/list/063/", homeURL],
  ["/rules/072/", homeURL],
  ["/products/defends/csharp/depurar-programas/", homeURL],
  ["/products/defends/aspnet/configurar-charset-http/", homeURL],
  ["/resources/doc/skims/parse_cfn/loader.html", homeURL],
  ["/products/defends/windows/bloquear-temporalmente/", homeURL],
  ["/resources/doc/skims/core/persist/index.html", homeURL],
  ["/products/defends/java/establecer-opciones-seguras/", homeURL],
  ["/products/defends/java/usar-procedimientos/", homeURL],
  ["/blog/tags/cybersecurity/index2.html", homeURL],
  ["/products/rules/findings/025/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.cloudtrail/",
    homeURL,
  ],
  ["/products/rules/findings/111/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.eks/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.s3/", homeURL],
  ["/findings/022/", homeURL],
  ["/resources/doc/skims/state/common.html", homeURL],
  ["/products/defends/aspnet/definir-autenticacion/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.configservice/", homeURL],
  ["/products/rules/list/284/", homeURL],
  ["/products/rules/list/066/", homeURL],
  ["/products/rules/list/199/", homeURL],
  ["/products/rules/findings/023/", homeURL],
  ["/products/defends/rpg/manejar-bitacoras/", homeURL],
  ["/findings/025/", homeURL],
  ["/web/defends/cobol/generar-numeros-aleatorios/", homeURL],
  ["/techniques/iast/", homeURL],
  ["/products/defends/redhat/proteger-fuerza-bruta/", homeURL],
  ["/solutions/apis/", homeURL],
  ["/blog/tags/training/index2.html", homeURL],
  ["/products/rules/list/141/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.azure.sqlserver/", homeURL],
  ["/products/rules/findings/021/", homeURL],
  ["/products/rules/list/189/", homeURL],
  ["/products/rules/findings/069/", homeURL],
  ["/blog/authors/julian-arango/index2.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.syst.linux/", homeURL],
  ["/products/rules/list/360/", homeURL],
  ["/web/defends/java/manejar-sesion-jsp/", homeURL],
  ["/rules/167/", homeURL],
  ["/resources/doc/skims/parse_antlr/index.html", homeURL],
  ["/findings/070/", homeURL],
  ["/blog/index13.html", homeURL],
  ["/products/defends/csharp/evitar-codigo-duplicado/", homeURL],
  ["/blog/tags/vulnerability/index2.html", homeURL],
  ["/products/rules/list/143/", homeURL],
  ["/products/rules/list/058/", homeURL],
  ["/products/rules/findings/067/", homeURL],
  ["/products/defends/aspnet/establecer-variables-sesion/", homeURL],
  ["/blog/index9.html", homeURL],
  ["/products/rules/findings/020/", homeURL],
  ["/blog/tags/information/index2.html", homeURL],
  ["/products/defends/java/definir-charset-jsp/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.iam/", homeURL],
  ["/rules/122/", homeURL],
  ["/rules/255/", homeURL],
  ["/products/defends/aspnet/implementar-cifrado/", homeURL],
  ["/blog/tags/cybersecurity/index4.html", homeURL],
  ["/products/rules/list/231/", homeURL],
  ["/products/defends/aspnet/usar-cookies-httponly/", homeURL],
  ["/road-to-functional-python/", homeURL],
  ["/rules/123/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.cloudfront/",
    homeURL,
  ],
  ["/products/defends/aix/conocer-privilegios-rbac/", homeURL],
  ["/products/rules/list/232/", homeURL],
  ["/products/rules/list/147/", homeURL],
  ["/products/defends/java/manejar-excepciones/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.docker/", homeURL],
  ["/products/rules/findings/063/", homeURL],
  ["/resources/doc/asserts/dev/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.secretsmanager/", homeURL],
  ["/products/rules/list/100/", homeURL],
  ["/products/rules/list/148/", homeURL],
  ["/rules/121/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.efs/", homeURL],
  ["/findings/076/", homeURL],
  ["/products/defends/sharepoint/configurar-bitacoras/", homeURL],
  ["/blog/index10.html", homeURL],
  ["/products/rules/list/101/", homeURL],
  ["/products/rules/list/016/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.rds/",
    homeURL,
  ],
  ["/products/defends/java/ubicar-codigo-fuente/src/cli.java", homeURL],
  ["/resources/doc/skims/parse_hcl2/index.html", homeURL],
  ["/blog/tags/business/index3.html", homeURL],
  ["/products/rules/list/234/", homeURL],
  ["/products/defends/csharp/establecer-content-type/", homeURL],
  ["/products/rules/list/235/", homeURL],
  ["/products/defends/cobol/eliminar-codigo-repetido/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.cookie/", homeURL],
  ["/products/rules/findings/062/", homeURL],
  ["/products/defends/java/implementar-control-acceso/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.bower/", homeURL],
  ["/products/defends/java/transmitir-https/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.s3/", homeURL],
  ["/blog/tags/code/index2.html", homeURL],
  ["/products/rules/list/323/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.ldap/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.linux/", homeURL],
  ["/products/defends/java/firmar-objeto/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.ec2/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.azure.security_center/", homeURL],
  ["/search.html?q=directive", homeURL],
  ["/about-us/partners/proximiteam/", homeURL],
  ["/products/defends/pl-sql/definir-opciones-defecto/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.ebs/", homeURL],
  ["/products/defends/java/almacenar-sesion-servlet/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.cloudfront/", homeURL],
  ["/defends/linux/remover-metadatos/", homeURL],
  ["/rules/348/", homeURL],
  ["/resources/doc/skims/zone/index.html", homeURL],
  ["/resources/doc/skims/utils/logs.html", homeURL],
  ["/resources/doc/skims/parse_babel/index.html", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.dynamodb/",
    homeURL,
  ],
  ["/products/rules/list/206/", homeURL],
  ["/products/rules/list/339/", homeURL],
  [
    "/products/defends/csharp/proteger-aplicacion-xss/src/default.aspx.cs",
    homeURL,
  ],
  ["/products/rules/list/207/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.route53/", homeURL],
  ["/products/rules/findings/108/", homeURL],
  ["/resources/doc/skims/lib_path/f047_aws.html", homeURL],
  ["/resources/doc/skims/utils/crypto.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.redshift/", homeURL],
  ["/products/rules/list/209/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.sqs/", homeURL],
  ["/rules/081/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.crypto/", homeURL],
  ["/products/defends/aspnet/proteger-seq-comando/", homeURL],
  ["/products/rules/findings/106/", homeURL],
  ["/resources/doc/skims/parse_hcl2/loader.html", homeURL],
  ["/resources/doc/asserts/reqs/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.fsx/", homeURL],
  ["/reversing-mortals/", homeURL],
  ["/products/rules/findings/107/", homeURL],
  ["/products/rules/findings/104/", homeURL],
  ["/products/rules/findings/019/", homeURL],
  ["/resources/doc/skims/lib_path/f001_jpa.html", homeURL],
  ["/rules/080/", homeURL],
  ["/products/rules/findings/105/", homeURL],
  ["/products/rules/list/070/", homeURL],
  ["/products/defends/php/establecer-opciones-seguras/", homeURL],
  ["/products/rules/findings/017/", homeURL],
  ["/resources/doc/skims/state/ephemeral.html", homeURL],
  ["/findings/031/", homeURL],
  ["/blog/tags/security/index2.html", homeURL],
  ["/services/continuous-hacking/vuln-manage/", homeURL],
  ["/products/rules/findings/018/", homeURL],
  ["/rules/086/", homeURL],
  ["/defends/rpg/evitar-sqli/", homeURL],
  ["/findings/078/", homeURL],
  ["/products/defends/yii/usar-recaptcha/", homeURL],
  ["/defends/java/mantener-conexiones-db/src/connectionpoolfsg.java", homeURL],
  ["/products/rules/findings/015/", homeURL],
  ["/resources/doc/skims/utils/model.html", homeURL],
  ["/about-us/partners/mainsoft/", homeURL],
  ["/products/rules/findings/101/", homeURL],
  ["/blog/tags/security/index4.html", homeURL],
  ["/products/rules/findings/013/", homeURL],
  ["/rules/174/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.loader/",
    homeURL,
  ],
  ["/products/defends/iis/negar-acceso-consola-admin/", homeURL],
  ["/findings/035/", homeURL],
  ["/products/defends/linux/remover-metadatos/", homeURL],
  ["/products/rules/list/162/", homeURL],
  ["/products/rules/list/077/", homeURL],
  ["/products/defends/java/purificar-html/", homeURL],
  ["/products/rules/findings/014/", homeURL],
  ["/rules/175/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.aws/", homeURL],
  ["/products/rules/list/030/", homeURL],
  ["/products/rules/list/296/", homeURL],
  ["/products/rules/findings/059/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.pypi/", homeURL],
  ["/products/defends/java/compilar-archivo/", homeURL],
  ["/products/rules/list/164/", homeURL],
  ["/products/defends/java/crear-permisos/", homeURL],
  ["/products/rules/list/297/", homeURL],
  ["/products/rules/list/153/", homeURL],
  ["/products/rules/list/020/", homeURL],
  ["/rules/178/", homeURL],
  ["/findings/083/", homeURL],
  ["/resources/doc/asserts/fluidasserts.db.mssql/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.elb2/",
    homeURL,
  ],
  ["/products/defends/aspnet/lineamientos-seguridad/", homeURL],
  ["/products/rules/findings/010/", homeURL],
  ["/products/rules/list/154/", homeURL],
  ["/products/rules/findings/058/", homeURL],
  ["/resources/doc/skims/lib_path/f037.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.ssl/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.dynamodb/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.elb/",
    homeURL,
  ],
  ["/products/rules/list/240/", homeURL],
  ["/resources/doc/asserts/genindex/", homeURL],
  ["/products/rules/findings/055/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.kms/",
    homeURL,
  ],
  ["/search.html?q=OWASP", homeURL],
  ["/products/rules/list/241/", homeURL],
  ["/products/rules/list/289/", homeURL],
  ["/resources/doc/skims/integrates/domain.html", homeURL],
  ["/products/rules/findings/056/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.kms/", homeURL],
  ["/blog/tags/application/index2.html", homeURL],
  ["/about-us/partners/novacomp/", homeURL],
  ["/products/defends/php/prevenir-sqli/", homeURL],
  ["/systems/networks/", homeURL],
  ["/search.html", homeURL],
  ["/products/rules/list/110/", homeURL],
  ["/products/defends/aspnet/evitar-sqli-parametrizacion/", homeURL],
  ["/rules/352/", homeURL],
  ["/products/rules/list/111/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.elasticache/", homeURL],
  ["/rules/132/", homeURL],
  ["/products/rules/list/026/", homeURL],
  ["/products/defends/scala/usar-opciones-seguras/", homeURL],
  ["/products/rules/findings/051/", homeURL],
  ["/resources/doc/skims/benchmark/index.html", homeURL],
  ["/blog/authors/jonathan-armas/index2.html", homeURL],
  ["/resources/doc/skims/nvd/local.html", homeURL],
  [
    "/products/defends/aspnet/evitar-sesion-concurrente/src/session-control.cs",
    homeURL,
  ],
  ["/resources/doc/skims/", homeURL],
  ["/rules/133/", homeURL],
  ["/resources/doc/skims/utils/fs.html", homeURL],
  ["/products/rules/list/331/", homeURL],
  ["/products/rules/findings/097/", homeURL],
  ["/products/rules/list/113/", homeURL],
  ["/blog/categories/attacks/index3.html", homeURL],
  ["/rules/006/", homeURL],
  ["/blog/index8.html", homeURL],
  ["/products/rules/findings/098/", homeURL],
  ["/products/rules/list/247/", homeURL],
  ["/products/rules/findings/050/", homeURL],
  ["/resources/doc/skims/lib_path/f034.html", homeURL],
  ["/resources/doc/skims/parse_hcl2/tokens.html", homeURL],
  ["/products/rules/list/200/", homeURL],
  ["/products/defends/csharp/limitar-vida-variable/", homeURL],
  ["/resources/doc/skims/utils/env.html", homeURL],
  ["/products/rules/list/248/", homeURL],
  ["/products/defends/csharp/limitar-vida-recurso/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.rpgle/", homeURL],
  ["/products/rules/list/201/", homeURL],
  ["/rules/222/", homeURL],
  ["/products/rules/list/249/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.banner/", homeURL],
  ["/products/rules/findings/096/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.terraform.dynamodb/",
    homeURL,
  ],
  ["/products/rules/list/335/", homeURL],
  ["/products/rules/list/117/", homeURL],
  ["/rules/313/", homeURL],
  ["/resources/doc/skims/utils/bugs.html", homeURL],
  ["/products/rules/list/203/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.ecs/", homeURL],
  ["/resources/doc/asserts/usage/", homeURL],
  ["/blog/tags/vulnerability/index4.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.ssh/", homeURL],
  ["/rules/314/", homeURL],
  ["/products/rules/list/204/", homeURL],
  ["/rules/008/", homeURL],
  ["/findings/081/", homeURL],
  ["/products/rules/findings/091/", homeURL],
  ["/resources/doc/skims/aws/iam/utils.html", homeURL],
  ["/rules/359/", homeURL],
  ["/web/defends/java/generar-cadena-segura/", homeURL],
  ["/products/rules/list/205/", homeURL],
  ["/rules/227/", homeURL],
  ["/products/defends/cobol/obtener-atributos/", homeURL],
  ["/blog/categories/attacks/index2.html", homeURL],
  ["/products/defends/windows/configurar-actualizaciones/", homeURL],
  ["/blog/tags/business/index4.html", homeURL],
  ["/products/rules/list/218/", homeURL],
  ["/resources/doc/skims/lib_path/f052.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.ssl/", homeURL],
  ["/products/rules/list/219/", homeURL],
  ["/products/rules/findings/090/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.string/", homeURL],
  ["/products/defends/windows/evitar-enumeracion-usuario/", homeURL],
  ["/products/rules/list/305/", homeURL],
  ["/resources/doc/asserts/fluidasserts.utils.cli/", homeURL],
  ["/blog/tags/machine-learning/index2.html", homeURL],
  ["/findings/004/", homeURL],
  ["/rules/093/", homeURL],
  ["/products/rules/findings/009/", homeURL],
  ["/resources/doc/skims/lib_path/f009.html", homeURL],
  ["/findings/007/", homeURL],
  ["/resources/doc/skims/utils/encodings.html", homeURL],
  ["/resources/doc/skims/lib_path/f055_aws.html", homeURL],
  ["/products/defends/java/crear-control-obligatorio/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.http/", homeURL],
  ["/products/defends/aspnet/presentar-error-seguro/", homeURL],
  ["/products/rules/list/080/", homeURL],
  ["/resources/doc/skims/config/index.html", homeURL],
  ["/products/defends/java/firmar-arreglo/", homeURL],
  ["/resources/doc/skims/utils/string.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.cognito/", homeURL],
  ["/blog/index14.html", homeURL],
  ["/products/rules/list/081/", homeURL],
  ["/products/rules/findings/008/", homeURL],
  ["/products/defends/java/identificar-clases-inseguras/", homeURL],
  ["/about-us/partners/choucair/", homeURL],
  ["/resources/doc/skims/lib_path/f011.html", homeURL],
  ["/products/defends/cobol/prevenir-sqli-sentencias/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.captcha/", homeURL],
  ["/products/defends/java/compilar-estrictamente/", homeURL],
  ["/products/rules/findings/005/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.sns/", homeURL],
  ["/products/defends/aspnet/implementar-esquemas-aut/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.generic/", homeURL],
  ["/products/defends/scala/validar-archivo-header/", homeURL],
  ["/products/rules/list/085/", homeURL],
  ["/resources/doc/asserts/ref/", homeURL],
  ["/findings/042/", homeURL],
  ["/products/rules/list/086/", homeURL],
  ["/products/defends/java/almacenar-sesion-filtro/", homeURL],
  ["/resources/doc/skims/core/index.html", homeURL],
  ["/products/rules/findings/004/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.python/", homeURL],
  ["/products/defends/java/controlar-tiempo/", homeURL],
  ["/resources/doc/asserts/credits/", homeURL],
  ["/products/defends/forense/recolectar-info-fisica/", homeURL],
  ["/asserts/fluidasserts.helper.proxy/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca/", homeURL],
  ["/products/rules/findings/049/", homeURL],
  ["/resources/doc/skims/parse_cfn/structure.html", homeURL],
  ["/resources/doc/skims/lib_path/f061.html", homeURL],
  ["/products/defends/php/comparar-strings/", homeURL],
  ["/products/rules/list/174/", homeURL],
  ["/resources/doc/skims/parse_json/index.html", homeURL],
  ["/products/rules/list/089/", homeURL],
  ["/products/defends/cobol/generar-cadenas-aleatorias/", homeURL],
  ["/resources/doc/skims/aws/utils.html", homeURL],
  ["/products/defends/aspnet/liberar-recursos/", homeURL],
  ["/products/defends/java/determinar-archivo-ext/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.dotnetconfig/", homeURL],
  ["/solutions/pentesting/", homeURL],
  ["/products/rules/list/260/", homeURL],
  ["/products/rules/list/175/", homeURL],
  ["/products/rules/list/042/", homeURL],
  ["/products/rules/findings/047/", homeURL],
  ["/products/defends/java/autenticar-app-opensaml/src/saml.java", homeURL],
  ["/findings/001/", homeURL],
  ["/findings/049/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.npm/", homeURL],
  ["/asserts/fluidasserts.cloud.aws/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.elb2/", homeURL],
  ["/products/defends/csharp/definir-opciones-seguras/", homeURL],
  ["/resources/doc/skims/parse_antlr/parse.html", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.terraform.cloudfront/",
    homeURL,
  ],
  ["/products/defends/aspnet/usar-recaptcha/", homeURL],
  ["/products/rules/list/032/", homeURL],
  ["/products/defends/java/limitar-vida-variable/", homeURL],
  ["/products/rules/findings/045/", homeURL],
  ["/about-us/certifications/iso27001/", homeURL],
  ["/resources/doc/skims/lib_path/f117.html", homeURL],
  ["/application-hacking/", homeURL],
  ["/products/rules/list/251/", homeURL],
  ["/products/defends/aspnet/registrar-eventos-web/", homeURL],
  ["/products/defends/scala/limitar-vida-recurso/", homeURL],
  ["/products/rules/findings/046/", homeURL],
  [
    "/products/defends/java/implementar-mod-autenticacion/src/countfiles.java",
    homeURL,
  ],
  ["/resources/doc/skims/cli/index.html", homeURL],
  ["/resources/doc/skims/aws/model.html", homeURL],
  ["/products/defends/cobol/evitar-msg-autenticacion/", homeURL],
  ["/products/rules/list/252/", homeURL],
  ["/products/rules/list/034/", homeURL],
  ["/products/defends/csharp/registrar-eventos/", homeURL],
  ["/products/rules/list/167/", homeURL],
  ["/rules/055/", homeURL],
  ["/products/defends/java/validar-jcaptcha/src/loginservlet.java", homeURL],
  ["/rules/273/", homeURL],
  ["/findings/097/", homeURL],
  ["/products/rules/list/253/", homeURL],
  ["/products/rules/list/035/", homeURL],
  ["/blog/categories/attacks/index4.html", homeURL],
  ["/resources/doc/skims/serialization/index.html", homeURL],
  ["/rules/189/", homeURL],
  ["/resources/doc/skims/parse_cfn/parse_yaml.html", homeURL],
  ["/products/drills/", homeURL],
  ["/products/defends/yii/validar-datos-entrada/", homeURL],
  ["/resources/doc/asserts/fluidasserts.syst.win/", homeURL],
  ["/products/rules/list/121/", homeURL],
  ["/products/rules/list/254/", homeURL],
  ["/products/defends/aix/activar-rbac-extendido/", homeURL],
  ["/products/rules/findings/041/", homeURL],
  ["/products/rules/list/255/", homeURL],
  ["/resources/doc/skims/parse_common/types.html", homeURL],
  ["/findings/050/", homeURL],
  ["/rules/148/", homeURL],
  [
    "/defends/java/comprobar-identidad-servlets/src/testremoteuserdata.java",
    homeURL,
  ],
  ["/defends/aspnet/realizar-peticiones-https/src/mypolicy.cs", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.lang/", homeURL],
  ["/products/defends/java/firmar-arreglo/src/cli.java", homeURL],
  ["/products/rules/findings/087/", homeURL],
  ["/products/rules/list/123/", homeURL],
  ["/resources/doc/skims/nvd/index.html", homeURL],
  ["/blog/authors/felipe-ruiz/index4.html", homeURL],
  ["/blog/tags/security/index5.html", homeURL],
  ["/resources/doc/skims/utils/graph.html", homeURL],
  ["/products/defends/csharp/evitar-msg-error/", homeURL],
  ["/products/rules/list/257/", homeURL],
  ["/products/rules/findings/040/", homeURL],
  ["/services/one-shot-hacking/reports/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.x509/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.kms/", homeURL],
  ["/products/rules/list/210/", homeURL],
  ["/products/rules/list/343/", homeURL],
  ["/products/rules/list/258/", homeURL],
  [
    "/products/defends/java/implementar-mod-autenticacion/src/simpleloginmodule.java",
    homeURL,
  ],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.elb/", homeURL],
  ["/blog/index6.html", homeURL],
  ["/products/rules/findings/085/", homeURL],
  ["/resources/doc/asserts/fluidasserts.db.postgresql/", homeURL],
  ["/blog/tags/exploit/index2.html", homeURL],
  ["/blog/tags/company/index2.html", homeURL],
  ["/blog/authors/mateo-gutierrez-gomez/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.pkcs12/", homeURL],
  ["/blog/tags/hacking/index3.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.db.mysql/", homeURL],
  ["/resources/doc/skims/utils/ctx.html", homeURL],
  ["/products/rules/list/345/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.chocolatey/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.sca/", homeURL],
  ["/products/devsecops/", homeURL],
  ["/resources/doc/skims/lib_path/f022.html", homeURL],
  ["/products/defends/windows-server/renombrar-usuarios/", homeURL],
  ["/techniques/asm/", homeURL],
  ["/rules/101/", homeURL],
  ["/about-us/partners/gamma-ingenieros/", homeURL],
  ["/products/rules/list/128/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.secretsmanager/",
    homeURL,
  ],
  ["/resources/doc/asserts/fluidasserts.proto.graphql/", homeURL],
  ["/products/rules/findings/084/", homeURL],
  ["/products/rules/list/214/", homeURL],
  ["/products/rules/list/129/", homeURL],
  ["/products/rules/findings/081/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.proxy/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.dns/", homeURL],
  ["/defends/cobol/manejar-error-texto/", homeURL],
  ["/products/rules/list/300/", homeURL],
  ["/blog/authors/rafael-ballestas/index3.html", homeURL],
  ["/techniques/dast/", homeURL],
  ["/products/defends/java/registrar-eventos-clases/", homeURL],
  ["/products/rules/list/301/", homeURL],
  ["/findings/093/", homeURL],
  ["/rules/105/", homeURL],
  ["/network-hacking/", homeURL],
  ["/products/defends/redhat/actualizar-software/", homeURL],
  [
    "/products/defends/aspnet/verificar-tamano-extension/src/example.cs",
    homeURL,
  ],
  ["/findings/091/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.winrm/", homeURL],
  ["/blog/tags/security/index3.html", homeURL],
  ["/products/rules/list/315/", homeURL],
  ["/blog/index11.html", homeURL],
  ["/services/continuous-hacking/critical-info/", homeURL],
  ["/products/defends/csharp/proteger-csrf-token/", homeURL],
  ["/findings/015/", homeURL],
  ["/resources/doc/skims/state/cache.html", homeURL],
  ["/about-us/partners/agt/", homeURL],
  ["/products/rules/list/316/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.azure.active_directory/",
    homeURL,
  ],
  ["/resources/doc/asserts/fluidasserts.format/", homeURL],
  ["/products/rules/list/317/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.php/", homeURL],
  ["/blog/blog/smishing/", homeURL],
  ["/products/defends/php/limitar-vida-recurso/", homeURL],
  ["/defends/scala/obtener-rutas-canon/", homeURL],
  ["/resources/doc/skims/lib_path/f073.html", homeURL],
  ["/resources/doc/skims/integrates/limits.html", homeURL],
  ["/findings/101/", homeURL],
  ["/products/rules/list/090/", homeURL],
  ["/resources/doc/asserts/fluidasserts.ot.powerlogic/", homeURL],
  ["/blog/authors/andres-roldan/index2.html", homeURL],
  ["/products/defends/glassfish/definir-rol-seguridad/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.ftp/", homeURL],
  ["/findings/018/", homeURL],
  ["/products/rules/list/092/", homeURL],
  ["/blog/categories/attacks/index5.html", homeURL],
  ["/products/rules/list/094/", homeURL],
  ["/resources/doc/skims/utils/concurrency.html", homeURL],
  ["/blog/tags/information/index3.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.vpc/", homeURL],
  ["/products/defends/java/definir-permisos/", homeURL],
  ["/products/rules/list/095/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.azure.virtual_machines/",
    homeURL,
  ],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.iam/", homeURL],
  ["/partners/gamma-ingenieros/", homeURL],
  ["/findings/105/", homeURL],
  ["/products/defends/aspnet/codificar-salida/", homeURL],
  ["/products/rules/list/096/", homeURL],
  ["/defends/yii/usar-recaptcha/", homeURL],
  ["/products/rules/list/180/", homeURL],
  ["/products/rules/list/097/", homeURL],
  ["/products/defends/glassfish/revisar-bitacora/", homeURL],
  ["/asserts/fluidasserts.cloud.aws.cloudformation.fsx/", homeURL],
  ["/products/rules/findings/039/", homeURL],
  ["/products/defends/aspnet/remover-metadata-imgs/", homeURL],
  ["/products/rules/list/098/", homeURL],
  ["/services/continuous-hacking/environments/", homeURL],
  ["/resources/doc/skims/utils/ast.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.jwt/", homeURL],
  ["/products/rules/list/184/", homeURL],
  ["/services/one-shot-hacking/vuln-manage/", homeURL],
  ["/resources/doc/skims/integrates/dal.html", homeURL],
  ["/products/rules/list/099/", homeURL],
  ["/defends/windows/cambiar-credenciales/", homeURL],
  ["/techniques/sre/", homeURL],
  ["/resources/doc/asserts/py-modindex/", homeURL],
  ["/blog/categories/philosophy/index2.html", homeURL],
  ["/findings/056/", homeURL],
  ["/products/rules/list/052/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.s3/", homeURL],
  ["/rules/150/", homeURL],
  ["/products/rules/findings/037/", homeURL],
  ["/findings/059/", homeURL],
  ["/products/defends/java/mantener-conexiones-db/", homeURL],
  ["/solutions/cloud-infrastructure/", homeURL],
  ["/findings/010/", homeURL],
  ["/products/rules/findings/120/", homeURL],
  ["/products/defends/aspnet/reutilizar-objetos-bucles/", homeURL],
  ["/blog/tags/hacking/index2.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang/", homeURL],
  ["/resources/doc/asserts/install/", homeURL],
  ["/products/rules/list/140/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.rest/", homeURL],
  ["/products/rules/list/273/", homeURL],
  ["/products/rules/list/055/", homeURL],
  ["/products/rules/findings/036/", homeURL],
  ["/resources/doc/skims/utils/url.html", homeURL],
  ["/search.html?q=CWE", homeURL],
  ["/blog/tags/vulnerability/index3.html", homeURL],
  ["/products/rules/list/044/", homeURL],
  ["/products/rules/findings/033/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.file/", homeURL],
  ["/products/defends/cobol/usar-estructuras-optimizadas/", homeURL],
  ["/products/rules/list/130/", homeURL],
  ["/products/defends/aspnet/filtrar-campos-entrada/", homeURL],
  ["/resources/doc/asserts/fluidasserts/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.rds/", homeURL],
  ["/products/rules/list/179/", homeURL],
  ["/rules/152/", homeURL],
  ["/asserts/fluidasserts.cloud.azure.network_security_groups/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud/", homeURL],
  ["/blog/categories/opinions/index2.html", homeURL],
  ["/products/rules/list/047/", homeURL],
  ["/products/rules/findings/032/", homeURL],
  ["/products/rules/list/133/", homeURL],
  ["/defends/scala/limitar-vida-recurso/", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.maven/", homeURL],
  ["/products/rules/findings/077/", homeURL],
  ["/products/defends/java/gestionar-keystore/", homeURL],
  ["/rules/159/", homeURL],
  ["/resources/doc/asserts/fluidasserts.iot.camera/", homeURL],
  ["/resources/doc/asserts/fluidasserts.format.apk/", homeURL],
  [
    "/products/defends/java/usar-ejb-time-service/src/timeservlet.java",
    homeURL,
  ],
  ["/resources/doc/skims/integrates/graphql.html", homeURL],
  ["/products/rules/list/352/", homeURL],
  ["/products/rules/findings/078/", homeURL],
  ["/products/defends/cobol/comprobar-password/", homeURL],
  ["/products/rules/list/220/", homeURL],
  ["/products/rules/findings/075/", homeURL],
  ["/products/rules/list/002/", homeURL],
  ["/findings/065/", homeURL],
  ["/resources/doc/asserts/fluidasserts.lang.core/", homeURL],
  ["/resources/doc/skims/aws/iam/structure.html", homeURL],
  ["/products/rules/list/221/", homeURL],
  ["/products/rules/list/354/", homeURL],
  ["/products/rules/list/136/", homeURL],
  ["/techniques/re/", homeURL],
  ["/resources/doc/skims/lib_path/f031_cwe378.html", homeURL],
  ["/products/rules/list/222/", homeURL],
  ["/products/rules/list/004/", homeURL],
  ["/products/rules/findings/073/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform/", homeURL],
  ["/products/rules/list/005/", homeURL],
  ["/products/rules/list/138/", homeURL],
  ["/products/rules/findings/074/", homeURL],
  ["/products/defends/csharp/limitar-vida-recurso/src/myreadfile.cs", homeURL],
  ["/products/defends/windows/cambiar-credenciales/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.tcp/", homeURL],
  ["/products/rules/list/139/", homeURL],
  ["/products/rules/list/006/", homeURL],
  ["/defends/cobol/prevenir-xss/", homeURL],
  ["/defends/java/utilizar-pool-conexion/", homeURL],
  ["/rules/113/", homeURL],
  ["/products/rules/list/225/", homeURL],
  ["/rules/114/", homeURL],
  ["/resources/doc/asserts/fluidasserts.helper.yaml_loader_alt/", homeURL],
  ["/resources/doc/skims/parse_common/index.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.terraform.ebs/", homeURL],
  ["/defends/aspnet/usar-regex/", homeURL],
  ["/products/rules/list/311/", homeURL],
  ["/blog/tags/cybersecurity/index3.html", homeURL],
  ["/rules/204/", homeURL],
  ["/rules/337/", homeURL],
  ["/resources/doc/asserts/fluidasserts.utils.parsers.json/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.azure.app_services/", homeURL],
  ["/products/rules/list/312/", homeURL],
  ["/rules/338/", homeURL],
  ["/products/rules/findings/070/", homeURL],
  ["/resources/doc/skims/utils/system.html", homeURL],
  ["/resources/doc/skims/lib_path/f031_aws.html", homeURL],
  ["/products/rules/list/313/", homeURL],
  ["/resources/doc/asserts/fluidasserts.cloud.aws.ec2/", homeURL],
  ["/products/rules/list/228/", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.smb/", homeURL],
  ["/blog/tags/ethical-hacking/index2.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.proto.smtp/", homeURL],
  ["/resources/doc/skims/core/entrypoint.html", homeURL],
  ["/resources/doc/skims/parse_java_properties/index.html", homeURL],
  ["/resources/doc/asserts/fluidasserts.sca.nuget/", homeURL],
  [
    "/resources/doc/asserts/fluidasserts.cloud.aws.cloudformation.ec2/",
    homeURL,
  ],
  ["/products/rules/list/314/", homeURL],
  ["/products/rules/list/229/", homeURL],
  ["/search.html?q=bsimm9", homeURL],
  ["/defends/java/listar-criptografico/src/cli.java", homeURL],
  ["/solutions/security-testing/partners/choucair/", homeURL],
  ["/solutions/security-testing/about-us/people/dcardona/", homeURL],
  ["/partners/gamma-ingenieros/", homeURL],
  [
    "/blog/what-is-devsecops",
    "https://fluidattacks.com/blog/devsecops-concept/",
  ],
  [
    "/blog/what-is-devsecops/",
    "https://fluidattacks.com/blog/devsecops-concept/",
  ],
  [
    "/web/blog/updating-belief",
    "https://fluidattacks.com/blog/updating-belief/",
  ],
  [
    "/web/blog/updating-belief/",
    "https://fluidattacks.com/blog/updating-belief/",
  ],
  [
    "/web/blog/reversing-mortals/image3.png",
    "https://fluidattacks.com/blog/reversing-mortals/",
  ],
  [
    "/web/blog/reversing-mortals",
    "https://fluidattacks.com/blog/reversing-mortals/",
  ],
  [
    "/web/blog/reversing-mortals/",
    "https://fluidattacks.com/blog/reversing-mortals/",
  ],
  ["/security-testing", "https://fluidattacks.com/solutions/security-testing/"],
  [
    "/security-testing/",
    "https://fluidattacks.com/solutions/security-testing/",
  ],
  ["/products/defends/java/validar-correo-electronico", homeURL],
  ["/products/defends/java/validar-correo-electronico/", homeURL],
  [
    "/blog/gherkin-steroids/local-file-inclusion.feature/",
    "https://fluidattacks.com/blog/gherkin-steroids/local-file-inclusion.feature",
  ],
  [
    "/blog/libssh-bypass-cve/cve201810933.zip/",
    "https://fluidattacks.com/blog/libssh-bypass-cve/cve201810933.zip",
  ],
  [
    "/blog/my-heart-bleeds/openssl-fragment.c/",
    "https://fluidattacks.com/blog/my-heart-bleeds/openssl-fragment.c",
  ],
  [
    "/blog/pars-orationis-secura/results.txt/",
    "https://fluidattacks.com/blog/pars-orationis-secura/results.txt",
  ],
  [
    "/blog/pars-orationis-secura/sqli-parser.py/",
    "https://fluidattacks.com/blog/pars-orationis-secura/sqli-parser.py",
  ],
  [
    "/blog/pars-orationis-secura/redux-sqli-7.php/",
    "https://fluidattacks.com/blog/pars-orationis-secura/redux-sqli-7.php",
  ],
  [
    "/blog/pars-orationis-secura/test-cases.lst/",
    "https://fluidattacks.com/blog/pars-orationis-secura/test-cases.lst",
  ],
  [
    "/services/one-shot-hacking/",
    "https://fluidattacks.com/services/continuous-hacking/",
  ],
  [
    "/services/comparative/",
    "https://fluidattacks.com/services/continuous-hacking/",
  ],
  [
    "/blog/amsi-bypass-python/amsibypass.py/",
    "https://fluidattacks.com/blog/amsi-bypass-python/amsibypass.py",
  ],
  [
    "/blog/netscan-exploit/exploit.py/",
    "https://fluidattacks.com/blog/netscan-exploit/exploit.py",
  ],
  [
    "/blog/offensive-hyperv-directx-1/sample1.c/",
    "https://fluidattacks.com/blog/offensive-hyperv-directx-1/sample1.c",
  ],
  [
    "/blog/quantitative-python/events-redux.csv/",
    "https://fluidattacks.com/blog/quantitative-python/events-redux.csv",
  ],
  [
    "/blog/quantitative-python/quant.ipynb/",
    "https://fluidattacks.com/blog/quantitative-python/quant.ipynb",
  ],
  [
    "/blog/quantitative-python/quant.py/",
    "https://fluidattacks.com/blog/quantitative-python/quant.py",
  ],
  [
    "/blog/quantitative-python/events.csv/",
    "https://fluidattacks.com/blog/quantitative-python/events.csv",
  ],
  [
    "/blog/quickzip-exploit/exploit.py/",
    "https://fluidattacks.com/blog/quickzip-exploit/exploit.py",
  ],
  [
    "/blog/vulnserver-gmon/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-gmon/exploit.py",
  ],
  [
    "/blog/vulnserver-gter-no-egghunter/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-gter-no-egghunter/exploit.py",
  ],
  [
    "/blog/vulnserver-gter/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-gter/exploit.py",
  ],
  [
    "/blog/vulnserver-kstet-alternative/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-kstet-alternative/exploit.py",
  ],
  [
    "/blog/vulnserver-kstet/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-kstet/exploit.py",
  ],
  [
    "/blog/vulnserver-lter-seh/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-lter-seh/exploit.py",
  ],
  [
    "/blog/vulnserver-trun-rop/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-trun-rop/exploit.py",
  ],
  [
    "/blog/vulnserver-trun/exploit.py/",
    "https://fluidattacks.com/blog/vulnserver-trun/exploit.py",
  ],
  ["/product-overview/", "https://fluidattacks.com/platform/"],
  ["/categories/arm/", "https://fluidattacks.com/platform/arm/"],
  ["/categories/sast/", "https://fluidattacks.com/product/sast/"],
  ["/categories/dast/", "https://fluidattacks.com/product/dast/"],
  ["/categories/sca/", "https://fluidattacks.com/product/sca/"],
  ["/categories/re/", "https://fluidattacks.com/product/re/"],
  ["/categories/ptaas/", "https://fluidattacks.com/product/ptaas/"],
  ["/categories/mast/", "https://fluidattacks.com/product/mast/"],
  ["/about-us/clients/", " https://fluidattacks.com/clients/"],
  ["/about-us/certifications/", "https://fluidattacks.com/certifications/"],
  [
    "/blog/product/attacks/",
    "https://fluidattacks.com/blog/categories/attacks/",
  ],
  [
    "/blog/product/development/",
    "https://fluidattacks.com/blog/categories/development/",
  ],
  [
    "/blog/product/interview/",
    "https://fluidattacks.com/blog/categories/interview/",
  ],
  [
    "/blog/product/opinions/",
    "https://fluidattacks.com/blog/categories/opinions/",
  ],
  [
    "/blog/product/philosophy/",
    "https://fluidattacks.com/blog/categories/philosophy/",
  ],
  [
    "/blog/product/politics/",
    "https://fluidattacks.com/blog/categories/politics/",
  ],
  [
    "/web/en/blog/",
    "https://fluidattacks.com/blog/",
  ],
  [
    "/faq/",
    homeURL,
  ],
]);

addEventListener("fetch", (event) => {
  event.respondWith(addHeaders(event.request));
});

async function addHeaders(req) {
  const response = await fetch(req);
  const newHdrs = new Headers(response.headers);

  const requestURL = new URL(response.url);
  const path = requestURL.pathname;
  const location = redirectMap.get(path);

  if (location) {
    return Response.redirect(location, 301);
  }

  if (
    newHdrs.has("Content-Type") &&
    !newHdrs.get("Content-Type").includes("text/html")
  ) {
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: newHdrs,
    });
  }

  Object.keys(securityHeaders).forEach((name) => {
    newHdrs.set(name, securityHeaders[name]);
  });

  Object.keys(sanitiseHeaders).forEach((name) => {
    newHdrs.set(name, sanitiseHeaders[name]);
  });

  removeHeaders.forEach(function (name) {
    newHdrs.delete(name);
  });

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: newHdrs,
  });
}
