AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:t1qX18V/G/gVBrs1ao8UmT6XqTTcya8uNe91PUq3uNMvjIdX4tZhkiIovQYvt5rXyGE0h25XGrsI7u4YhFjdfQ==,iv:M5+hZsLOBFczAF3RuxUu9dCbtJbiJrj1BzrZkZbCqtQ=,tag:Q4NJLWEKtWxhMV0yXbmxPQ==,type:str]
CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:5yo+oh1eqEA5Mg2Ny4hwMfofJO4gOSiRON/QYlPGWqI=,iv:2H9pftrqedCEX8HGeD2GPqbuRX8UPKfGmKhXVOaIJZg=,tag:upkeHOZrFJnrhZmM4N1T9A==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:q410Qq8zlqKgY14cRr6j+N6W0WtjMfP6wk4QuVy1IpcaOz5SdAmQnA==,iv:AbX+p4GkSfyjaVsAhK3aTP296+8jqIZBG+GnALDERAc=,tag:kUU6gBvCJCOIwt+gtkYUxw==,type:str]
CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:As7aObPF1lI3fz5ssQ==,iv:rdafXWk2U/rF9ryNfQrwqpa6WLLqceB7NIelVdiT8RQ=,tag:gRCJE/wrCuKGP7FM0QRsVw==,type:str]
CLOUDINARY_API_KEY: ENC[AES256_GCM,data:2ehhAyuz8DYGDMs0Rx+9,iv:zIcHDIXQjmcFxijWIqy+TW+YSj8dWti1OXAg6VBRJp0=,tag:v3S16YEkEUze1Wmg0ULZWA==,type:int]
CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:b45Rx3pFJhjiHyTE0/VQiXARfaTY7+ReG/LG,iv:nOnXaHXPi/8KAkG2+TB7xy+QwkBQf7vNs5NrNiVnb90=,tag:8/bjB3f3X+xkE/tiorKa3g==,type:str]
GATSBY_ALGOLIA_APP_ID: ENC[AES256_GCM,data:DEcMQGdlUdUaSg==,iv:iKu9bNL7QXZdX5QgxX1NRPzKOzzcfd2FsHEnhn4AH0Q=,tag:EU9K/Qp/lE43NnZxzP2jAw==,type:str]
GATSBY_ALGOLIA_SEARCH_KEY: ENC[AES256_GCM,data:F3CdJ4awl2s8ml0d6MH22UARFNdF+KmAnZxBq0tjKKs=,iv:VFb6jAHRwh4/Qr6XMLDp5A0pC4OK5jguimQMCbcMhz0=,tag:tWHcffui41nYs2VdiiUQOg==,type:str]
ALGOLIA_ADMIN_KEY: ENC[AES256_GCM,data:ZrMwfpsDIa3kwDV9WTN8AGSC+1psmoEhoxb3OpLYRf0=,iv:7ccfkASBvNtMgFpxADGojm9hQNkTYOmV5jJNkzYuLHo=,tag:FJd9AZ8GDZvjeF4csha3Tw==,type:str]
GATSBY_AUTH0_DOMAIN: ENC[AES256_GCM,data:sL5wWqLfeEpEZgmQFRKZbF1SxcWdUj6EYA==,iv:QJk56DA7FfeU7g9cDdfbhk38wzkeVC2GNQ/4j2FmjNk=,tag:CwsEpWctdzha4bTJe/ugyQ==,type:str]
GATSBY_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:GUd7RhM2f4GdIUxsAdUWoNOSXk7sqG1svc4AfVwaB1k=,iv:LogKAZTLzwX00HFpLUUQJieUR4vK49tsiDjPrNT/bbA=,tag:MHpFrAOzAnmeBX6uowgcnA==,type:str]
GATSBY_AUTH0_CALLBACK: ENC[AES256_GCM,data:Jr0jGrERyqUFt4oQOQTXyeH9fHffv8BC,iv:668XbCmISTG4lGoqnq9e9rXTGBPXZXOTrbxpCz0sTGY=,tag:HlAIsVFXutkQb3wFe41jGQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:205810638802:alias/dev
          created_at: "2022-02-18T22:29:33Z"
          enc: AQICAHhXTEro6XxD1aUcNM+ov9OG4EgBp9RTxhGglF2qwWCpLAGxPTBkMU1TsA4c9wN6dDbPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZBK9rAAK5JJV/PaQAgEQgDvBuGGM0YJl7HOTcRSHhskjaj878kFZ9y/AqbiuFVGe133FwdndAuWljgnZyyQ1P3hQgend7oiV3pRdeQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-16T12:46:53Z"
    mac: ENC[AES256_GCM,data:I8Pb225fWYaFb0v+2+XhToSa3xiO2ujg1pgONTbawMQLA9B3aaud1at+Th2sJZSms/zDjde7wPofEcnqsiA3+j3HbOpjYv/lJ3oDw+yQ+68i9TRIv3z7A7Rx9F4xAaSknJs/EJAcEXM9Q9xnpFfqBF2bEBlv5AG03hHjc0/Fd4Y=,iv:zNSDMrHlcgE0/eBfriRolLHH9lczLdaAwEOg9dS5KVE=,tag:J+7Sq3+MU/LWE2y4fG2aWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
