CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:0OUuc2KhfnjayuNjmCDdPIy5hgs39QBibb0Y88zj/gY=,iv:gplZzcbKj2w3xISbKk/7HUkKakbK2qf/b0zzH6KAC0w=,tag:CkUpEsiX68hicru5oI+Djw==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:+tiqWkAFdu35ob0XLC86e+U8LC0GGLjcoh62cvzFXQ+BKxx8SpCsrQ==,iv:FMevsYW1LHtFzZydekRIYsUoCQBUWZE6hZOu7CpVK1Y=,tag:iv6sAgSJsOrb693Zs2ceXg==,type:str]
CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:DiPIruCemFGO1IT99g==,iv:AQHvaHcNlE1c3COQQEHVC0ClRtMsRzxGQC3YG4Rw/6w=,tag:NlCEHeTjgLZrnMME6Z2gDA==,type:str]
CLOUDINARY_API_KEY: ENC[AES256_GCM,data:5CPz3imC+r/3Gd+SBsaG,iv:dhSiAlJxnyTcQZRaOwiXoUW+JfC+sRC3UFtMaUQE+JE=,tag:fgggS8BJw7Z9DmZGt+V6iw==,type:int]
CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:zS6kupFkhQwooDZPSa3Hv3vZKtl8zwA7sLph,iv:ygxU3uNBwORaEZ/8k7SKR+y+7T9jHhl+519FIvo6ZPE=,tag:ysvHRkGN8VCfAN5G03XrnA==,type:str]
AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:oHcM2CLtVkigTKIhekxRe0T3ChUoBZ2iiyTpc59YB4s9IhSXpLMMHsLyMjxnLJlaVsGhXzfRqoZUYfwvPh3m+A==,iv:GHvi68IoC6JeYlIzoG4TDs9TDosmnZ6yqap1A9ZiWF8=,tag:6tJ8KMLEoybpqiVS8Wm6Zw==,type:str]
GATSBY_AUTH0_DOMAIN: ENC[AES256_GCM,data:8qOQ6LfR8t5d+t0DkeLTtedtaZvNsXqFFQ==,iv:Q+bshP2gJw7PtJdo4aNQKq5XT2OvymFJe/Mt3DykvOw=,tag:0d/kLpYFnQ0MyuqiFOrz5w==,type:str]
GATSBY_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:CImYt5DzuMSWQRLyi31AzOh/b5v7MVMA6xdPc6fMphE=,iv:d2co46cJ/D0JisHAXK+4Sy6oMbHhrlGWy+aRoMVNQvs=,tag:sKJfgiag+4zB1LYsiblHRw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:205810638802:alias/prod_airs
          created_at: "2022-02-21T21:28:11Z"
          enc: AQICAHiHF4y5xdTeEFAt+lqmk/uVp6mmJpljpSGoy7356Qx1ogGXHeRZb/4RoHdJEWRK65ehAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMC20l5I3OpmW6RTc3AgEQgDsF0lwmYweVGNIRV5Hzd2qOXPOmYXYc6zJM1xJzo33vkplp8BggUERInR/Kd5WOuuuT6OVWVHbjUSSn5g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-16T12:41:03Z"
    mac: ENC[AES256_GCM,data:92AI2n+6fwXK3+atjW+VpA1suira1sUSoNTU3iE8Kcrf9h7Fau8wVcl0Yxdx/f4f09/5cd3S4hAYzPYZHx34FsXufZ8EXirOp5KBdaMgqBJ90jPD5NzHZ5xV348L15laVLAFiFvBGCtPeI9B8lIMO3c6em6FjuHxKYgc4qJHBis=,iv:lE/WVHsd0Dp24g2dYTUpHmPyDjZeEzmyDzU4evJXF/g=,tag:OldpdpyPdF+EZoj7cHpdzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
