/airs/eph:
  image: ghcr.io/fluidattacks/makes/amd64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /airs/eph
  stage: deploy-app
  tags:
    - airs-large-x86
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/airs/lint/code:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /airs/lint/code
  stage: lint-code
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/airs/lint/content:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /airs/lint/content
  stage: lint-code
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/airs/lint/styles:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /airs/lint/styles
  stage: lint-code
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/airs/prod:
  image: ghcr.io/fluidattacks/makes/amd64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH != "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /airs/prod
  stage: deploy-app
  tags:
    - airs-large-x86
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/deployTerraform/airsInfra:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  resource_group: $CI_JOB_NAME
  rules:
    - if: $CI_COMMIT_BRANCH != "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /deployTerraform/airsInfra
  stage: deploy-infra
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/lintMarkdown/airs:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /lintMarkdown/airs
  stage: lint-code
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/lintTerraform/airsInfra:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /lintTerraform/airsInfra
  stage: lint-code
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
/testTerraform/airsInfra:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  resource_group: $CI_JOB_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|airs)/
  script:
    - m . /testTerraform/airsInfra
  stage: test-infra
  tags:
    - airs-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
