# pylint: disable=too-many-lines
from authz.enforcer import (
    get_group_level_enforcer,
)
from collections.abc import (
    Callable,
    Coroutine,
)
from dataloaders import (
    Dataloaders,
)
from datetime import (
    datetime,
)
from db_model.enums import (
    Source,
)
from db_model.finding_comments.enums import (
    CommentType,
)
from db_model.finding_comments.types import (
    FindingComment,
)
from db_model.findings.enums import (
    FindingVerificationStatus,
)
from db_model.findings.types import (
    FindingVerification,
)
from db_model.group_access.types import (
    GroupAccess,
    GroupAccessState,
)
from db_model.vulnerabilities.enums import (
    VulnerabilityStateStatus,
    VulnerabilityToolImpact,
    VulnerabilityTreatmentStatus,
    VulnerabilityType,
    VulnerabilityVerificationStatus,
)
from db_model.vulnerabilities.types import (
    Vulnerability,
    VulnerabilityState,
    VulnerabilityTool,
    VulnerabilityTreatment,
    VulnerabilityUnreliableIndicators,
    VulnerabilityVerification,
)
from decimal import (
    Decimal,
)
import pytest
from typing import (
    Any,
)
from unittest.mock import (
    AsyncMock,
    patch,
)

pytestmark = [
    pytest.mark.asyncio,
]


MOCKED_DATA: dict[str, dict[str, Any]] = {
    "finding_comments.domain.Dataloaders.finding_historic_verification": {
        '["436992569"]': [
            FindingVerification(
                comment_id="1558048727000",
                modified_by="integratesuser@gmail.com",
                modified_date=datetime.fromisoformat(
                    "2019-04-08T00:43:18+00:00"
                ),
                status=FindingVerificationStatus.REQUESTED,
                vulnerability_ids={
                    "15375781-31f2-4953-ac77-f31134225747",
                    "587c40de-09a0-4d85-a9f9-eaa46aa895d7",
                },
            ),
            FindingVerification(
                comment_id="1558048727000",
                modified_by="integratesuser@gmail.com",
                modified_date=datetime.fromisoformat(
                    "2020-02-19T15:41:04+00:00"
                ),
                status=FindingVerificationStatus.REQUESTED,
                vulnerability_ids={
                    "15375781-31f2-4953-ac77-f31134225747",
                    "587c40de-09a0-4d85-a9f9-eaa46aa895d7",
                },
            ),
            FindingVerification(
                comment_id="1558048727111",
                modified_by="integrateshacker@fluidattacks.com",
                modified_date=datetime.fromisoformat(
                    "2020-02-21T15:41:04+00:00"
                ),
                status=FindingVerificationStatus.VERIFIED,
                vulnerability_ids={"15375781-31f2-4953-ac77-f31134225747"},
            ),
        ]
    },
    "finding_comments.domain.Dataloaders.finding_vulnerabilities": {
        '["436992569"]': [
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T13:17:41+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="15375781-31f2-4953-ac77-f31134225747",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T13:17:41+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.101",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=VulnerabilityTool(
                        name="tool-2",
                        impact=VulnerabilityToolImpact.INDIRECT,
                    ),
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T13:17:41+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=datetime.fromisoformat(
                        "2020-02-19T15:41:04+00:00"
                    ),
                    unreliable_last_reattack_requester="integratesuser@gmail.com",  # noqa: E501 pylint: disable=line-too-long
                    unreliable_last_requested_reattack_date=datetime.fromisoformat(  # noqa: E501 pylint: disable=line-too-long
                        "2020-02-18T15:41:04+00:00"
                    ),
                    unreliable_reattack_cycles=1,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T13:17:41+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=VulnerabilityVerification(
                    modified_date=datetime.fromisoformat(
                        "2020-02-19T15:41:04+00:00"
                    ),
                    status=VulnerabilityVerificationStatus.VERIFIED,
                    event_id=None,
                ),
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="1c644e88-b7a2-498b-b248-c3d367629982",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="1111",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.12",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=VulnerabilityTool(
                        name="tool-2",
                        impact=VulnerabilityToolImpact.INDIRECT,
                    ),
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="3ec662b9-431a-475c-97e4-ac6ad4cabd90",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="3333",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.4",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=VulnerabilityTool(
                        name="tool-2",
                        impact=VulnerabilityToolImpact.INDIRECT,
                    ),
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id="EVENT#418900971",
                hash=None,
                root_id="4039d098-ffc5-4984-8ed3-eb17bca98e19",
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=VulnerabilityVerification(
                    modified_date=datetime.fromisoformat(
                        "2022-02-19T15:41:04+00:00"
                    ),
                    status=VulnerabilityVerificationStatus.ON_HOLD,
                    event_id="418900971",
                ),
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="47910cbe-932a-411b-8a46-9570a87f4663",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="6666",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.17",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id="EVENT#418900971",
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=VulnerabilityVerification(
                    modified_date=datetime.fromisoformat(
                        "2022-02-19T15:41:04+00:00"
                    ),
                    status=VulnerabilityVerificationStatus.ON_HOLD,
                    event_id="418900971",
                ),
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="4ed30d35-33a5-44ba-af44-6cb253be053b",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="4444",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.15",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=VulnerabilityTool(
                        name="tool-3",
                        impact=VulnerabilityToolImpact.INDIRECT,
                    ),
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="5291f6fa-b296-4e89-a760-798ce56f17d0",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="5555",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.6",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=VulnerabilityTool(
                        name="tool-3",
                        impact=VulnerabilityToolImpact.INDIRECT,
                    ),
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="57e5c1ec-5956-40e9-8e30-284033c1140d",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="9999",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.10",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=VulnerabilityTool(
                        name="tool-3",
                        impact=VulnerabilityToolImpact.INDIRECT,
                    ),
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T22:00:56+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="587c40de-09a0-4d85-a9f9-eaa46aa895d7",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T22:00:56+00:00"
                    ),
                    source=Source.ASM,
                    specific="1111",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.112",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T22:00:56+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester="integratesuser@gmail.com",  # noqa: E501 pylint: disable=line-too-long
                    unreliable_last_requested_reattack_date=datetime.fromisoformat(  # noqa: E501 pylint: disable=line-too-long
                        "2020-02-19T15:41:04+00:00"
                    ),
                    unreliable_reattack_cycles=1,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T22:00:56+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=VulnerabilityVerification(
                    modified_date=datetime.fromisoformat(
                        "2020-02-19T15:41:04+00:00"
                    ),
                    status=VulnerabilityVerificationStatus.REQUESTED,
                    event_id=None,
                ),
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T14:58:38+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="5afb9a49-a359-48ce-80ee-79c145919275",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T14:58:38+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.105",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T14:58:38+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T14:58:38+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T20:37:59+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="5ed5c3c0-9064-41f5-8ef2-5e1eeee62955",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T20:37:59+00:00"
                    ),
                    source=Source.ASM,
                    specific="1111",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.111",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T20:37:59+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T20:37:59+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T16:03:21+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="72bb8607-c259-4781-9599-185aac02b3cc",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T16:05:05+00:00"
                    ),
                    source=Source.ASM,
                    specific="4444",
                    status=VulnerabilityStateStatus.SAFE,
                    where="192.168.100.101",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T16:03:21+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=datetime.fromisoformat(
                        "2019-09-13T16:05:05+00:00"
                    ),
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T16:03:21+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="759aaf00-34ee-4609-aec6-7f857c470eff",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="4444",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.5",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="integratesmanager@gmail.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T13:59:20+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="integratesmanager@gmail.com",
                id="81db1fad-c329-4356-a5eb-9ad9b0d75a7e",
                state=VulnerabilityState(
                    modified_by="aaguirre@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T13:59:20+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.104",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T13:59:20+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T13:59:20+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T15:00:03+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="8226e222-8128-438d-a9b7-93eeb93a36b3",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T15:09:02+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.SAFE,
                    where="192.168.100.107",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T15:00:03+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=datetime.fromisoformat(
                        "2019-09-13T15:09:02+00:00"
                    ),
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T15:00:03+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="95068fdd-80ca-4eb2-8311-b16b63a61f05",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="8888",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.9",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-16T21:01:24+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="987a6d71-d23c-40db-ad98-bfccf60660ed",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-16T21:01:24+00:00"
                    ),
                    source=Source.ASM,
                    specific="888",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.122",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-16T21:01:24+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-16T21:01:24+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="aa6a9d70-618b-4ab0-b280-d627ce311200",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="6666",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.7",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="ab25380d-dfe1-4cde-aefd-acca6990d6aa",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="1111",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.2",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="ae16f325-a492-482b-a7a1-6285e8057480",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="2222",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.3",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="b16ed89e-668d-42d6-add1-73535bb0e083",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="2222",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.13",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="bac162ff-5c2a-4a96-9b77-fd7020976160",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="7777",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.8",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T15:53:05+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="bf818399-b331-4fa4-b335-98548e037378",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T16:28:20+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.SAFE,
                    where="192.168.100.109",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T15:53:05+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=datetime.fromisoformat(
                        "2019-09-13T16:28:20+00:00"
                    ),
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T15:53:05+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="c8161719-5ac8-45ba-a3fb-ab69ea39ddcb",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="5555",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.16",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-12T13:45:48+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="d212a841-7d48-4cb6-b776-cccc2845c383",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    source=Source.ASM,
                    specific="3333",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.1.14",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-12T13:45:48+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T20:19:17+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="d4d4c6a0-3d51-42cf-b93f-4c503f67d72d",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T20:19:17+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.108",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T20:19:17+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T20:19:17+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-08-30T14:30:13+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="f2d577b4-855b-41fc-a844-2b96f797775c",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-08-30T14:30:13+00:00"
                    ),
                    source=Source.ASM,
                    specific="asserts",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="testing",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.INPUTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-08-30T14:30:13+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-08-30T14:30:13+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="unittest@fluidattacks.com",
                created_date=datetime.fromisoformat(
                    "2019-09-16T20:02:17+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="unittest@fluidattacks.com",
                id="fc01759b-0f2f-4e4e-9e24-5c27c91d574b",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-16T20:02:17+00:00"
                    ),
                    source=Source.ASM,
                    specific="1111",
                    status=VulnerabilityStateStatus.VULNERABLE,
                    where="192.168.100.113",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-16T20:02:17+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=None,
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-16T20:02:17+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
            Vulnerability(
                created_by="integratesmanager@gmail.com",
                created_date=datetime.fromisoformat(
                    "2019-09-13T14:03:05+00:00"
                ),
                finding_id="436992569",
                group_name="unittesting",
                organization_name="okada",
                hacker_email="integratesmanager@gmail.com",
                id="feabfd52-0b0f-405e-bf6a-e9a224af6726",
                state=VulnerabilityState(
                    modified_by="unittest@fluidattacks.com",
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T14:03:05+00:00"
                    ),
                    source=Source.ASM,
                    specific="333",
                    status=VulnerabilityStateStatus.SAFE,
                    where="192.168.100.103",
                    commit=None,
                    reasons=None,
                    other_reason=None,
                    tool=None,
                    snippet=None,
                ),
                type=VulnerabilityType.PORTS,
                bug_tracking_system_url=None,
                custom_severity=None,
                developer=None,
                event_id=None,
                hash=None,
                root_id=None,
                skims_method=None,
                skims_technique=None,
                stream=None,
                tags=None,
                treatment=VulnerabilityTreatment(
                    modified_date=datetime.fromisoformat(
                        "2019-09-13T14:03:05+00:00"
                    ),
                    status=VulnerabilityTreatmentStatus.UNTREATED,
                    acceptance_status=None,
                    accepted_until=None,
                    justification=None,
                    assigned=None,
                    modified_by=None,
                ),
                unreliable_indicators=VulnerabilityUnreliableIndicators(
                    unreliable_closing_date=datetime.fromisoformat(
                        "2019-09-13T14:03:05+00:00"
                    ),
                    unreliable_source=Source.ASM,
                    unreliable_efficacy=Decimal("0"),
                    unreliable_last_reattack_date=None,
                    unreliable_last_reattack_requester=None,
                    unreliable_last_requested_reattack_date=None,
                    unreliable_reattack_cycles=0,
                    unreliable_report_date=datetime.fromisoformat(
                        "2019-09-13T14:03:05+00:00"
                    ),
                    unreliable_treatment_changes=0,
                ),
                verification=None,
                zero_risk=None,
            ),
        ]
    },
    "finding_comments.domain.get_unformatted_comments": {
        '["436992569"]': [
            FindingComment(
                comment_type=CommentType.VERIFICATION,
                content="This is a commenting test of a request verification "
                "in vulns",
                creation_date=datetime.fromisoformat(
                    "2020-02-19T15:41:04+00:00"
                ),
                email="integratesuser@gmail.com",
                finding_id="436992569",
                id="1558048727000",
                parent_id="0",
                full_name="user Integrates",
            ),
            FindingComment(
                comment_type=CommentType.VERIFICATION,
                content="this is a commenting test of a verifying request "
                "verification in vulns",
                creation_date=datetime.fromisoformat(
                    "2020-02-21T15:41:04+00:00"
                ),
                email="integrateshacker@fluidattacks.com",
                finding_id="436992569",
                id="1558048727111",
                parent_id="0",
                full_name="hacker Integrates",
            ),
        ]
    },
    "finding_comments.domain._fill_vuln_info": {
        '["436992569"]': [
            FindingComment(
                comment_type=CommentType.VERIFICATION,
                content="Regarding vulnerabilities: \n  "
                "- 192.168.100.101\n  - 192.168.100.112\n\nThis "
                "is a commenting test of a request verification "
                "in vulns",
                creation_date=datetime.fromisoformat(
                    "2020-02-19T15:41:04+00:00"
                ),
                email="integratesuser@gmail.com",
                finding_id="436992569",
                id="1558048727000",
                parent_id="0",
                full_name="user Integrates",
            ),
            FindingComment(
                comment_type=CommentType.VERIFICATION,
                content="Regarding vulnerabilities: \n  - 192.168.100.101\n  "
                "- 192.168.100.112\n\nThis is a commenting test of a request "
                "verification in vulns",
                creation_date=datetime.fromisoformat(
                    "2020-02-19T15:41:04+00:00"
                ),
                email="integratesuser@gmail.com",
                finding_id="436992569",
                id="1558048727000",
                parent_id="0",
                full_name="user Integrates",
            ),
            FindingComment(
                comment_type=CommentType.VERIFICATION,
                content="Regarding vulnerabilities: \n  - 192.168.100.101\n\n"
                "this is a commenting test of a verifying request "
                "verification in vulns",
                creation_date=datetime.fromisoformat(
                    "2020-02-21T15:41:04+00:00"
                ),
                email="integrateshacker@fluidattacks.com",
                finding_id="436992569",
                id="1558048727111",
                parent_id="0",
                full_name="hacker Integrates",
            ),
        ]
    },
}

MOCK_GROUP_ACCESS = {
    "unittest@fluidattacks.com": [
        GroupAccess(
            email="unittest@fluidattacks.com",
            group_name="unittesting",
            state=GroupAccessState(
                modified_date=datetime.fromisoformat(
                    "2020-01-01T20:07:57+00:00"
                )
            ),
            confirm_deletion=None,
            expiration_time=None,
            has_access=True,
            invitation=None,
            responsibility="Tester",
            role=None,
        )
    ],
}

MOCK_USERS_ROLES: dict[str, str] = {
    "unittest@fluidattacks.com": "admin",
}


@pytest.fixture
def mocked_data_for_module(
    *,
    resolve_mock_data: Callable,
) -> Any:
    def _mocked_data_for_module(
        mock_path: str, mock_args: list[Any], module_at_test: str
    ) -> Callable[[str, list[Any], str], Any]:
        return resolve_mock_data(
            mock_data=MOCKED_DATA,
            mock_path=mock_path,
            mock_args=mock_args,
            module_at_test=module_at_test,
        )

    return _mocked_data_for_module


@pytest.fixture
def side_effect_get_group_level_enforcer() -> (
    Callable[..., Coroutine[Any, Any, Callable[[str, str], bool]]]
):
    @patch("authz.enforcer.get_user_level_role", new_callable=AsyncMock)
    @patch(
        "authz.enforcer.Dataloaders.stakeholder_groups_access",
        new_callable=AsyncMock,
    )
    async def _mock_get_group_level_enforcer(
        loaders: Dataloaders,
        email: str,
        mock_dataloaders_stakeholder_groups_access: AsyncMock,
        mock_get_user_level_role: AsyncMock,
    ) -> Callable[[str, str], bool]:
        # Set up mocks' results using mock data dictionaries
        mock_dataloaders_stakeholder_groups_access.load.return_value = (
            MOCK_GROUP_ACCESS[email]
        )
        mock_get_user_level_role.return_value = MOCK_USERS_ROLES[email]

        enforcer = await get_group_level_enforcer(loaders, email)
        return enforcer

    return _mock_get_group_level_enforcer
