.makes4: &makes4
  image: ghcr.io/fluidattacks/makes/arm64:latest
  needs: []
  interruptible: true
  script:
    - m . "${CI_JOB_NAME% *}"
  variables:
    GIT_DEPTH: 5

.docs_commit_pattern: &docs_commit_pattern $CI_COMMIT_TITLE =~ /^(all|docs)/

.docs_in_dev_branch: &docs_in_dev_branch
  tags: [docs-small]
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: *docs_commit_pattern

.docs_in_prod_branch: &docs_in_prod_branch
  tags: [docs-small]
  resource_group: ${CI_JOB_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH != "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: *docs_commit_pattern

/deployTerraform/docsInfra:
  <<: [*makes4, *docs_in_prod_branch]
  stage: deploy-infra

/docs/deploy/dev:
  <<: [*makes4, *docs_in_dev_branch]
  stage: deploy-app
  script: m . /docs/deploy dev "${CI_COMMIT_REF_NAME}"
  environment:
    name: docs/${CI_COMMIT_REF_NAME}
    url: https://docs-dev.fluidattacks.com/${CI_COMMIT_REF_NAME}/

/docs/deploy/prod:
  <<: [*makes4, *docs_in_prod_branch]
  stage: deploy-app
  script: m . /docs/deploy prod default
  environment:
    name: docs/${CI_COMMIT_REF_NAME}
    url: https://docs.fluidattacks.com/

/docs/generate/criteria:
  <<: [*makes4, *docs_in_dev_branch]
  stage: build

/lintMarkdown/docs:
  <<: [*makes4, *docs_in_dev_branch]
  stage: lint-code

/docs/lint:
  <<: [*makes4, *docs_in_dev_branch]
  stage: lint-code

/lintTerraform/docsInfra:
  <<: [*makes4, *docs_in_dev_branch]
  stage: test-infra

/testTerraform/docsInfra:
  <<: [*makes4, *docs_in_dev_branch]
  stage: lint-code
