apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: integrates-${NAME}
  namespace: prod-integrates
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: integrates-${NAME}
  minReplicas: 5
  maxReplicas: 75
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
