/lintPython/module/melts:
  image: ghcr.io/fluidattacks/makes/arm64:latest
  interruptible: true
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "trunk"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_TITLE =~ /^(all|melts)/
  script:
    - m . /lintPython/module/melts
  stage: lint-code
  tags:
    - melts-small
  variables:
    GIT_DEPTH: 1
    MAKES_GIT_DEPTH: 1
